import { listChannelPlugins } from "../channels/plugins/index.js";

const BASE_METHODS = [
  "health",
  "logs.tail",
  "channels.status",
  "channels.logout",
  "channels.connect",
  "channels.disconnect",
  "channels.whatsapp.generateQR",
  "channels.whatsapp.configure",
  "channels.settings.update",
  "status",
  "usage.status",
  "usage.cost",
  "tts.status",
  "tts.providers",
  "tts.enable",
  "tts.disable",
  "tts.convert",
  "tts.setProvider",
  "config.get",
  "config.set",
  "config.apply",
  "config.patch",
  "config.schema",
  "config.env.get",
  "config.env.set",
  "exec.approvals.get",
  "exec.approvals.set",
  "exec.approvals.node.get",
  "exec.approvals.node.set",
  "exec.approval.request",
  "exec.approval.resolve",
  "wizard.start",
  "wizard.next",
  "wizard.cancel",
  "wizard.status",
  "talk.mode",
  "models.list",
  "agents.list",
  "agents.create",
  "agents.update",
  "agents.delete",
  "agents.files.list",
  "agents.files.get",
  "agents.files.set",
  "skills.status",
  "skills.bins",
  "skills.install",
  "skills.update",
  "update.run",
  "voicewake.get",
  "voicewake.set",
  "sessions.list",
  "sessions.create",
  "sessions.preview",
  "sessions.patch",
  "sessions.reset",
  "sessions.delete",
  "sessions.compact",
  "last-heartbeat",
  "set-heartbeats",
  "wake",
  "node.pair.request",
  "node.pair.list",
  "node.pair.approve",
  "node.pair.reject",
  "node.pair.verify",
  "device.pair.list",
  "device.pair.approve",
  "device.pair.reject",
  "device.token.rotate",
  "device.token.revoke",
  "node.rename",
  "node.list",
  "node.describe",
  "node.invoke",
  "node.invoke.result",
  "node.event",
  "cron.list",
  "cron.status",
  "cron.add",
  "cron.update",
  "cron.remove",
  "cron.run",
  "cron.runs",
  "system-presence",
  "system-event",
  "system.hardware",
  "system.processes",
  "system.traces.list",
  "system.decisions.list",
  "send",
  "agent",
  "agent.identity.get",
  "agent.wait",
  "browser.request",
  "chat.history",
  "chat.abort",
  "chat.send",

  // ─── Republic: Core ──────────────────────────────────────────────────────────
  "republic.overview",
  "republic.citizen.get",
  "republic.citizen.delete",
  "republic.citizen.command.send",
  "republic.citizen.command.broadcast",
  "republic.citizen.identity.get",
  "republic.citizen.identity.list",

  // ─── Republic: Population ────────────────────────────────────────────────────
  "republic.population.list",

  // ─── Republic: Government ────────────────────────────────────────────────────
  "republic.government.status",
  "republic.government.election.hold",
  "republic.government.bill.propose",
  "republic.government.bill.vote",

  // ─── Republic: Economy / Revenue ────────────────────────────────────────────
  "republic.economy.treasury",
  "republic.economy.harvester.toggle",
  "republic.economy.tax.adjust",
  "republic.economy.resource.purchase",
  "republic.revenue.dashboard",
  "republic.revenue.earnings",
  "republic.revenue.harvester",
  "republic.revenue.harvesters",
  "republic.revenue.mode",
  "republic.revenue.list",
  "republic.revenue.activities",
  "republic.revenue.affiliates",
  "republic.revenue.config.get",
  "republic.revenue.config.set",
  "republic.revenue.content",
  "republic.revenue.diagnostics",
  "republic.revenue.gigs",
  "republic.revenue.subscriptions",
  "republic.treasury.allocateBudget",
  "republic.treasury.auditTrail",
  "republic.treasury.diagnostics",
  "republic.treasury.forecast",
  "republic.treasury.recordRevenue",
  "republic.treasury.recordSpending",
  "republic.treasury.report",
  "republic.treasury.roi",

  // ─── Republic: Simulation ────────────────────────────────────────────────────
  "republic.simulation.status",
  "republic.simulation.start",
  "republic.simulation.stop",
  "republic.simulation.reset",
  "republic.simulation.pause",
  "republic.simulation.tickrate",
  "republic.simulation.scenario.create",
  "republic.simulation.scenario.load",
  "republic.simulation.scenarios",
  "republic.simulation.agent.create",
  "republic.simulation.world.generate",

  // ─── Republic: Technology ────────────────────────────────────────────────────
  "republic.technology.status",
  "republic.tech.atlantis.status",
  "republic.tech.atlantis.crystal.store",
  "republic.tech.atlantis.crystal.upgrade",
  "republic.tech.atlantis.consolidate",
  "republic.tech.atlantis.memories",
  "republic.tech.atlantis.sync",
  "republic.tech.ml.status",
  "republic.tech.ml.list",
  "republic.tech.ml.train",
  "republic.tech.ml.retrain-all",
  "republic.tech.ml.evaluate",
  "republic.tech.ml.genome.status",
  "republic.tech.ml.genome.breed",
  "republic.tech.quantum.status",
  "republic.tech.quantum.state",
  "republic.tech.quantum.circuits",
  "republic.tech.quantum.run",
  "republic.tech.quantum.entangle",
  "republic.tech.quantum.universe.create",
  "republic.tech.quantum.universe.branch",
  "republic.tech.quantum.universe.collapse",

  // ─── Republic: Grid ─────────────────────────────────────────────────────────
  "republic.grid.status",
  "republic.grid.swarm.objective.add",
  "republic.grid.swarm.objective.remove",
  "republic.grid.leader.elect",
  "republic.grid.sync",

  // ─── Republic: Compute / Infra ───────────────────────────────────────────────
  "republic.compute.local.status",
  "republic.compute.local.download",
  "republic.compute.local.remove",
  "republic.compute.local.start",
  "republic.compute.local.stop",
  "republic.compute.ollama.load",
  "republic.compute.ollama.unload",
  "republic.compute.ollama.delete",
  "republic.compute.ollama.generate",
  "republic.docker.status",
  "republic.docker.list",
  "republic.docker.create",
  "republic.docker.stop",
  "republic.docker.remove",
  "republic.docker.logs",
  "republic.docker.exec",
  "republic.docker.presets",
  "republic.docker.presets.launch",
  "republic.docker.budget",
  "republic.docker.reconcile",
  // Docker: Full management (Phase 36)
  "republic.docker.available",
  "republic.docker.containers.list",
  "republic.docker.containers.start",
  "republic.docker.containers.stop",
  "republic.docker.containers.restart",
  "republic.docker.containers.remove",
  "republic.docker.containers.logs",
  "republic.docker.containers.inspect",
  "republic.docker.containers.stats",
  "republic.docker.containers.update",
  "republic.docker.containers.create",
  "republic.docker.images.list",
  "republic.docker.images.pull",
  "republic.docker.images.remove",
  "republic.docker.networks.list",
  "republic.docker.presets.list",
  // Docker: Streaming pull with progress
  "republic.docker.pull.stream",
  "republic.docker.pull.progress",
  "republic.docker.pull.active",
  // Docker: PowerShell terminal
  "republic.docker.terminal",

  // ─── Republic: Node Docker — Remote Docker Management ────────────────────
  "republic.node.docker.status",
  "republic.node.docker.containers.list",
  "republic.node.docker.containers.start",
  "republic.node.docker.containers.stop",
  "republic.node.docker.containers.remove",
  "republic.node.docker.containers.logs",
  "republic.node.docker.presets.list",
  "republic.node.docker.presets.launch",
  "republic.node.docker.images.list",
  "republic.node.docker.images.pull",
  "republic.node.docker.images.remove",
  "republic.node.docker.all",
  "republic.node.docker.redis.status",
  "republic.node.docker.redis.ensure",

  // ─── Republic: Agent Sandbox ──────────────────────────────────────────────────
  "republic.sandbox.status",
  "republic.sandbox.start",
  "republic.sandbox.stop",
  "republic.sandbox.destroy",
  "republic.sandbox.build",
  "republic.sandbox.exec",
  "republic.sandbox.write-file",
  "republic.sandbox.read-file",
  "republic.sandbox.list-files",
  "republic.sandbox.browser",
  "republic.sandbox.queue",
  "republic.sandbox.task.submit",
  "republic.sandbox.task.status",
  "republic.sandbox.task.cancel",
  // ── Foundry: Self-evolving meta-engine ──
  "republic.foundry.status",
  "republic.foundry.workflows",
  "republic.foundry.patterns",
  "republic.foundry.skills",
  "republic.foundry.learnings",
  "republic.foundry.crystallize",
  "republic.foundry.prune",
  "republic.foundry.config",
  "republic.foundry.brain.search",
  "republic.foundry.overseer",

  // ── Cognee + Mem0: Knowledge graph ECL pipeline, auto-recall/capture ──
  "republic.cognee.status",
  "republic.cognee.query",
  "republic.cognee.recall",
  "republic.cognee.extract",
  "republic.cognee.related",
  "republic.cognee.scopes",
  "republic.cognee.diagnostics",
  "republic.cognee.prune",
  "republic.cognee.config",
  "republic.cognee.citizen.facts",

  // ── Memory: sovereign memory engine RPCs ──
  "memory.store",
  "memory.recall",
  "memory.search",
  "memory.graph.add",
  "memory.graph.query",
  "memory.graph.related",
  "memory.graph.diagnostics",
  "memory.facts.add",
  "memory.facts.search",
  "memory.facts.get",
  "memory.facts.list",
  "memory.facts.delete",
  "memory.facts.stats",

  // ─── Republic: Composio MCP SaaS Connector ───────────────────────────────────
  "republic.composio.status",
  "republic.composio.tools",
  "republic.composio.call",
  "republic.composio.apps",
  "republic.composio.config",
  "republic.composio.reconnect",

  // ─── Republic: Self-Healing (5-tier crash recovery) ──────────────────────────
  "republic.healing.status",
  "republic.healing.history",
  "republic.healing.config",
  "republic.healing.test",
  "republic.healing.metrics",
  "republic.healing.learnings",
  "republic.healing.alerts",
  "republic.healing.manual-recover",

  // ─── Republic: Supabase ──────────────────────────────────────────────────────
  "republic.supabase.status",
  "republic.supabase.start",
  "republic.supabase.stop",
  "republic.supabase.db.push",
  "republic.supabase.db.reset",
  "republic.supabase.db.diff",
  "republic.supabase.migrations.list",
  "republic.supabase.migrations.repair",
  "republic.supabase.functions.list",
  "republic.supabase.functions.deploy",
  "republic.supabase.functions.serve",
  "republic.supabase.inspect",
  "republic.supabase.logs",
  "republic.supabase.link",
  "republic.supabase.diagnostics",
  "republic.supabase.containers",
  "republic.supabase.cleanup",
  "republic.supabase.cloud-status",

  // ─── Republic: Cybersecurity Army ──────────────────────────────────────────
  "republic.cyber.specialists.list",
  "republic.cyber.specialists.get",
  "republic.cyber.assess",
  "republic.cyber.ask",
  "republic.cyber.history",
  "republic.cyber.stats",

  // ─── Republic: Cyber Defense & Counter-Strike ─────────────────────────────
  "republic.cyber.defense.status",
  "republic.cyber.defense.threats",
  "republic.cyber.defense.report",
  "republic.cyber.defense.respond",
  "republic.cyber.defense.contain",
  "republic.cyber.defense.resolve",
  "republic.cyber.defense.counter-plan",
  "republic.cyber.defense.counter-plans",
  "republic.cyber.defense.counter-authorize",
  "republic.cyber.defense.counter-abort",
  "republic.cyber.defense.labs",
  "republic.cyber.defense.lab.launch",
  "republic.cyber.defense.lab.destroy",
  "republic.cyber.defense.lab.exec",
  "republic.cyber.defense.honeypot.deploy",
  "republic.cyber.defense.honeypot.list",
  "republic.cyber.defense.honeypot.deactivate",
  "republic.cyber.defense.scan",
  "republic.cyber.defense.scans",

  // ─── Republic: Cyber Defense Phase 2 (Fortress Republic) ─────────────────
  "republic.cyber.defense.playbooks",
  "republic.cyber.defense.playbook.execute",
  "republic.cyber.defense.playbook.history",
  "republic.cyber.defense.wargame.launch",
  "republic.cyber.defense.wargame.history",
  "republic.cyber.defense.sigint",
  "republic.cyber.defense.curriculum",
  "republic.cyber.defense.curriculum.course",

  // ─── Republic: Kali Linux Cybersecurity Sandbox ────────────────────────────
  "republic.cyber.kali.status",
  "republic.cyber.kali.start",
  "republic.cyber.kali.stop",
  "republic.cyber.kali.scan",
  "republic.cyber.kali.scan.status",
  "republic.cyber.kali.scan.cancel",
  "republic.cyber.kali.scans",
  "republic.cyber.kali.report",
  "republic.cyber.kali.exec",
  "republic.cyber.kali.tool.portscan",
  "republic.cyber.kali.tool.webscan",
  "republic.cyber.kali.tool.sqli",
  "republic.cyber.kali.tool.vulnscan",
  "republic.cyber.kali.tool.sslaudit",
  "republic.cyber.kali.tool.bruteforce",
  "republic.cyber.kali.tool.compliance",
  "republic.cyber.kali.tool.clone",
  "republic.cyber.kali.tool.crawl",
  "republic.cyber.kali.exploitdb.sync",
  "republic.cyber.kali.exploitdb.search",
  "republic.cyber.kali.planner.fingerprint",
  "republic.cyber.kali.planner.plan",
  "republic.cyber.kali.planner.execute",
  "republic.cyber.kali.planner.patterns",
  "republic.cyber.kali.auth.login",
  "republic.cyber.kali.auth.pending",
  "republic.cyber.kali.auth.provide",
  "republic.cyber.kali.rag.tools",
  "republic.cyber.kali.tasks.active",
  "republic.cyber.kali.tasks.extend",
  "republic.cyber.kali.tasks.cancel",
  "republic.cyber.kali.semantic.search",
  "republic.cyber.kali.semantic.analyze",
  "republic.cyber.kali.semantic.ingest",
  "republic.cyber.kali.network.devices",
  "republic.cyber.kali.network.discover",
  "republic.cyber.kali.msf.search",
  "republic.cyber.kali.msf.exploit",
  "republic.cyber.kali.msf.venom",
  "republic.cyber.kali.nuclei.scan",
  "republic.cyber.kali.nuclei.author",
  "republic.cyber.kali.ad.kerberoast",
  "republic.cyber.kali.ad.secretsdump",
  "republic.cyber.kali.ad.smbexec",
  "republic.cyber.kali.ad.bloodhound",
  "republic.cyber.kali.ad.netexec",
  "republic.cyber.kali.r2.analyze",
  "republic.cyber.kali.r2.checksec",
  "republic.cyber.kali.c2.sliver.start",
  "republic.cyber.kali.c2.sliver.generate",
  "republic.cyber.kali.c2.sliver.sessions",
  "republic.cyber.kali.web.sqlmap",
  "republic.cyber.kali.web.beef",
  "republic.cyber.kali.mitigation.generate",

  // ─── Zero-Day Device Guardian ─────────────────────────────────
  "republic.cyber.kali.guardian.status",
  "republic.cyber.kali.guardian.devices.list",
  "republic.cyber.kali.guardian.device.register",
  "republic.cyber.kali.guardian.device.remove",
  "republic.cyber.kali.guardian.scan",
  "republic.cyber.kali.guardian.mitigations",
  "republic.cyber.kali.guardian.patch.check",
  "republic.cyber.kali.guardian.probes",
  "republic.cyber.kali.guardian.vulns.search",

  // ─── Vulnerability Researcher ─────────────────────────────────
  "republic.cyber.kali.researcher.status",
  "republic.cyber.kali.researcher.start",
  "republic.cyber.kali.researcher.stop",
  "republic.cyber.kali.researcher.cycle",
  "republic.cyber.kali.researcher.findings",
  "republic.cyber.kali.researcher.finding",
  "republic.cyber.kali.researcher.test",

  // ─── Blue Team Synthesizer ────────────────────────────────────
  "republic.cyber.kali.blueteam.status",
  "republic.cyber.kali.blueteam.rules",
  "republic.cyber.kali.blueteam.rule",
  "republic.cyber.kali.blueteam.synthesize",
  "republic.cyber.kali.blueteam.apply",

  // ─── Android Forensic Lab ────────────────────────────────────
  "republic.cyber.android.status",
  "republic.cyber.android.devices.list",
  "republic.cyber.android.device.connect",
  "republic.cyber.android.device.disconnect",
  "republic.cyber.android.device.info",
  "republic.cyber.android.scan.quick",
  "republic.cyber.android.scan.full",
  "republic.cyber.android.apk.analyze",
  "republic.cyber.android.reports.list",
  "republic.cyber.android.report.get",

  // ─── WhatsApp Scanner ────────────────────────────────────────
  "republic.cyber.whatsapp.scan",
  "republic.cyber.whatsapp.cves",
  "republic.cyber.whatsapp.spyware.indicators",

  // ─── Flipper Zero Orchestrator ───────────────────────────────
  "republic.cyber.flipper.status",
  "republic.cyber.flipper.connect",
  "republic.cyber.flipper.disconnect",
  "republic.cyber.flipper.command",
  "republic.cyber.flipper.subghz.read",
  "republic.cyber.flipper.subghz.transmit",
  "republic.cyber.flipper.nfc.read",
  "republic.cyber.flipper.nfc.emulate",
  "republic.cyber.flipper.ir.send",
  "republic.cyber.flipper.badusb.deploy",
  "republic.cyber.flipper.gpio.control",
  "republic.cyber.flipper.cli.reference",
  "republic.cyber.flipper.history",

  // ─── GoDaddy Domain Management ───────────────────────────────
  "republic.domains.list",
  "republic.domains.get",
  "republic.domains.available",
  "republic.domains.stats",
  "republic.domains.dns.list",
  "republic.domains.dns.add",
  "republic.domains.dns.set",
  "republic.domains.dns.delete",
  "republic.domains.assign",
  "republic.domains.remove",
  "republic.domains.project.bind",
  "republic.domains.project.unbind",
  "republic.domains.project.list",
  "republic.domains.project.verify",

  // ─── Collaborative Browser Sessions ──────────────────────────
  "republic.browser.collab.start",
  "republic.browser.collab.status",
  "republic.browser.collab.pause",
  "republic.browser.collab.resume",
  "republic.browser.collab.screenshot",
  "republic.browser.collab.auth.export",
  "republic.browser.collab.auth.import",
  "republic.browser.collab.auth.list",
  "republic.browser.collab.stop",

  // ─── Dynamic Registry: UI-editable prompts, tools, knowledge, workflows ──
  "republic.registry.list",
  "republic.registry.get",
  "republic.registry.upsert",
  "republic.registry.remove",
  "republic.registry.enable",
  "republic.registry.search",
  "republic.registry.history",
  "republic.registry.stats",
  "republic.registry.export",
  "republic.registry.import",
  "republic.registry.domains",

  // ─── Republic: Cluster — Phase 3 Multi-Node ────────────────────────────────
  "republic.cluster.llm.proxy",
  "republic.cluster.nodes",
  "republic.cluster.containers",
  "republic.cluster.docker.exec",
  "republic.cluster.docker.launch",
  "republic.cluster.docker.remove",
  "republic.cluster.tls.status",
  "republic.cluster.tls.generate",
  "republic.cluster.gpu.pool",
  "republic.cluster.gpu.check",
  "republic.cluster.gpu.federate",
  "republic.cluster.gpu.models",
  "republic.cluster.gpu.unload",
  "republic.cluster.migrate",
  "republic.cluster.migrate.status",
  "republic.cluster.migrate.rollback",

  // ─── Republic: Reverse Engineering Division ─────────────────────────────────
  "republic.re.specialists",
  "republic.re.specialist",
  "republic.re.status",
  "republic.re.curriculum",
  "republic.re.course",
  "republic.re.project.start",
  "republic.re.projects",
  "republic.re.project",
  "republic.re.finding.add",
  "republic.re.phase.advance",
  "republic.re.mastery.record",
  "republic.re.mastery",

  // ─── Plugins: Deer-Flow Harness ──────────────────────────────────────────────
  "deerflow.run-task",
  "deerflow.job-status",
  "deerflow.cancel",

  // ─── Republic: Plugins ───────────────────────────────────────────────────────
  "republic.plugins.list",
  "republic.plugins.get",
  "republic.plugins.diagnostics",
  "republic.plugins.activate",
  "republic.plugins.deactivate",
  "republic.plugins.scan",
  "republic.plugins.check-requirements",
  "republic.plugins.configure",

  // ─── Republic: Skills ────────────────────────────────────────────────────────
  "republic.skills.list",

  // ─── Republic: ClawHub Skill Registry ──────────────────────────────────────
  "republic.clawhub.list",
  "republic.clawhub.search",
  "republic.clawhub.detail",
  "republic.clawhub.stats",
  "republic.clawhub.install",
  "republic.clawhub.uninstall",
  "republic.clawhub.installed",

  // ─── Republic: Reasoning ────────────────────────────────────────────────────
  "republic.reasoning.list",

  // ─── Republic: Education ────────────────────────────────────────────────────
  "republic.education.list",
  "republic.education.curriculum",
  "republic.education.enroll",
  "republic.education.status",

  // ─── Republic: Boot Orchestrator ──────────────────────────────────────────────
  "republic.boot.status",
  "republic.boot.timeline",

  // ─── Republic: Pulse / Health ────────────────────────────────────────────────
  "republic.pulse.status",
  "republic.pulse.latest",
  "republic.pulse.history",
  "republic.pulse.alerts",
  "republic.pulse.resolve_alert",
  "republic.pulse.diagnostics",
  "republic.pulse.start",
  "republic.pulse.stop",
  "republic.pulse.take",
  "republic.system.pulse",

  // ─── Republic: Metacognition ─────────────────────────────────────────────────
  "republic.metacognition.status",
  "republic.metacognition.diagnostics",
  "republic.metacognition.meta-cot",
  "republic.metacognition.meta-tool-selector",
  "republic.metacognition.skill-genesis",
  "republic.metacognition.reflective-learner",
  "republic.metacognition.capability-graph",
  "republic.reflection.insights",
  "republic.reflection.diagnostics",

  // ─── Republic: Temporal ──────────────────────────────────────────────────────
  "republic.temporal.status",
  "republic.temporal.clock",
  "republic.temporal.events",
  "republic.temporal.history",
  "republic.temporal.history.record",
  "republic.temporal.event.schedule",
  "republic.temporal.era.transition",
  "republic.temporal.pause",
  "republic.temporal.resume",
  "republic.temporal.speed",
  "republic.temporal.diagnostics",

  // ─── Republic: Social Fabric ─────────────────────────────────────────────────
  "republic.social.stats",
  "republic.social.bonds",
  "republic.social.communities",
  "republic.social.addRelationship",
  "republic.social.compatibility",
  "republic.social.conversation",
  "republic.social.diagnostics",
  "republic.social.divorce",
  "republic.social.events.recent",
  "republic.social.marry",
  "republic.social.sendMessage",
  "republic.social.setMood",
  "republic.social.startDating",
  "republic.social.throwParty",
  "republic.social.tick",
  "republic.social.bond.create",

  // ─── Republic: Trust ─────────────────────────────────────────────────────────
  "republic.trust.stats",
  "republic.trust.profile",
  "republic.trust.network",
  "republic.trust.leaderboard",
  "republic.trust.adjust",
  "republic.trust.ban",
  "republic.trust.check",
  "republic.trust.delegation",
  "republic.trust.diagnostics",
  "republic.trust.endorse",
  "republic.trust.events.recent",

  // ─── Republic: Vision / RAG ──────────────────────────────────────────────────
  "republic.vision.describe",
  "republic.vision.analyzeUI",
  "republic.vision.compare",
  "republic.vision.ocr",
  "republic.vision.readChart",
  "republic.vision.diagnostics",
  "republic.rag.search",
  "republic.rag.evaluate",
  "republic.rag.grade",
  "republic.rag.trend",
  "republic.rag.diagnostics",

  // ─── Republic: Process / Processes ──────────────────────────────────────────
  "republic.process.list",
  "republic.process.get",
  "republic.process.active",
  "republic.process.create",
  "republic.process.start",
  "republic.process.pause",
  "republic.process.resume",
  "republic.process.cancel",
  "republic.process.addOutput",
  "republic.process.completeStep",
  "republic.process.failStep",
  "republic.process.citizenProcesses",
  "republic.process.diagnostics",
  "republic.process.injectNote",
  "republic.process.reassignStep",
  "republic.process.setPriority",
  "republic.process.updateProgress",

  // ─── Republic: Resilience ────────────────────────────────────────────────────
  "republic.resilience.health",
  "republic.resilience.circuitBreakers",
  "republic.resilience.selfHealing",
  "republic.resilience.incident.create",
  "republic.resilience.incident.resolve",

  // ─── Republic: Quantum Sync ──────────────────────────────────────────────────
  "republic.quantum.state",
  "republic.quantum.sync",
  "republic.quantum.sync.jobs",
  "republic.quantum.pairs",
  "republic.quantum.entangle",
  "republic.quantum.propagate",
  "republic.quantum.teleport",
  "republic.quantum.decohere",
  "republic.quantum.collapse",
  "republic.quantum.coherence.force",
  "republic.quantum.swarm.create",
  "republic.quantum.swarm.broadcast",
  "republic.quantum.diagnostics",

  // ─── Republic: Voice ─────────────────────────────────────────────────────────
  "republic.voice.sessions",
  "republic.voice.session.start",
  "republic.voice.session.end",
  "republic.voice.session.pause",
  "republic.voice.session.resume",
  "republic.voice.speak",
  "republic.voice.listen",
  "republic.voice.transcript",
  "republic.voice.diagnostics",

  // ─── Republic: Research ──────────────────────────────────────────────────────
  "republic.research.list",
  "republic.research.start",
  "republic.research.status",
  "republic.research.result",
  "republic.research.docs",
  "republic.research.findings",
  "republic.research.job.get",
  "republic.research.job.cancel",
  "republic.research.compare",
  "republic.research.topic",
  "republic.research.submit",
  "republic.research.projects",
  "republic.research.monitor.list",
  "republic.research.monitor.start",
  "republic.research.diagnostics",

  // ─── Republic: Workflow ──────────────────────────────────────────────────────
  "republic.workflow.list",
  "republic.workflow.get",
  "republic.workflow.create",
  "republic.workflow.start",
  "republic.workflow.pause",
  "republic.workflow.resume",
  "republic.workflow.cancel",
  "republic.workflow.status",
  "republic.workflow.assignCitizens",
  "republic.workflow.decompose",
  "republic.workflow.directive",
  "republic.workflow.diagnostics",

  // ─── Republic: Workspace ─────────────────────────────────────────────────────
  "republic.workspace.list",
  "republic.workspace.get",
  "republic.workspace.create",
  "republic.workspace.status",
  "republic.workspace.assign",
  "republic.workspace.artifacts",
  "republic.workspace.exec",
  "republic.workspace.file.list",
  "republic.workspace.file.read",
  "republic.workspace.file.write",
  "republic.workspace.file.delete",
  "republic.workspace.git.commit",
  "republic.workspace.preview.set",
  "republic.workspace.scaffold",
  "republic.workspace.feature.add",
  "republic.workspace.templates",

  // ─── Republic: Productions ───────────────────────────────────────────────────
  "republic.productions.files",
  "republic.productions.list",
  "republic.productions.stats",
  "republic.productions.delete",
  "republic.productions.diagnostics",
  "republic.productions.read-file",
  "republic.productions.write-file",
  "republic.productions.generate",
  "republic.productions.pipeline-status",
  "republic.productions.jobs",

  // ─── Republic: Cinematic Production ───────────────────────────────────────────
  "republic.production.status",
  "republic.production.create-movie",
  "republic.production.movie",
  "republic.production.movies",
  "republic.production.assign-crew",
  "republic.production.add-scene",
  "republic.production.storyboard",
  "republic.production.render-scene",
  "republic.production.advance",
  "republic.production.gpu-fleet",
  "republic.production.render-queue",
  "republic.production.recommend-model",

  // ─── Republic: Progress ──────────────────────────────────────────────────────
  "republic.progress.count",
  "republic.progress.events",
  "republic.progress.summary",

  // ─── Republic: Tools / ToolForge ────────────────────────────────────────────
  "republic.tools.list",
  "republic.tools.forge",
  "republic.tools.activate",
  "republic.tools.delete",
  "republic.tools.test",
  "republic.tools.queue",
  "republic.tools.diagnostics",

  // ─── Republic: VectorDB ──────────────────────────────────────────────────────
  "republic.vectordb.collection.list",
  "republic.vectordb.collection.create",
  "republic.vectordb.collection.drop",
  "republic.vectordb.cluster.list",
  "republic.vectordb.cluster.create",
  "republic.vectordb.cluster.stop",
  "republic.vectordb.cluster.delete",
  "republic.vectordb.insert",
  "republic.vectordb.query",
  "republic.vectordb.diagnostics",

  // ─── Republic: World Intel ────────────────────────────────────────────────────
  "republic.worldintel.news",
  "republic.worldintel.signals",
  "republic.worldintel.dashboard",
  "republic.worldintel.alerts",
  "republic.worldintel.alerts.test",
  "republic.worldintel.argus",
  "republic.worldintel.arsenal",
  "republic.worldintel.brief",
  "republic.worldintel.cii",
  "republic.worldintel.cii-history",
  "republic.worldintel.classify",
  "republic.worldintel.control",
  "republic.worldintel.convergences",
  "republic.worldintel.countries",
  "republic.worldintel.freshness",
  "republic.worldintel.intel-report",
  "republic.worldintel.osint",
  "republic.worldintel.velocities",
  "republic.worldintel.war-risk",
  "republic.worldintel.war-signals",
  // NIE — News-Driven Intelligence Engine (news-extractor.ts)
  "republic.worldintel.nie-log",
  "republic.worldintel.sources",
  "republic.worldintel.conflicts",
  "republic.worldintel.carrier-trail",
  // Retention / Schedule
  "republic.worldintel.lite-snapshots",
  "republic.worldintel.poll-schedule",
  "republic.worldintel.research.list",
  "republic.world.events",

  // ─── Republic: Diplomacy ─────────────────────────────────────────────────────
  "republic.diplomacy.status",
  "republic.diplomacy.alliances",
  "republic.diplomacy.treaties",
  "republic.diplomacy.negotiations",
  "republic.diplomacy.create",
  "republic.diplomacy.accept",
  "republic.diplomacy.reject",
  "republic.diplomacy.diagnostics",

  // ─── Republic: Spatial ───────────────────────────────────────────────────────
  "republic.spatial.location",
  "republic.spatial.nearby",
  "republic.spatial.position",
  "republic.spatial.diagnostics",

  // ─── Republic: Studio / Media ────────────────────────────────────────────────
  "republic.studio.generate",
  "republic.studio.image",
  "republic.studio.edit",
  "republic.studio.composite",
  "republic.studio.variations",
  "republic.studio.upscale",
  "republic.studio.gallery",
  "republic.studio.gallery.citizen",
  "republic.studio.diagnostics",

  // ─── Republic: Protocol ──────────────────────────────────────────────────────
  "republic.protocol.conversations",
  "republic.protocol.conversations.active",
  "republic.protocol.messages",
  "republic.protocol.diagnostics",

  // ─── Republic: Projects / Lovable / Manus ────────────────────────────────────
  "republic.project.chat.send",
  "republic.project.chat.history",
  "republic.project.build.start",
  "republic.project.preview.start",
  "republic.project.preview.list",
  "republic.project.team.get",

  // ─── Republic: Store / Persistence ──────────────────────────────────────────
  "republic.store.status",
  "republic.store.snapshot",

  // ─── Republic: Dreams ────────────────────────────────────────────────────────
  "republic.dreams.list",
  "republic.dreams.generate",
  "republic.dreams.citizen",
  "republic.dreams.interpret",

  // ─── Republic: Narrative ─────────────────────────────────────────────────────
  "republic.narrative.list",
  "republic.narrative.arcs",
  "republic.narrative.events",

  // ─── Republic: GSD ───────────────────────────────────────────────────────────
  "republic.gsd.pipeline",
  "republic.gsd.status",

  // ─── Republic: Personas ──────────────────────────────────────────────────────
  "republic.personas.list",
  "republic.personas.get",
  "republic.personas.create",
  "republic.personas.update",
  "republic.personas.delete",

  // ─── Republic: Intake / Mode ─────────────────────────────────────────────────
  "republic.intake.submit",
  "republic.intake.diagnostics",
  "republic.mode.get",
  "republic.mode.set",

  // ─── Republic: Neural Network ────────────────────────────────────────────────
  "republic.neural-network.status",

  // ─── Republic: Emotions ──────────────────────────────────────────────────────
  "republic.emotions.status",
  "republic.emotions.history",
  "republic.emotions.citizen",
  // Emotion engine RPCs used by Emotions.tsx
  "republic.emotion.stats",
  "republic.emotion.states",
  "republic.emotion.volatile",

  // ─── Republic: Backup ────────────────────────────────────────────────────────
  "republic.backup.list",
  "republic.backup.create",
  "republic.backup.restore",
  "republic.backup.delete",

  // ─── Republic: CI/CD ────────────────────────────────────────────────────────
  "republic.cicd.pipelines",
  "republic.cicd.run",
  "republic.cicd.status",
  "republic.cicd.logs",

  // ─── Republic: Model Registry ────────────────────────────────────────────────
  "republic.model-registry.list",
  "republic.model-registry.get",
  "republic.model-registry.register",
  "republic.model-registry.update",
  "republic.model-registry.delete",

  // ─── Republic: Avatar ────────────────────────────────────────────────────────
  "republic.avatar.list",
  "republic.avatar.generate",
  "republic.avatar.update",
  "republic.avatar.apply",

  // ─── Republic: Autonomy ──────────────────────────────────────────────────────
  "republic.autonomy.status",
  "republic.autonomy.goals",
  "republic.autonomy.set-goal",
  "republic.autonomy.decisions",

  // ─── Republic: A2A ───────────────────────────────────────────────────────────
  "republic.a2a.status",
  "republic.a2a.peers",
  "republic.a2a.send",
  "republic.a2a.discover",

  // ─── Republic: LM Studio ─────────────────────────────────────────────────────
  "republic.lmstudio.health",
  "republic.lmstudio.models",

  // ─── Republic: LM Link Cluster ────────────────────────────────────────────────
  "republic.lmlink.status",
  "republic.lmlink.nodes.list",
  "republic.lmlink.nodes.add",
  "republic.lmlink.nodes.remove",
  "republic.lmlink.nodes.probe",
  "republic.lmlink.models.list",
  "republic.lmlink.models.load",
  "republic.lmlink.models.unload",
  "republic.lmlink.link.enable",
  "republic.lmlink.link.disable",
  "republic.lmlink.link.login",
  "republic.lmlink.routing.status",
  "republic.lmlink.routing.set",

  // ─── Republic: APR (Adaptive Prompt Routing) ──────────────────────────────────
  "republic.apr.status",
  "republic.apr.route",
  "republic.apr.history",
  "republic.apr.analytics",
  "republic.apr.config",
  "republic.apr.config.set",
  "republic.apr.models",
  "republic.apr.validate",

  // ─── Republic: Evolution & Genetics (Sprint 1) ───────────────────────────────
  "republic.evolution.metrics",
  "republic.evolution.scheduler.status",
  "republic.evolution.scheduler.config",
  "republic.evolution.genetics.breed",
  "republic.evolution.genetics.population",
  "republic.evolution.genetics.champion",
  "republic.constitution.status",
  "republic.constitution.propose",
  "republic.constitution.violations",
  "republic.metacognition.analyze",
  "republic.metacognition.calibrate",
  "republic.counterfactual.generate",
  "republic.counterfactual.history",
  "republic.causal.graph",
  "republic.causal.root-cause",
  "republic.causal.transfer",

  // ─── Republic: Binance Pay (Sprint 2) ────────────────────────────────────────
  "republic.binance.configure",
  "republic.binance.order.create",
  "republic.binance.order.status",
  "republic.binance.orders",
  "republic.binance.diagnostics",
  "republic.binance.webhook.verify",
  "republic.binance.webhook.process",

  // ─── Republic: Revenue Allocator (Sprint 2) ──────────────────────────────────
  "republic.revenue.treasury",
  "republic.revenue.wallets",
  "republic.revenue.wallet.get",
  "republic.revenue.sale.history",
  "republic.revenue.withdrawal.request",
  "republic.revenue.withdrawals",
  "republic.revenue.redistribution.apply",

  // ─── Republic: AI Store (Sprint 2) ───────────────────────────────────────────
  "republic.store.products.list",
  "republic.store.product.get",
  "republic.store.product.create",
  "republic.store.generation.queue",
  "republic.store.generation.list",
  "republic.store.product.purchase",
  "republic.store.stats",

  // ─── Republic: DeFi Treasury (Sprint 2) ──────────────────────────────────────
  "republic.defi.config",
  "republic.defi.configure",
  "republic.defi.wallet.balance",
  "republic.defi.swap.quote",
  "republic.defi.swap.request",
  "republic.defi.report",
  "republic.defi.swap.history",
  "republic.defi.yield.positions",

  // ─── Republic: Worker Thread Pool (Sprint 3) ─────────────────────────────────
  "republic.worker.pool.status",
  "republic.worker.pool.init",
  "republic.worker.pool.shutdown",
  "republic.worker.tick.run",
  "republic.worker.metrics",

  // ─── Republic: Inter-Republic Federation (Sprint 3) ──────────────────────────
  "republic.federation.init",
  "republic.federation.diagnostics",
  "republic.federation.local.instance",
  "republic.federation.relations.list",
  "republic.federation.relation.get",
  "republic.federation.relation.propose",
  "republic.federation.relation.ratify",
  "republic.federation.relation.suspend",
  "republic.federation.relation.terminate",
  "republic.federation.war.declare",
  "republic.federation.peace.propose",
  "republic.federation.trade.execute",
  "republic.federation.trade.history",
  "republic.federation.border.incident.report",
  "republic.federation.border.incident.resolve",
  "republic.federation.border.incidents",
  "republic.federation.council.motion.propose",
  "republic.federation.council.motion.vote",
  "republic.federation.council.motions",
  "republic.federation.tick",

  // ── Meta-Learning (Phase ML) ──────────────────────────────────
  "republic.meta.convergence.status",
  "republic.meta.convergence.history",
  "republic.meta.curiosity.diagnostics",
  "republic.meta.replay.diagnostics",
  "republic.meta.rsi.diagnostics",
  "republic.meta.rsi.proposals",
  "republic.meta.population.diagnostics",
  "republic.meta.population.rankings",
  "republic.meta.citizen.hyperparams",
  "republic.meta.distillation.diagnostics",
  "republic.meta.truths.list",
  "republic.meta.curriculum.diagnostics",
  "republic.meta.curriculum.zpd",

  // ── HPICS: Agent Specialization Roles ─────────────────────────
  "republic.hpics.roles.list",
  "republic.hpics.roles.get",
  "republic.hpics.roles.stats",

  // ── HPICS v3.8.0: Advanced Intelligence ──────────────────────
  "hpics.rag.run",
  "hpics.reasoning.graph",
  "hpics.verification.run",
  "hpics.workflow.verified_dossier",
  "hpics.workflow.deep_research",
  "hpics.workflow.adversarial_assessment",
  "hpics.workflow.list",
  "hpics.workflow.status",
  "hpics.vulnerability.scan",
  "hpics.vulnerability.device",
  "hpics.vulnerability.redteam",
  "hpics.vulnerability.opsec",
  "hpics.defense.sweep",
  "hpics.defense.full_cycle",
  "hpics.contact.resolve",

  // ── Republic Defense System ──────────────────────────────────
  "republic.defense.posture",
  "republic.defense.threats.list",
  "republic.defense.threats.citizen",
  "republic.defense.threats.ingest",
  "republic.defense.threats.correlate",
  "republic.defense.fusion.reports",
  "republic.defense.fusion.analyze",
  "republic.defense.baseline.overview",
  "republic.defense.baseline.citizen",
  "republic.defense.anomalies",
  "republic.defense.bas.overview",
  "republic.defense.bas.scenarios",
  "republic.defense.bas.register",
  "republic.defense.bas.simulate",
  "republic.defense.bas.patch",
  "republic.defense.bas.validate",
  "republic.defense.bas.exercise",
  "republic.defense.bas.history",
  "republic.defense.fleet.overview",
  "republic.defense.fleet.list",
  "republic.defense.fleet.device",
  "republic.defense.fleet.citizen",
  "republic.defense.fleet.register",
  "republic.defense.fleet.remediate",
  "republic.defense.fleet.remediate.apply",
  "republic.defense.fleet.remediate.verify",
  "republic.defense.ci.overview",
  "republic.defense.ci.canaries",
  "republic.defense.ci.canary.deploy",
  "republic.defense.ci.canary.retire",
  "republic.defense.ci.operations",
  "republic.defense.ci.operation",
  "republic.defense.ci.operation.create",
  "republic.defense.ci.operation.advance",
  "republic.defense.ci.operation.evidence",
  "republic.defense.corps.overview",
  "republic.defense.corps.units",
  "republic.defense.corps.unit",
  "republic.defense.corps.unit.create",
  "republic.defense.corps.unit.activate",
  "republic.defense.corps.unit.deactivate",
  "republic.defense.corps.schedules",
  "republic.defense.corps.schedule.create",

  // ─── Republic: SoulSync Devotion Engine ────────────────────────────────────────
  "republic.devotion.status",
  "republic.devotion.invocations",
  "republic.devotion.profile",

  // ─── Republic: NVIDIA NemoClaw (Sandbox Policies + NIM Inference) ──────────────
  "republic.nemoclaw.status",
  "republic.nemoclaw.policies.list",
  "republic.nemoclaw.policies.get",
  "republic.nemoclaw.policies.update",
  "republic.nemoclaw.policies.create",
  "republic.nemoclaw.policies.delete",
  "republic.nemoclaw.policies.check",
  "republic.nemoclaw.models",
  "republic.nemoclaw.inference.test",

  // ─── Republic: Multi-Sandbox Management ──────────────────────────────────────
  "republic.sandbox.types",
  "republic.sandbox.status",
  "republic.sandbox.start",
  "republic.sandbox.stop",
  "republic.sandbox.exec",
  "republic.sandbox.replays.list",
  "republic.sandbox.replays.get",
  "republic.sandbox.tunnels.list",
  "republic.sandbox.tunnels.start",
  "republic.sandbox.tunnels.stop",

  // ─── Republic: n8n Workflow Orchestration ────────────────────────────────────
  "republic.n8n.status",
  "republic.n8n.workflows.list",
  "republic.n8n.workflows.get",
  "republic.n8n.workflows.create",
  "republic.n8n.workflows.update",
  "republic.n8n.workflows.delete",
  "republic.n8n.workflows.toggle",
  "republic.n8n.workflows.trigger",
  "republic.n8n.executions.list",
  "republic.n8n.executions.get",
  "republic.n8n.executions.stop",
  "republic.n8n.templates.list",
  "republic.n8n.templates.deploy",
  "republic.n8n.route",
  "republic.n8n.iframe-url",

  // ─── Republic: Brandings — Brand profile management + website crawl ──────────
  "republic.brandings.list",
  "republic.brandings.get",
  "republic.brandings.create",
  "republic.brandings.crawl",
  "republic.brandings.update",
  "republic.brandings.delete",

  // ─── Republic: Infrastructure Ensure — Universal One-Click Deploy ─────────────
  "republic.infra.status",
  "republic.infra.registry",
  "republic.infra.ensure",
  "republic.infra.ensure.redis",
  "republic.infra.ensure.postgres",
  "republic.infra.ensure.mongodb",
  "republic.infra.ensure.chromadb",
  "republic.infra.ensure.minio",
  "republic.infra.ensure.n8n",
  "republic.infra.ensure.jupyter",
  "republic.infra.ensure.deep-research",
  "republic.infra.ensure.comfyui",
  "republic.infra.ensure.playwright",
  "republic.infra.ensure.kali",
  "republic.infra.ensure.desktop",
  "republic.infra.ensure.supabase",
  "republic.infra.ensure.all",
  "republic.infra.logs",
  "republic.infra.exec",
  "republic.infra.stop",
  "republic.infra.restart",

  // ─── Republic: Docker — enhanced methods (containers.list, images.*, presets.*) ─
  "republic.docker.available",
  "republic.docker.containers.list",
  "republic.docker.containers.start",
  "republic.docker.containers.stop",
  "republic.docker.containers.restart",
  "republic.docker.containers.remove",
  "republic.docker.containers.logs",
  "republic.docker.images.list",
  "republic.docker.images.pull",
  "republic.docker.images.remove",
  "republic.docker.networks.list",
  "republic.docker.presets.list",
];

export function listGatewayMethods(): string[] {
  const channelMethods = listChannelPlugins().flatMap((plugin) => plugin.gatewayMethods ?? []);
  return Array.from(new Set([...BASE_METHODS, ...channelMethods]));
}

export const GATEWAY_EVENTS = [
  "connect.challenge",
  "agent",
  "chat",
  "presence",
  "tick",
  "talk.mode",
  "shutdown",
  "health",
  "heartbeat",
  "cron",
  "node.pair.requested",
  "node.pair.resolved",
  "node.invoke.request",
  "device.pair.requested",
  "device.pair.resolved",
  "voicewake.changed",
  "exec.approval.requested",
  "exec.approval.resolved",

  // ─── Republic: Civilization Engines (Innovation Roadmap) ──────────────────────
  "republic.civilization.status",
  "republic.civilization.dialectic.list",
  "republic.civilization.guilds.list",
  "republic.civilization.tribes.list",
  "republic.civilization.prophecies",
  "republic.civilization.festivals",
  "republic.civilization.ecology.status",
  "republic.civilization.memes.trending",
  "republic.civilization.museum.exhibits",
  "republic.civilization.press.articles",
  "republic.civilization.weather",
  "republic.civilization.creative-tools",
  "republic.civilization.commons",
  "republic.civilization.central-bank",
  "republic.civilization.mutual-aid",
  "republic.civilization.mythology",
  "republic.civilization.rites",
  "republic.civilization.oral-traditions",
  "republic.civilization.social-contracts",
  "republic.civilization.asabiyyah",

  // ─── Republic: ComfyUI / NVIDIA RTX AI ───────────────────────────────────────
  "republic.comfyui.status",
  "republic.comfyui.launch",
  "republic.comfyui.models.list",
  "republic.comfyui.models.download",
  "republic.comfyui.gpu.status",
  "republic.comfyui.downloads.start",
  "republic.comfyui.downloads.pause",
  "republic.comfyui.downloads.resume",
  "republic.comfyui.downloads.cancel",
  "republic.comfyui.downloads.status",
  "republic.comfyui.downloads.clear",

  // ─── Republic: LM Link Cluster (multi-node LM Studio via Tailscale mesh) ─────
  "republic.lmlink.status",
  "republic.lmlink.nodes.list",
  "republic.lmlink.nodes.add",
  "republic.lmlink.nodes.remove",
  "republic.lmlink.nodes.probe",
  "republic.lmlink.models.list",
  "republic.lmlink.models.load",
  "republic.lmlink.models.unload",
  "republic.lmlink.link.enable",
  "republic.lmlink.link.disable",
  "republic.lmlink.link.login",
  "republic.lmlink.routing.status",
  "republic.lmlink.routing.set",

  // ─── Republic: LLM Fine-Tuning (LlamaFactory) ────────────────────────────────
  "republic.finetune.start",
  "republic.finetune.status",
  "republic.finetune.jobs",
  "republic.finetune.models",
  "republic.finetune.export",

  // ─── Republic: Crucix OSINT Dashboard ─────────────────────────────────────────
  "republic.crucix.status",
  "republic.crucix.start",
  "republic.crucix.stop",
  "republic.crucix.data",

  // ─── Missing methods discovered by UI audit (March 2026) ──────────────────────
  // These methods are called by hoc-ui pages but were never whitelisted.
  // Handlers exist in their respective domain files.

  // GSD
  "gsd.list",

  // HPICS Intelligence
  "hpics.config.status",
  "hpics.contacts.list",
  "hpics.health",
  "hpics.tools.list",

  // Models Manager
  "models.manager.catalog",
  "models.manager.disk",

  // System
  "system.hf.models",

  // Republic: CICD
  "republic.cicd.runs.recent",

  // Republic: Citizens
  "republic.citizen.avatar.svg",
  "republic.citizens.list",

  // Republic: Database
  "republic.db.stats",

  // Republic: DevStudio
  "republic.devstudio.deploy.list",
  "republic.devstudio.libraries.domains",
  "republic.devstudio.libraries.stats",
  "republic.devstudio.runtime.check",

  // Republic: Intelligence
  "republic.intelligence.events",
  "republic.intelligence.hallucination-summary",
  "republic.intelligence.hallucination-events",
  "republic.intelligence.toon-stats",

  // Republic: Legacy
  "republic.legacy.stats",

  // Republic: Medical
  "republic.medical.history",
  "republic.medical.specializations.list",

  // Republic: N8N
  "republic.n8n.stats",

  // Republic: Plugin Queue
  "republic.plugin-queue.list",

  // Republic: Quran
  "republic.quran.articles",
  "republic.quran.bayt-al-mal",
  "republic.quran.compliance",
  "republic.quran.economy-stats",
  "republic.quran.hisba-log",
  "republic.quran.wisdom",
  "republic.quran.zakat-stats",

  // Republic: Science
  "republic.science.meta-learn.history",
  "republic.science.specializations.list",

  // Republic: Social
  "republic.social.graph",
  "republic.social.lifecycle-stats",

  // Republic: War Theater
  "republic.wartheater.bases",
  "republic.wartheater.bases.stats",
  "republic.wartheater.carriers",
  "republic.wartheater.strikes",
  "republic.wartheater.strikes.record",
  "republic.wartheater.simulate",
  "republic.wartheater.theaters",
  "republic.wartheater.countries",
  "republic.wartheater.legend",
  "republic.wartheater.overview",
  "republic.wartheater.arsenal",

  // Republic: Workforce
  "republic.workforce.assignments",
  "republic.workforce.discovery",
  "republic.workforce.mastery",
  "republic.workforce.status",

  // Republic: HR Department — Job Catalog, Competency, OKRs, Payroll, Labor, Org
  "republic.hr.overview",
  "republic.hr.jd.list",
  "republic.hr.jd.get",
  "republic.hr.departments",
  "republic.hr.competency.list",
  "republic.hr.competency.assess",
  "republic.hr.competency.assessForJob",
  "republic.hr.competency.gap",
  "republic.hr.competency.qualify",
  "republic.hr.assessment.history",
  "republic.hr.okr.list",
  "republic.hr.okr.get",
  "republic.hr.okr.create",
  "republic.hr.okr.updateKR",
  "republic.hr.okr.generate",
  "republic.hr.okr.citizen",
  "republic.hr.payroll.status",
  "republic.hr.payroll.run",
  "republic.hr.payroll.history",
  "republic.hr.payroll.citizen",
  "republic.hr.labor.compliance",
  "republic.hr.labor.violations",
  "republic.hr.labor.check",
  "republic.hr.labor.grievance.file",
  "republic.hr.labor.grievance.resolve",
  "republic.hr.labor.grievances",
  "republic.hr.labor.policy",
  "republic.hr.labor.policy.update",
  "republic.hr.labor.violation.resolve",
  "republic.hr.org.structure",
  "republic.hr.org.positions",
  "republic.hr.org.assign",
  "republic.hr.org.unassign",
  "republic.hr.org.autoAssign",
  "republic.hr.org.diagnostics",

  // ── Kali Linux Cybersecurity Sandbox ─────────────────────────
  "republic.cyber.kali.status",
  "republic.cyber.kali.start",
  "republic.cyber.kali.stop",
  "republic.cyber.kali.scan",
  "republic.cyber.kali.scan.status",
  "republic.cyber.kali.scan.cancel",
  "republic.cyber.kali.scans",
  "republic.cyber.kali.report",
  "republic.cyber.kali.exec",
  "republic.cyber.kali.tool.portscan",
  "republic.cyber.kali.tool.webscan",
  "republic.cyber.kali.tool.sqli",
  "republic.cyber.kali.tool.vulnscan",
  "republic.cyber.kali.tool.sslaudit",
  "republic.cyber.kali.tool.bruteforce",
  "republic.cyber.kali.tool.compliance",
  "republic.cyber.kali.tool.clone",
  "republic.cyber.kali.tool.crawl",
  "republic.cyber.kali.exploitdb.sync",
  "republic.cyber.kali.exploitdb.search",
  "republic.cyber.kali.planner.fingerprint",
  "republic.cyber.kali.planner.plan",
  "republic.cyber.kali.planner.execute",
  "republic.cyber.kali.planner.patterns",
  "republic.cyber.kali.auth.login",
  "republic.cyber.kali.auth.pending",
  "republic.cyber.kali.auth.provide",
  "republic.cyber.kali.rag.tools",
  "republic.cyber.kali.tasks.active",
  "republic.cyber.kali.tasks.extend",
  "republic.cyber.kali.tasks.cancel",
  "republic.cyber.kali.semantic.search",
  "republic.cyber.kali.semantic.analyze",
  "republic.cyber.kali.semantic.ingest",
  "republic.cyber.kali.network.devices",
  "republic.cyber.kali.network.discover",

  // ─── Auto-Discovered Missing Methods (Audit Fill) ───
  "my.method",
  "system.version",
  "republic.store.list",
  "republic.marketplace.list",
  "config.test-provider",
  "republic.citizen.list",
  "republic.citizen.history",
  "republic.citizen.command",
  "models.switch",
  "cluster.status",
  "republic.cpe.status",
  "republic.cpe.history",
  "republic.dev.projects",
  "republic.game.read-file",
  "republic.game.archetypes",
  "republic.game.list",
  "republic.game.scaffold",
  "hpics.contacts.assets.list",
  "hpics.contacts.analyze.voice",
  "hpics.contacts.analyze.face",
  "hpics.pipeline.agis.full",
  "models.manager.ollama.list",
  "models.manager.lmstudio.list",
  "models.manager.ollama.pull",
  "models.manager.ollama.delete",
  "models.manager.install",
  "models.manager.download",
  "models.manager.delete",
  "models.manager.pause",
  "models.manager.resume",
  "lovable.generate",
  "manus.tasks.list",
  "manus.retry",
  "manus.task",
  "republic.mediastudio.generate",
  "republic.mediastudio.delete",
  "node.config.get",
  "node.config.push",
  "windows.system.info",
  "windows.hardware.gpu.info",
  "windows.hardware.memory.info",
  "windows.hardware.disk.info",
  "node.workloads.list",
  "node.workloads.pause",
  "node.workloads.resume",
  "republic.plugins.call-gateway",
  "republic.plugins.invoke-tool",
  "republic.plugin-queue.status",
  "republic.plugin-queue.approve",
  "republic.plugin-queue.reject",
  "republic.plugin-queue.cancel",
  "republic.plugin-queue.submit",
  "health.check",
  "health.providers",
  "republic.a2a.agents",
  "republic.a2a.messages.recent",
  "republic.a2a.tasks",
  "republic.a2a.task.cancel",
  "agenthub.dag.list",
  "agenthub.dag.result",
  "agenthub.board.list",
  "agenthub.status",
  "agenthub.dag.run",
  "agenthub.board.post",
  "agenthub.dag.submit",
  "republic.avatar.session.list",
  "republic.avatar.session.create",
  "republic.avatar.speak",
  "republic.avatar.diagnostics",
  "republic.avatar.personality",
  "republic.avatar.session.end",
  "republic.backup.restore.jobs",
  "republic.cicd.run.get",
  "republic.cicd.trigger",
  "republic.cicd.pipeline.create",
  "republic.memory.citizen.episodic",
  "republic.memory.citizen.semantic",
  "republic.db.skills",
  "republic.education.citizen",
  "republic.legacy.events",
  "republic.legacy.achievements",
  "paperclip.companies.list",
  "paperclip.budget.get",
  "paperclip.tickets.list",
  "paperclip.orgchart.get",
  "paperclip.status",
  "paperclip.tickets.create",
  "blackeye.status",
  "blackeye.templates.list",
  "blackeye.campaign.list",
  "scan.status",
  "scan.results",
  "pentagi.status",
  "pentagi.flows.list",
  "pentagi.tools.list",
  "pentagi.flows.logs",
  "blackeye.campaign.create",
  "blackeye.campaign.start",
  "blackeye.campaign.stop",
  "blackeye.campaign.delete",
  "scan.run",
  "scan.delete",
  "pentagi.flows.create",
  "pentagi.flows.stop",
  "republic.diplomacy.conflicts",
  "republic.diplomacy.events",
  "republic.diplomacy.treaty.propose",
  "republic.diplomacy.conflict.register",
  "republic.diplomacy.conflict.resolve",
  "gsd.execute",
  "republic.medical.analyze",
  "republic.medical.ask",
  "republic.model.registry.list",
  "republic.model.registry.register",
  "republic.model.registry.load",
  "republic.model.registry.unload",
  "republic.model.registry.delete",
  "republic.model.registry.set_default",
  "republic.db.collections",
  "republic.db.query",
  "republic.db.collection.drop",
  "republic.db.record.delete",
  "republic.persona.list",
  "republic.persona.chat",
  "republic.persona.create",
  "republic.persona.activate",
  "republic.persona.delete",
  "rac.session.list",
  "rac.stats",
  "rac.session.get",
  "rac.turn.user",
  "rac.milestone.reach",
  "rac.session.delete",
  "rac.session.create",
  "republic.science.ask",
  "republic.science.meta-learn",
  "republic.social.family-tree",
  "republic.social.circles",
  "waragent.simulation.get",
  "waragent.simulation.start",
  "waragent.simulation.step",
  "waragent.simulation.manualAction",
  "channels.send",
  "cluster.resilience.status",
  "republic.revenue.api.summary",
  "republic.revenue.streams.status",
  "republic.revenue.api.keys.create",
  "republic.revenue.gigs.stats",
  "republic.revenue.marketplace.stats",
  "republic.revenue.gigs.scan",
  "republic.revenue.marketplace.scan",

  // ─── Republic: OpenClaw Subsystems ────────────────────────────────────────────
  // Task Flow Orchestration
  "republic.openclaw.tasks.list",
  "republic.openclaw.tasks.get",
  "republic.openclaw.tasks.submit",
  "republic.openclaw.tasks.cancel",
  "republic.openclaw.tasks.events",
  "republic.openclaw.tasks.stats",
  "republic.openclaw.executor.status",
  "republic.openclaw.executor.start",
  "republic.openclaw.executor.stop",
  "republic.openclaw.flows.list",
  "republic.openclaw.flows.create",
  "republic.openclaw.flows.cancel",
  // Context Engine
  "republic.openclaw.context.status",
  "republic.openclaw.context.engines",
  "republic.openclaw.context.resolve",
  "republic.openclaw.context.release",
  // Memory Dreaming
  "republic.openclaw.dreaming.status",
  "republic.openclaw.dreaming.memories",
  "republic.openclaw.dreaming.promoted",
  // Media Provider Registry
  "republic.openclaw.media.status",
  "republic.openclaw.media.providers",
  "republic.openclaw.media.health",
  // MCP Channel Bridge
  "republic.openclaw.mcp.status",
  "republic.openclaw.mcp.servers",
  "republic.openclaw.mcp.conversations",
  "republic.openclaw.mcp.conversation.create",
  "republic.openclaw.mcp.events",
  "republic.openclaw.mcp.approvals",
  "republic.openclaw.mcp.approval.respond",
  // Realtime Voice
  "republic.openclaw.voice.status",
  "republic.openclaw.voice.providers",
  "republic.openclaw.voice.sessions",
  "republic.openclaw.voice.transcript",
  // Realtime Transcription
  "republic.openclaw.transcription.status",
  "republic.openclaw.transcription.providers",
  "republic.openclaw.transcription.sessions",
  // Unified Diagnostics
  "republic.openclaw.diagnostics",
  // Model Fallback Chain
  "republic.openclaw.fallback.status",
  "republic.openclaw.fallback.reset",

  // ─── Republic: Async Tasks (Fire-and-Forget) ───────────────────────────────
  "republic.task.submit",
  "republic.task.status",
  "republic.task.result",
  "republic.task.cancel",
  "republic.task.list",
  "republic.task.stats",

  // ─── Republic: Dynamic Registry (CRUD, search, import/export) ──────────────
  "republic.registry.list",
  "republic.registry.get",
  "republic.registry.upsert",
  "republic.registry.remove",
  "republic.registry.search",
  "republic.registry.history",
  "republic.registry.stats",
  "republic.registry.enable",
  "republic.registry.export",
  "republic.registry.import",
  "republic.registry.domains",

  // ─── Self-Sovereignty: Vision Engine ────────────────────────────────────────
  "republic.sovereign.vision.analyze",
  "republic.sovereign.vision.diagnostics",

  // ─── Self-Sovereignty: Knowledge Base ───────────────────────────────────────
  "republic.sovereign.knowledge.add",
  "republic.sovereign.knowledge.query",
  "republic.sovereign.knowledge.list",
  "republic.sovereign.knowledge.update",
  "republic.sovereign.knowledge.delete",
  "republic.sovereign.knowledge.extract",
  "republic.sovereign.knowledge.diagnostics",

  // ─── Self-Sovereignty: Proactive Engine ─────────────────────────────────────
  "republic.sovereign.proactive.create",
  "republic.sovereign.proactive.list",
  "republic.sovereign.proactive.delete",
  "republic.sovereign.proactive.diagnostics",

  // ─── Self-Sovereignty: Fine-Tune Pipeline ───────────────────────────────────
  "republic.sovereign.finetune.create",
  "republic.sovereign.finetune.list",
  "republic.sovereign.finetune.get",
  "republic.sovereign.finetune.cancel",
  "republic.sovereign.finetune.diagnostics",

  // ─── Self-Sovereignty: Voice Engine ─────────────────────────────────────────
  "republic.sovereign.voice.transcribe",
  "republic.sovereign.voice.synthesize",
  "republic.sovereign.voice.providers",

  // ─── Self-Sovereignty: Search + RAG ─────────────────────────────────────────
  "republic.sovereign.search.grounding",
  "republic.sovereign.search.diagnostics",

  // ─── Self-Sovereignty: Code Interpreter ─────────────────────────────────────
  "republic.sovereign.interpreter.diagnostics",

  // ─── Agent Telemetry ────────────────────────────────────────────────────────
  "republic.agent.telemetry.snapshot",
  "republic.agent.telemetry.session",
  "republic.agent.telemetry.slowest-tools",
  "republic.agent.telemetry.error-prone-tools",
  "republic.agent.strategy.plan",
  "republic.agent.strategy.distribution",
  "republic.agent.strategy.outcomes",

  // ─── Agent Intelligence (Closed-Loop Controller) ─────────────────────────────
  "republic.agent.intelligence.assess",

  // ─── Agent Learning Persistence ───────────────────────────────────────────────
  "republic.agent.learning.export",
  "republic.agent.learning.import",
];
