/**
 * Model Manager — Model Registry (static catalog data)
 */

import type { ManagedModel } from "./types.js";

// ─── Model Registry ───────────────────────────────────────────────────────────

export const MODEL_REGISTRY: Array<
  Omit<ManagedModel, "status" | "localPath" | "sizeBytes" | "downloadProgress" | "downloadSpeed">
> = [
  // ── BitNet ────────────────────────────────────────────────
  // NOTE: microsoft/bitnet-b1.58-2B-4T-gguf only ships the removed i2_s format.
  // Use community GGUF conversions from RichardErkhov instead.
  {
    id: "bitnet-large-iq3m",
    name: "BitNet b1.58 Large (IQ3_M)",
    category: "bitnet",
    repo: "RichardErkhov/1bitLLM_-_bitnet_b1_58-large-gguf",
    filename: "bitnet_b1_58-large.IQ3_M.gguf",
    description: "BitNet b1.58 700M — ultra-fast 1-bit CPU inference. Already downloaded.",
    ramGB: 1,
    diskGB: 0.4,
    quantization: "IQ3_M",
    capabilities: ["chat", "completion"],
    license: "MIT",
    isCore: true,
  },
  {
    id: "bitnet-3b-q4km",
    name: "BitNet b1.58 3B (Q4_K_M)",
    category: "bitnet",
    repo: "RichardErkhov/1bitLLM_-_bitnet_b1_58-3B-gguf",
    filename: "bitnet_b1_58-3B.Q4_K_M.gguf",
    description: "BitNet 3B Q4_K_M — larger 1-bit model for better quality.",
    ramGB: 2,
    diskGB: 1.8,
    quantization: "Q4_K_M",
    capabilities: ["chat", "completion"],
    license: "MIT",
    isCore: false,
  },

  // ── GGUF — Small ──────────────────────────────────────────────
  {
    id: "llama-3.2-3b-q5km",
    name: "Llama 3.2 3B",
    category: "gguf",
    repo: "bartowski/Llama-3.2-3B-Instruct-GGUF",
    filename: "Llama-3.2-3B-Instruct-Q5_K_M.gguf",
    description: "Fast 3B model — good for quick tasks and low-RAM deployments.",
    ramGB: 3,
    diskGB: 2.2,
    quantization: "Q5_K_M",
    capabilities: ["chat"],
    license: "llama3.2",
    isCore: true,
    ollamaTag: "llama3.2",
  },
  {
    id: "gemma-3-4b-q5km",
    name: "Gemma 3 4B",
    category: "gguf",
    repo: "bartowski/gemma-3-4b-it-GGUF",
    filename: "gemma-3-4b-it-Q5_K_M.gguf",
    description: "Google's Gemma 3 4B — excellent multilingual chat and coding.",
    ramGB: 4,
    diskGB: 3,
    quantization: "Q5_K_M",
    capabilities: ["chat", "multilingual"],
    license: "gemma",
    isCore: true,
    ollamaTag: "gemma3:4b",
  },
  {
    id: "qwen-2.5-coder-7b-q5km",
    name: "Qwen 2.5 Coder 7B",
    category: "gguf",
    repo: "bartowski/Qwen2.5-Coder-7B-Instruct-GGUF",
    filename: "Qwen2.5-Coder-7B-Instruct-Q5_K_M.gguf",
    description: "Best-in-class 7B coding model — used by HoC dev agents.",
    ramGB: 6,
    diskGB: 5,
    quantization: "Q5_K_M",
    capabilities: ["chat", "code", "tool_use"],
    license: "apache-2.0",
    isCore: true,
    ollamaTag: "qwen2.5-coder:7b",
  },
  {
    id: "deepseek-r1-7b-q4km",
    name: "DeepSeek R1 7B",
    category: "gguf",
    repo: "bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF",
    filename: "DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf",
    description: "DeepSeek R1 distilled — strong reasoning and coding at 7B.",
    ramGB: 6,
    diskGB: 4.7,
    quantization: "Q4_K_M",
    capabilities: ["chat", "reasoning", "code"],
    license: "MIT",
    isCore: false,
    ollamaTag: "deepseek-r1:7b",
  },

  // ── GGUF — Large ──────────────────────────────────────────────
  {
    id: "phi-4-14b-q4km",
    name: "Phi 4 14B",
    category: "gguf",
    repo: "bartowski/phi-4-GGUF",
    filename: "phi-4-Q4_K_M.gguf",
    description: "Microsoft Phi-4 14B — excellent reasoning, coding, and tool use.",
    ramGB: 10,
    diskGB: 8,
    quantization: "Q4_K_M",
    capabilities: ["chat", "code", "reasoning", "tool_use"],
    license: "MIT",
    isCore: true,
    ollamaTag: "phi4",
  },
  {
    id: "gemma-3-12b-q4km",
    name: "Gemma 3 12B",
    category: "gguf",
    repo: "bartowski/gemma-3-12b-it-GGUF",
    filename: "gemma-3-12b-it-Q4_K_M.gguf",
    description: "Google Gemma 3 12B — vision + multilingual + coding.",
    ramGB: 9,
    diskGB: 7,
    quantization: "Q4_K_M",
    capabilities: ["chat", "code", "vision", "multilingual"],
    license: "gemma",
    isCore: false,
    ollamaTag: "gemma3:12b",
  },
  {
    id: "qwen-2.5-coder-32b-q4km",
    name: "Qwen 2.5 Coder 32B",
    category: "gguf",
    repo: "bartowski/Qwen2.5-Coder-32B-Instruct-GGUF",
    filename: "Qwen2.5-Coder-32B-Instruct-Q4_K_M.gguf",
    description: "Top-tier 32B coding model — best local code generation.",
    ramGB: 24,
    diskGB: 18,
    quantization: "Q4_K_M",
    capabilities: ["chat", "code", "reasoning", "tool_use"],
    license: "apache-2.0",
    isCore: false,
    ollamaTag: "qwen2.5-coder:32b",
  },
  {
    id: "deepseek-r1-32b-q4km",
    name: "DeepSeek R1 32B",
    category: "gguf",
    repo: "bartowski/DeepSeek-R1-Distill-Qwen-32B-GGUF",
    filename: "DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf",
    description: "DeepSeek R1 30B — frontier-level reasoning locally.",
    ramGB: 24,
    diskGB: 18,
    quantization: "Q4_K_M",
    capabilities: ["chat", "reasoning", "code"],
    license: "MIT",
    isCore: false,
    ollamaTag: "deepseek-r1:32b",
  },
  {
    id: "gemma-3-27b-q4km",
    name: "Gemma 3 27B",
    category: "gguf",
    repo: "bartowski/gemma-3-27b-it-GGUF",
    filename: "gemma-3-27b-it-Q4_K_M.gguf",
    description: "Google's largest open model — 27B with vision.",
    ramGB: 20,
    diskGB: 15,
    quantization: "Q4_K_M",
    capabilities: ["chat", "code", "reasoning", "vision", "multilingual"],
    license: "gemma",
    isCore: false,
    ollamaTag: "gemma3:27b",
  },

  // ── Embeddings ────────────────────────────────────────────────
  {
    id: "nomic-embed-text",
    name: "Nomic Embed Text",
    category: "embedding",
    repo: "nomic-ai/nomic-embed-text-v1.5",
    filename: "nomic-embed-text-v1.5.Q8_0.gguf",
    description: "High-quality text embedding — used by memory and search systems.",
    ramGB: 0.5,
    diskGB: 0.3,
    capabilities: ["embedding"],
    license: "apache-2.0",
    isCore: true,
    ollamaTag: "nomic-embed-text",
  },
  {
    id: "mxbai-embed-large",
    name: "mxbai Embed Large",
    category: "embedding",
    repo: "mixedbread-ai/mxbai-embed-large-v1",
    filename: "mxbai-embed-large-v1-f16.gguf",
    description: "Mixedbread large embedding model — state-of-the-art vector search.",
    ramGB: 1,
    diskGB: 0.7,
    capabilities: ["embedding"],
    license: "apache-2.0",
    isCore: false,
    ollamaTag: "mxbai-embed-large",
  },

  // ── Audio / MMAudio ────────────────────────────────────────────
  {
    id: "mmaudio-large-44k",
    name: "MMAudio Large 44k v2",
    category: "audio",
    repo: "hkchengrex/MMAudio",
    filename: "weights_v2.pth",
    description: "MMAudio — large multimodal audio generation model (44kHz, CVPR 2025).",
    ramGB: 4,
    diskGB: 6,
    capabilities: ["audio-generation", "video-to-audio"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-mmaudio",
    vramGB: 6,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    files: [
      { name: "weights_v2.pth", sizeEstimate: "2.5 GB" },
      { name: "weights.pth", sizeEstimate: "2.5 GB" },
      { name: "best_listener.pth", sizeEstimate: "1.3 GB" },
    ],
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── TTS / Chatterbox ──────────────────────────────────────────
  {
    id: "chatterbox-tts",
    name: "Chatterbox TTS (Resemble AI)",
    category: "tts",
    repo: "ResembleAI/chatterbox",
    filename: "s3gen.safetensors",
    description:
      "Chatterbox TTS — voice cloning and synthesis. Turbo, Standard, and Multilingual variants.",
    ramGB: 4,
    diskGB: 7.5,
    capabilities: ["tts", "voice-cloning", "multilingual"],
    license: "NC",
    isCore: false,
    pluginId: "hoc-plugin-chatterbox",
    vramGB: 4,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    files: [
      { name: "s3gen.safetensors", sizeEstimate: "1.06 GB" },
      { name: "t3_cfg.safetensors", sizeEstimate: "2.13 GB" },
      { name: "ve.safetensors", sizeEstimate: "5.7 MB" },
      { name: "conds.pt", sizeEstimate: "107 KB" },
      { name: "tokenizer.json", sizeEstimate: "25 KB" },
      { name: "t3_23lang.safetensors", sizeEstimate: "2.14 GB" },
      { name: "t3_mtl23ls_v2.safetensors", sizeEstimate: "2.14 GB" },
      { name: "mtl_tokenizer.json", sizeEstimate: "68 KB" },
    ],
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── TTS / Bark ────────────────────────────────────────────────
  {
    id: "bark-tts",
    name: "Bark TTS (Suno AI)",
    category: "tts",
    repo: "suno/bark",
    filename: "pytorch_model.bin",
    description: "Bark TTS — speech, music, sound effects, 100+ voice presets, 13 languages.",
    ramGB: 8,
    diskGB: 22,
    capabilities: ["tts", "music-generation", "sound-effects", "multilingual"],
    license: "MIT",
    isCore: false,
    pluginId: "hoc-plugin-bark",
    vramGB: 8,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    files: [
      { name: "text.pt", sizeEstimate: "2.32 GB" },
      { name: "coarse.pt", sizeEstimate: "1.25 GB" },
      { name: "fine.pt", sizeEstimate: "1.11 GB" },
      { name: "text_2.pt", sizeEstimate: "5.35 GB" },
      { name: "coarse_2.pt", sizeEstimate: "3.93 GB" },
      { name: "fine_2.pt", sizeEstimate: "3.74 GB" },
      { name: "pytorch_model.bin", sizeEstimate: "4.49 GB" },
      { name: "config.json", sizeEstimate: "9 KB" },
      { name: "tokenizer.json", sizeEstimate: "2.9 MB" },
    ],
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── TTS / Qwen3-TTS ────────────────────────────────────────────
  {
    id: "qwen3-tts",
    name: "Qwen3-TTS (Alibaba)",
    category: "tts",
    repo: "QwenLM/Qwen3-TTS",
    filename: "model.safetensors",
    description: "Qwen3-TTS — voice synthesis, design, and cloning from Alibaba.",
    ramGB: 4,
    diskGB: 4,
    capabilities: ["tts", "voice-cloning", "voice-design"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-qwen3-tts",
    vramGB: 6,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── TTS / LuxTTS ────────────────────────────────────────────────
  {
    id: "luxtts",
    name: "LuxTTS (Voice Cloning)",
    category: "tts",
    repo: "YatharthS/LuxTTS",
    filename: "model.safetensors",
    description:
      "LuxTTS — Lightweight zipvoice based high-quality voice cloning and generation at 150x realtime.",
    ramGB: 2,
    diskGB: 1.5,
    capabilities: ["tts", "voice-cloning"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-luxtts",
    vramGB: 1,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── Diffusion / OmniGen ────────────────────────────────────────
  {
    id: "omnigen-v1",
    name: "OmniGen v1",
    category: "diffusion",
    repo: "Shitao/OmniGen-v1",
    filename: "model.safetensors",
    description: "OmniGen — unified image generation, editing, and visual reasoning.",
    ramGB: 8,
    diskGB: 7.5,
    capabilities: ["image-generation", "image-editing"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-omnigen",
    vramGB: 8,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    files: [
      { name: "model.safetensors", sizeEstimate: "7.5 GB" },
      { name: "config.json", sizeEstimate: "1 KB" },
      { name: "tokenizer.json", sizeEstimate: "7 MB" },
      { name: "tokenizer_config.json", sizeEstimate: "1 KB" },
    ],
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── Diffusion / Switti ────────────────────────────────────────
  {
    id: "switti-base",
    name: "Switti Base",
    category: "diffusion",
    repo: "yresearch/Switti",
    filename: "switti.safetensors",
    description: "Switti — fast transformer-based text-to-image generation.",
    ramGB: 6,
    diskGB: 3.5,
    capabilities: ["image-generation"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-switti",
    vramGB: 6,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── Diffusion / SD 2.1 (Deforum) ──────────────────────────────
  {
    id: "sd-2.1-deforum",
    name: "Stable Diffusion 2.1 (Deforum)",
    category: "diffusion",
    repo: "stabilityai/stable-diffusion-2-1",
    filename: "v2-1_768-ema-pruned.safetensors",
    description: "SD 2.1 — backbone for Deforum animated video generation.",
    ramGB: 6,
    diskGB: 5.2,
    capabilities: ["image-generation", "animation"],
    license: "openrail++",
    isCore: false,
    pluginId: "hoc-plugin-deforum",
    vramGB: 8,
    downloadType: "single-file",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── Diffusion / SDXL Base (StoryDiffusion) ────────────────────
  {
    id: "sdxl-base-1.0",
    name: "SDXL Base 1.0 (StoryDiffusion)",
    category: "diffusion",
    repo: "stabilityai/stable-diffusion-xl-base-1.0",
    filename: "sd_xl_base_1.0.safetensors",
    description: "SDXL Base 1.0 — backbone for StoryDiffusion consistent character generation.",
    ramGB: 8,
    diskGB: 6.9,
    capabilities: ["image-generation", "story-generation"],
    license: "openrail++",
    isCore: false,
    pluginId: "hoc-plugin-storydiffusion",
    vramGB: 8,
    downloadType: "single-file",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── Diffusion / FLUX.1 Dev (KV-Edit) ──────────────────────────
  {
    id: "flux1-dev",
    name: "FLUX.1 Dev (KV-Edit)",
    category: "diffusion",
    repo: "black-forest-labs/FLUX.1-dev",
    filename: "flux1-dev.safetensors",
    description: "FLUX.1 Dev — 12B DiT model for KV-Edit image editing. Requires 24GB+ VRAM.",
    ramGB: 24,
    diskGB: 23.8,
    capabilities: ["image-generation", "image-editing"],
    license: "FLUX-1-dev-non-commercial",
    isCore: false,
    pluginId: "hoc-plugin-kv-edit",
    vramGB: 24,
    downloadType: "single-file",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── Diffusion / GLM-Image (CogView4) ──────────────────────────
  {
    id: "cogview4-6b",
    name: "CogView4 6B (GLM-Image)",
    category: "diffusion",
    repo: "THUDM/CogView4-6B",
    filename: "model.safetensors",
    description: "CogView4 6B — GLM-Image generation. Requires 80GB+ VRAM or multi-GPU.",
    ramGB: 16,
    diskGB: 12,
    capabilities: ["image-generation", "text2image"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-glm-image",
    vramGB: 80,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda", "diffusers"],
  },

  // ── Diffusion / SD VAE (Avatar/Face pipelines) ────────────────
  {
    id: "sd-vae-ft-mse",
    name: "SD VAE ft-mse",
    category: "diffusion",
    repo: "stabilityai/sd-vae-ft-mse",
    filename: "diffusion_pytorch_model.safetensors",
    description: "SD VAE — shared VAE for StableAvatar and face/avatar pipelines.",
    ramGB: 1,
    diskGB: 0.34,
    capabilities: ["vae", "image-encoding"],
    license: "openrail++",
    isCore: false,
    vramGB: 2,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    files: [
      { name: "diffusion_pytorch_model.safetensors", sizeEstimate: "335 MB" },
      { name: "config.json", sizeEstimate: "547 B" },
    ],
  },

  // ── 3D / Stable Zero123 (Sparc3D) ─────────────────────────────
  {
    id: "stable-zero123",
    name: "Stable Zero123 (3D)",
    category: "3d",
    repo: "stabilityai/stable-zero123",
    filename: "stable_zero123.ckpt",
    description: "Stable Zero123 — single-image to 3D generation for Sparc3D.",
    ramGB: 10,
    diskGB: 8.6,
    capabilities: ["3d-generation", "image-to-3d"],
    license: "openrail++",
    isCore: false,
    pluginId: "hoc-plugin-sparc3d",
    vramGB: 12,
    downloadType: "single-file",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── 3D / StableAvatar ──────────────────────────────────────────
  {
    id: "stable-avatar",
    name: "StableAvatar",
    category: "3d",
    repo: "Francis-Rings/StableAvatar",
    filename: "inference.py",
    description: "StableAvatar — audio-driven talking-head synthesis.",
    ramGB: 8,
    diskGB: 4,
    capabilities: ["avatar", "talking-head", "audio-driven"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-stable-avatar",
    vramGB: 8,
    downloadType: "git-clone",
    prerequisites: ["python3", "torch", "cuda", "git"],
  },

  // ── Audio / InspireMusic ───────────────────────────────────────
  {
    id: "inspiremusic-base",
    name: "InspireMusic Base (FunAudioLLM)",
    category: "audio",
    repo: "FunAudioLLM/InspireMusic-Base",
    filename: "llm.pt",
    description: "InspireMusic — AI music generation with text and audio prompts.",
    ramGB: 8,
    diskGB: 5,
    capabilities: ["music-generation", "audio-to-audio"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-funmusic",
    vramGB: 8,
    downloadType: "git-clone",
    prerequisites: ["python3", "torch", "cuda", "git", "flash-attn"],
  },

  // ── Diffusion / MagicAnimate ───────────────────────────────────
  {
    id: "magicanimate",
    name: "MagicAnimate (Bytedance)",
    category: "diffusion",
    repo: "zcxu-eric/MagicAnimate",
    filename: "appearance_encoder/diffusion_pytorch_model.safetensors",
    description: "MagicAnimate — temporally consistent human image animation.",
    ramGB: 8,
    diskGB: 8,
    capabilities: ["animation", "image-to-video"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-magicanimate",
    vramGB: 8,
    downloadType: "git-clone",
    prerequisites: ["python3", "torch", "cuda", "git"],
  },

  // ── Diffusion / LingBot-World ──────────────────────────────────
  {
    id: "lingbot-world",
    name: "LingBot World Sim",
    category: "diffusion",
    repo: "robbyant/lingbot-world-base-cam",
    filename: "model.safetensors",
    description: "LingBot-World — world simulation model. Requires 8GB+ VRAM (NF4 quantized).",
    ramGB: 12,
    diskGB: 10,
    capabilities: ["world-simulation", "video-generation"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-lingbot-world",
    vramGB: 8,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda"],
  },

  // ── Face / FaceFusion ──────────────────────────────────────────
  {
    id: "facefusion-inswapper",
    name: "FaceFusion Inswapper",
    category: "face",
    repo: "facefusion/facefusion-assets",
    filename: "inswapper_128_fp16.onnx",
    description: "FaceFusion face swap model — FP16 ONNX format.",
    ramGB: 2,
    diskGB: 0.5,
    capabilities: ["face-swap"],
    license: "NC",
    isCore: false,
    pluginId: "hoc-plugin-facefusion",
    vramGB: 4,
    downloadType: "single-file",
  },
  {
    id: "facefusion-gfpgan",
    name: "FaceFusion GFPGAN",
    category: "face",
    repo: "facefusion/facefusion-assets",
    filename: "GFPGANv1.4.pth",
    description: "GFPGAN face enhancement model for FaceFusion.",
    ramGB: 1,
    diskGB: 0.35,
    capabilities: ["face-enhancement"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-facefusion",
    vramGB: 2,
    downloadType: "single-file",
  },

  // ── Face / DeepFaceLab ─────────────────────────────────────────
  {
    id: "deepfacelab",
    name: "DeepFaceLab",
    category: "face",
    repo: "iperov/DeepFaceLab",
    filename: "SAEHD.py",
    description: "DeepFaceLab — advanced face swapping and aging.",
    ramGB: 6,
    diskGB: 2,
    capabilities: ["face-swap", "deepfake", "face-aging"],
    license: "GPL-3.0",
    isCore: false,
    pluginId: "hoc-plugin-deepfacelab",
    vramGB: 6,
    downloadType: "git-clone",
    prerequisites: ["python3", "torch", "cuda", "git"],
  },

  // ── Video Generation ────────────────────────────────────────────
  {
    id: "cogvideox-2b",
    name: "CogVideoX-2B (INT8)",
    category: "video",
    repo: "THUDM/CogVideoX-2b",
    filename: "transformer/diffusion_pytorch_model.safetensors",
    description: "CogVideoX 2B — fast draft-quality video generation, 8GB VRAM. INT8 quantized.",
    ramGB: 8,
    diskGB: 3.5,
    capabilities: ["text-to-video", "draft-quality"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-cogvideox",
    vramGB: 8,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda", "diffusers"],
  },
  {
    id: "wan-2.2-5b",
    name: "Wan 2.2 5B MoE (FP16)",
    category: "video",
    repo: "Wan-AI/Wan2.2-T2V-14B",
    filename: "diffusion_pytorch_model.safetensors",
    description: "Wan 2.2 — cinematic text-to-video and image-to-video. 720p, excellent lighting.",
    ramGB: 12,
    diskGB: 10,
    capabilities: ["text-to-video", "image-to-video", "cinematic"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-wan-video",
    vramGB: 12,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda", "diffusers"],
  },
  {
    id: "ltx-2",
    name: "LTX-2 (FP8)",
    category: "video",
    repo: "Lightricks/LTX-Video-2B",
    filename: "ltx-video-2b-v0.9.5.safetensors",
    description: "LTX-2 — 4K/50fps video with synchronized audio. Production-quality.",
    ramGB: 12,
    diskGB: 8,
    capabilities: ["text-to-video", "4k", "50fps", "audio-sync"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-ltx-video",
    vramGB: 12,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda", "diffusers"],
  },
  {
    id: "hunyuan-1.5-13b",
    name: "HunyuanVideo 1.5 13B (FP8)",
    category: "video",
    repo: "tencent/HunyuanVideo",
    filename: "hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states_fp8.pt",
    description:
      "HunyuanVideo 1.5 13B — hero-quality cinematic video. FP8 quantized, 1080p upscale.",
    ramGB: 16,
    diskGB: 14,
    capabilities: ["text-to-video", "hero-quality", "1080p-upscale"],
    license: "tencent-hunyuan",
    isCore: false,
    pluginId: "hoc-plugin-hunyuan-video",
    vramGB: 14,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda", "flash-attn"],
  },
  {
    id: "skyreels-v2-14b",
    name: "SkyReels V2 14B",
    category: "video",
    repo: "Skywork/SkyReels-V2-T2V-14B-540P",
    filename: "diffusion_pytorch_model.safetensors",
    description:
      "SkyReels V2 14B — infinite-length film generation. Multi-scene, character continuity.",
    ramGB: 28,
    diskGB: 28,
    capabilities: ["text-to-video", "infinite-length", "multi-scene", "continuity"],
    license: "apache-2.0",
    isCore: false,
    pluginId: "hoc-plugin-skyreels",
    vramGB: 24,
    downloadType: "hf-repo",
    hfCacheLayout: true,
    prerequisites: ["python3", "torch", "cuda", "flash-attn"],
  },
];
