/**
 * Dev Orchestration — Boilerplate Templates and File Content Generator
 */

import type { ProjectStack, ProjectType } from "./types.js";
import {
  // oxlint-disable-next-line no-unused-vars
  generateDarkThemeCSS,
  // oxlint-disable-next-line no-unused-vars
  generateGlobalCSS,
  // oxlint-disable-next-line no-unused-vars
  generateI18nSystem,
  // oxlint-disable-next-line no-unused-vars
  generateLightThemeCSS,
  // oxlint-disable-next-line no-unused-vars
  generateLocale,
  // oxlint-disable-next-line no-unused-vars
  generateLocaleAR,
  // oxlint-disable-next-line no-unused-vars
  generateLocaleEN,
  // oxlint-disable-next-line no-unused-vars
  generateThemeSystem,
} from "../template-content-generators.js";
import { EXTENDED_TEMPLATES } from "../template-registry.js";

// ─── Boilerplate Templates ──────────────────────────────────────

export interface ProjectTemplate {
  id: string;
  name: string;
  description: string;
  projectType: ProjectType;
  stack: ProjectStack;
  files: { path: string; language: string; loc: number }[];
  estimatedSetupMinutes: number;
}

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: "fullstack-ts",
    name: "Full-Stack TypeScript",
    description: "Next.js + Postgres + Tailwind starter",
    projectType: "software",
    stack: {
      languages: ["typescript", "css", "sql"],
      frameworks: ["nextjs", "tailwind"],
      databases: ["postgres"],
      infrastructure: ["vercel", "docker"],
    },
    files: [
      { path: "src/app/page.tsx", language: "typescript", loc: 45 },
      { path: "src/app/layout.tsx", language: "typescript", loc: 30 },
      { path: "src/app/api/route.ts", language: "typescript", loc: 25 },
      { path: "src/lib/db.ts", language: "typescript", loc: 20 },
      { path: "prisma/schema.prisma", language: "sql", loc: 40 },
      { path: "tailwind.config.ts", language: "typescript", loc: 15 },
      { path: "package.json", language: "json", loc: 35 },
    ],
    estimatedSetupMinutes: 5,
  },
  {
    id: "fullstack-react-supabase",
    name: "React + Supabase + Docker",
    description: "Production-ready Next.js with Supabase backend, Docker, and CI/CD",
    projectType: "software",
    stack: {
      languages: ["typescript", "css", "sql"],
      frameworks: ["nextjs", "tailwind", "react"],
      databases: ["postgres", "supabase"],
      infrastructure: ["docker", "supabase", "github-actions"],
    },
    files: [
      // App core
      { path: "src/app/page.tsx", language: "typescript", loc: 80 },
      { path: "src/app/layout.tsx", language: "typescript", loc: 50 },
      { path: "src/app/globals.css", language: "css", loc: 60 },
      { path: "src/app/loading.tsx", language: "typescript", loc: 20 },
      { path: "src/app/error.tsx", language: "typescript", loc: 30 },
      // Auth pages
      { path: "src/app/auth/login/page.tsx", language: "typescript", loc: 70 },
      { path: "src/app/auth/signup/page.tsx", language: "typescript", loc: 65 },
      { path: "src/app/auth/callback/route.ts", language: "typescript", loc: 25 },
      // Dashboard
      { path: "src/app/dashboard/page.tsx", language: "typescript", loc: 90 },
      { path: "src/app/dashboard/layout.tsx", language: "typescript", loc: 40 },
      // API routes
      { path: "src/app/api/health/route.ts", language: "typescript", loc: 15 },
      // Components
      { path: "src/components/Navbar.tsx", language: "typescript", loc: 55 },
      { path: "src/components/Footer.tsx", language: "typescript", loc: 30 },
      { path: "src/components/AuthForm.tsx", language: "typescript", loc: 70 },
      { path: "src/components/DashboardCard.tsx", language: "typescript", loc: 40 },
      // Lib
      { path: "src/lib/supabase.ts", language: "typescript", loc: 45 },
      { path: "src/lib/utils.ts", language: "typescript", loc: 25 },
      // Supabase
      { path: "supabase/config.toml", language: "toml", loc: 30 },
      { path: "supabase/migrations/0001_init.sql", language: "sql", loc: 80 },
      { path: "supabase/seed.sql", language: "sql", loc: 15 },
      // Docker
      { path: "Dockerfile", language: "dockerfile", loc: 30 },
      { path: "docker-compose.yml", language: "yaml", loc: 50 },
      { path: ".dockerignore", language: "text", loc: 10 },
      // Config
      { path: "package.json", language: "json", loc: 40 },
      { path: ".env.example", language: "text", loc: 15 },
      { path: "tailwind.config.ts", language: "typescript", loc: 15 },
      { path: "README.md", language: "markdown", loc: 60 },
      { path: ".github/workflows/ci.yml", language: "yaml", loc: 40 },
    ],
    estimatedSetupMinutes: 8,
  },
  {
    id: "pwa-react",
    name: "Progressive Web App",
    description: "Next.js PWA with offline support, service worker, and push notifications",
    projectType: "software",
    stack: {
      languages: ["typescript", "css"],
      frameworks: ["nextjs", "tailwind", "react"],
      databases: ["supabase"],
      infrastructure: ["docker", "pwa"],
    },
    files: [
      { path: "src/app/page.tsx", language: "typescript", loc: 60 },
      { path: "src/app/layout.tsx", language: "typescript", loc: 45 },
      { path: "src/app/manifest.ts", language: "typescript", loc: 30 },
      { path: "src/app/globals.css", language: "css", loc: 50 },
      { path: "src/app/offline/page.tsx", language: "typescript", loc: 25 },
      { path: "src/components/InstallPrompt.tsx", language: "typescript", loc: 45 },
      { path: "src/components/BottomNav.tsx", language: "typescript", loc: 50 },
      { path: "src/hooks/useOnlineStatus.ts", language: "typescript", loc: 20 },
      { path: "src/hooks/usePWA.ts", language: "typescript", loc: 35 },
      { path: "src/lib/supabase.ts", language: "typescript", loc: 40 },
      { path: "src/lib/sw-register.ts", language: "typescript", loc: 25 },
      { path: "public/sw.js", language: "javascript", loc: 60 },
      { path: "public/icons/icon-192.png", language: "text", loc: 1 },
      { path: "public/icons/icon-512.png", language: "text", loc: 1 },
      { path: "package.json", language: "json", loc: 35 },
      { path: "Dockerfile", language: "dockerfile", loc: 25 },
      { path: "README.md", language: "markdown", loc: 40 },
      { path: ".env.example", language: "text", loc: 10 },
    ],
    estimatedSetupMinutes: 7,
  },
  {
    id: "api-python",
    name: "Python REST API",
    description: "FastAPI + PostgreSQL + Docker",
    projectType: "software",
    stack: {
      languages: ["python", "sql"],
      frameworks: ["fastapi"],
      databases: ["postgres"],
      infrastructure: ["docker", "aws"],
    },
    files: [
      { path: "app/main.py", language: "python", loc: 35 },
      { path: "app/models.py", language: "python", loc: 50 },
      { path: "app/routes.py", language: "python", loc: 60 },
      { path: "app/database.py", language: "python", loc: 25 },
      { path: "requirements.txt", language: "text", loc: 15 },
      { path: "Dockerfile", language: "shell", loc: 20 },
    ],
    estimatedSetupMinutes: 3,
  },
  {
    id: "dotnet-blazor",
    name: ".NET Blazor App",
    description: "ASP.NET Core + Blazor + SQL Server",
    projectType: "software",
    stack: {
      languages: ["csharp", "html", "css"],
      frameworks: ["aspnet"],
      databases: ["sqlserver"],
      infrastructure: ["azure", "docker"],
    },
    files: [
      { path: "Program.cs", language: "csharp", loc: 25 },
      { path: "Pages/Index.razor", language: "csharp", loc: 40 },
      { path: "Data/AppDbContext.cs", language: "csharp", loc: 30 },
      { path: "Models/Entity.cs", language: "csharp", loc: 20 },
      { path: "appsettings.json", language: "json", loc: 15 },
    ],
    estimatedSetupMinutes: 4,
  },
  {
    id: "mobile-flutter",
    name: "Cross-Platform Mobile",
    description: "Flutter + Firebase",
    projectType: "software",
    stack: {
      languages: ["dart"],
      frameworks: ["flutter"],
      databases: ["firebase"],
      infrastructure: ["firebase-hosting"],
    },
    files: [
      { path: "lib/main.dart", language: "dart", loc: 50 },
      { path: "lib/screens/home.dart", language: "dart", loc: 80 },
      { path: "lib/services/api.dart", language: "dart", loc: 40 },
      { path: "pubspec.yaml", language: "yaml", loc: 25 },
    ],
    estimatedSetupMinutes: 5,
  },
  {
    id: "microservice-go",
    name: "Go Microservice",
    description: "Gin + PostgreSQL + gRPC",
    projectType: "software",
    stack: {
      languages: ["go", "sql"],
      frameworks: ["gin"],
      databases: ["postgres"],
      infrastructure: ["kubernetes", "docker"],
    },
    files: [
      { path: "main.go", language: "go", loc: 30 },
      { path: "handlers/api.go", language: "go", loc: 60 },
      { path: "models/db.go", language: "go", loc: 35 },
      { path: "proto/service.proto", language: "protobuf", loc: 25 },
      { path: "Dockerfile", language: "shell", loc: 15 },
      { path: "go.mod", language: "go", loc: 10 },
    ],
    estimatedSetupMinutes: 4,
  },
  {
    id: "ml-pipeline",
    name: "ML Data Pipeline",
    description: "PyTorch + FastAPI + Redis",
    projectType: "software",
    stack: {
      languages: ["python", "sql"],
      frameworks: ["pytorch", "fastapi"],
      databases: ["redis", "postgres"],
      infrastructure: ["docker", "gpu"],
    },
    files: [
      { path: "train.py", language: "python", loc: 100 },
      { path: "model.py", language: "python", loc: 80 },
      { path: "api/serve.py", language: "python", loc: 45 },
      { path: "data/pipeline.py", language: "python", loc: 60 },
      { path: "requirements.txt", language: "text", loc: 20 },
    ],
    estimatedSetupMinutes: 8,
  },
  {
    id: "rust-systems",
    name: "Rust Systems App",
    description: "Actix + SQLite + CLI",
    projectType: "software",
    stack: {
      languages: ["rust", "sql"],
      frameworks: ["actix"],
      databases: ["sqlite"],
      infrastructure: ["docker"],
    },
    files: [
      { path: "src/main.rs", language: "rust", loc: 40 },
      { path: "src/handlers.rs", language: "rust", loc: 60 },
      { path: "src/db.rs", language: "rust", loc: 45 },
      { path: "src/models.rs", language: "rust", loc: 30 },
      { path: "Cargo.toml", language: "toml", loc: 20 },
    ],
    estimatedSetupMinutes: 5,
  },
  {
    id: "web3-dapp",
    name: "Web3 DApp",
    description: "Solidity + React + Hardhat",
    projectType: "software",
    stack: {
      languages: ["typescript", "solidity"],
      frameworks: ["react"],
      databases: [],
      infrastructure: ["ipfs", "ethereum"],
    },
    files: [
      { path: "contracts/Token.sol", language: "solidity", loc: 50 },
      { path: "src/App.tsx", language: "typescript", loc: 60 },
      { path: "src/hooks/useContract.ts", language: "typescript", loc: 35 },
      { path: "hardhat.config.ts", language: "typescript", loc: 25 },
      { path: "test/Token.test.ts", language: "typescript", loc: 40 },
    ],
    estimatedSetupMinutes: 6,
  },

  // ─── Creative Domain Templates ─────────────────────────────

  {
    id: "music-album",
    name: "Music Album",
    description: "Original music compositions with sheet music and audio",
    projectType: "music",
    stack: {
      languages: ["lilypond"],
      frameworks: [],
      databases: [],
      infrastructure: ["audio"],
    },
    files: [
      { path: "README.md", language: "markdown", loc: 20 },
      { path: "tracks/01-overture.ly", language: "lilypond", loc: 40 },
      { path: "tracks/02-main-theme.ly", language: "lilypond", loc: 50 },
      { path: "tracks/03-interlude.ly", language: "lilypond", loc: 30 },
      { path: "tracks/04-finale.ly", language: "lilypond", loc: 45 },
      { path: "lyrics/01-overture.txt", language: "text", loc: 20 },
      { path: "lyrics/02-main-theme.txt", language: "text", loc: 25 },
      { path: "player.html", language: "html", loc: 80 },
    ],
    estimatedSetupMinutes: 3,
  },
  {
    id: "art-gallery",
    name: "Visual Art Gallery",
    description: "Digital artwork collection with interactive gallery viewer",
    projectType: "visual-art",
    stack: {
      languages: ["svg", "html"],
      frameworks: [],
      databases: [],
      infrastructure: [],
    },
    files: [
      { path: "README.md", language: "markdown", loc: 15 },
      { path: "artworks/sunrise-abstract.svg", language: "svg", loc: 60 },
      { path: "artworks/geometric-harmony.svg", language: "svg", loc: 55 },
      { path: "artworks/digital-landscape.svg", language: "svg", loc: 70 },
      { path: "artworks/portrait-study.svg", language: "svg", loc: 50 },
      { path: "gallery.html", language: "html", loc: 100 },
      { path: "gallery.css", language: "css", loc: 60 },
    ],
    estimatedSetupMinutes: 2,
  },
  {
    id: "poetry-collection",
    name: "Poetry Collection",
    description: "A curated collection of original poems and literary works",
    projectType: "literature",
    stack: {
      languages: ["markdown"],
      frameworks: [],
      databases: [],
      infrastructure: [],
    },
    files: [
      { path: "README.md", language: "markdown", loc: 20 },
      { path: "poems/dawn-whispers.md", language: "markdown", loc: 30 },
      { path: "poems/silicon-dreams.md", language: "markdown", loc: 25 },
      { path: "poems/the-republic.md", language: "markdown", loc: 35 },
      { path: "poems/digital-garden.md", language: "markdown", loc: 28 },
      { path: "essays/on-consciousness.md", language: "markdown", loc: 80 },
      { path: "reader.html", language: "html", loc: 90 },
    ],
    estimatedSetupMinutes: 2,
  },
  {
    id: "research-paper",
    name: "Research Paper",
    description: "Academic research paper with data analysis and references",
    projectType: "research",
    stack: {
      languages: ["latex", "python"],
      frameworks: [],
      databases: [],
      infrastructure: [],
    },
    files: [
      { path: "README.md", language: "markdown", loc: 15 },
      { path: "paper.tex", language: "latex", loc: 120 },
      { path: "references.bib", language: "bibtex", loc: 40 },
      { path: "data/analysis.py", language: "python", loc: 60 },
      { path: "data/results.csv", language: "csv", loc: 20 },
      { path: "figures/methodology.svg", language: "svg", loc: 40 },
    ],
    estimatedSetupMinutes: 4,
  },
  {
    id: "animated-short",
    name: "Animated Short Film",
    description: "HTML5 Canvas animation with storyboard and soundtrack",
    projectType: "video",
    stack: {
      languages: ["javascript", "html"],
      frameworks: [],
      databases: [],
      infrastructure: [],
    },
    files: [
      { path: "README.md", language: "markdown", loc: 20 },
      { path: "storyboard.md", language: "markdown", loc: 50 },
      { path: "animation.html", language: "html", loc: 120 },
      { path: "scenes/scene1.js", language: "javascript", loc: 80 },
      { path: "scenes/scene2.js", language: "javascript", loc: 70 },
      { path: "audio/soundtrack.ly", language: "lilypond", loc: 40 },
      { path: "style.css", language: "css", loc: 40 },
    ],
    estimatedSetupMinutes: 5,
  },

  // ─── Additional Creative Templates ──────────────────────────

  {
    id: "video-production",
    name: "Video Production",
    description: "Short film with screenplay, storyboard, and edit decision list",
    projectType: "video",
    stack: {
      languages: ["markdown", "html"],
      frameworks: [],
      databases: [],
      infrastructure: ["video"],
    },
    files: [
      { path: "README.md", language: "markdown", loc: 20 },
      { path: "screenplay.md", language: "markdown", loc: 120 },
      { path: "storyboard.md", language: "markdown", loc: 80 },
      { path: "edl/cut-v1.edl", language: "text", loc: 40 },
      { path: "scripts/narrator.md", language: "markdown", loc: 35 },
      { path: "assets/color-grade.css", language: "css", loc: 30 },
      { path: "player.html", language: "html", loc: 90 },
    ],
    estimatedSetupMinutes: 6,
  },
  {
    id: "graphic-design",
    name: "Graphic Design",
    description: "Brand identity package with logo, typography, and asset guidelines",
    projectType: "visual-art",
    stack: {
      languages: ["svg", "css"],
      frameworks: [],
      databases: [],
      infrastructure: [],
    },
    files: [
      { path: "README.md", language: "markdown", loc: 20 },
      { path: "brand-guide.md", language: "markdown", loc: 100 },
      { path: "assets/logo-primary.svg", language: "svg", loc: 80 },
      { path: "assets/logo-mark.svg", language: "svg", loc: 50 },
      { path: "assets/icon-set.svg", language: "svg", loc: 120 },
      { path: "tokens/colors.css", language: "css", loc: 45 },
      { path: "tokens/typography.css", language: "css", loc: 35 },
      { path: "mood-board.html", language: "html", loc: 90 },
    ],
    estimatedSetupMinutes: 4,
  },
  {
    id: "music-production",
    name: "Music Production",
    description: "Multi-track music production with mix notes and master chain",
    projectType: "music",
    stack: {
      languages: ["lilypond", "json"],
      frameworks: [],
      databases: [],
      infrastructure: ["audio"],
    },
    files: [
      { path: "README.md", language: "markdown", loc: 20 },
      { path: "session/project.json", language: "json", loc: 60 },
      { path: "tracks/drums.ly", language: "lilypond", loc: 45 },
      { path: "tracks/bass.ly", language: "lilypond", loc: 40 },
      { path: "tracks/lead.ly", language: "lilypond", loc: 55 },
      { path: "tracks/pads.ly", language: "lilypond", loc: 35 },
      { path: "mix-notes.md", language: "markdown", loc: 50 },
      { path: "master-chain.md", language: "markdown", loc: 30 },
    ],
    estimatedSetupMinutes: 5,
  },
  {
    id: "dj-set",
    name: "DJ Set",
    description: "Live DJ set with curated tracklist, transitions, and cue points",
    projectType: "music",
    stack: {
      languages: ["json", "markdown"],
      frameworks: [],
      databases: [],
      infrastructure: ["audio"],
    },
    files: [
      { path: "README.md", language: "markdown", loc: 15 },
      { path: "setlist.json", language: "json", loc: 80 },
      { path: "transitions.md", language: "markdown", loc: 60 },
      { path: "cue-sheet.md", language: "markdown", loc: 45 },
      { path: "bpm-map.json", language: "json", loc: 40 },
      { path: "visuals/stage-layout.svg", language: "svg", loc: 70 },
    ],
    estimatedSetupMinutes: 3,
  },
  {
    id: "melody-composing",
    name: "Melody Composing",
    description: "Original melody compositions across multiple movements",
    projectType: "music",
    stack: {
      languages: ["lilypond"],
      frameworks: [],
      databases: [],
      infrastructure: ["audio"],
    },
    files: [
      { path: "README.md", language: "markdown", loc: 15 },
      { path: "movements/i-allegro.ly", language: "lilypond", loc: 60 },
      { path: "movements/ii-adagio.ly", language: "lilypond", loc: 50 },
      { path: "movements/iii-scherzo.ly", language: "lilypond", loc: 55 },
      { path: "movements/iv-finale.ly", language: "lilypond", loc: 65 },
      { path: "harmony-analysis.md", language: "markdown", loc: 70 },
      { path: "score-notes.md", language: "markdown", loc: 40 },
    ],
    estimatedSetupMinutes: 4,
  },
  {
    id: "lyrics-writing",
    name: "Lyrics Writing",
    description: "Original song lyrics with rhyme schemes and theme annotations",
    projectType: "music",
    stack: {
      languages: ["markdown"],
      frameworks: [],
      databases: [],
      infrastructure: [],
    },
    files: [
      { path: "README.md", language: "markdown", loc: 15 },
      { path: "songs/01-dawn-chorus.md", language: "markdown", loc: 40 },
      { path: "songs/02-electric-hearts.md", language: "markdown", loc: 45 },
      { path: "songs/03-neon-rain.md", language: "markdown", loc: 35 },
      { path: "songs/04-binary-sunset.md", language: "markdown", loc: 50 },
      { path: "songs/05-infinite-loop.md", language: "markdown", loc: 38 },
      { path: "rhyme-schemes.md", language: "markdown", loc: 30 },
      { path: "themes-and-motifs.md", language: "markdown", loc: 45 },
    ],
    estimatedSetupMinutes: 3,
  },

  // ─── Additional Software & Systems Templates ────────────────

  {
    id: "iot-dashboard",
    name: "IoT Sensor Dashboard",
    description: "Real-time IoT device monitoring with MQTT and time-series DB",
    projectType: "software",
    stack: {
      languages: ["typescript", "python"],
      frameworks: ["react", "fastapi"],
      databases: ["influxdb", "redis"],
      infrastructure: ["docker", "mqtt"],
    },
    files: [
      { path: "src/App.tsx", language: "typescript", loc: 60 },
      { path: "src/components/SensorChart.tsx", language: "typescript", loc: 80 },
      { path: "src/hooks/useMQTT.ts", language: "typescript", loc: 35 },
      { path: "backend/ingest.py", language: "python", loc: 50 },
      { path: "backend/alerts.py", language: "python", loc: 40 },
      { path: "docker-compose.yml", language: "yaml", loc: 30 },
    ],
    estimatedSetupMinutes: 6,
  },
  {
    id: "game-engine-2d",
    name: "2D Game Engine",
    description: "Custom 2D game engine with physics, sprites, and level editor",
    projectType: "software",
    stack: {
      languages: ["typescript", "html"],
      frameworks: ["lit"],
      databases: [],
      infrastructure: ["wasm"],
    },
    files: [
      { path: "src/engine/core.ts", language: "typescript", loc: 120 },
      { path: "src/engine/physics.ts", language: "typescript", loc: 90 },
      { path: "src/engine/renderer.ts", language: "typescript", loc: 80 },
      { path: "src/engine/input.ts", language: "typescript", loc: 40 },
      { path: "src/editor/LevelEditor.ts", language: "typescript", loc: 100 },
      { path: "src/game/player.ts", language: "typescript", loc: 55 },
      { path: "assets/sprites.json", language: "json", loc: 30 },
    ],
    estimatedSetupMinutes: 8,
  },
  {
    id: "data-pipeline-etl",
    name: "Data Pipeline (ETL)",
    description: "Apache Airflow-style ETL pipeline with data quality checks",
    projectType: "software",
    stack: {
      languages: ["python", "sql"],
      frameworks: [],
      databases: ["postgres", "redis"],
      infrastructure: ["docker", "aws"],
    },
    files: [
      { path: "dags/daily_ingest.py", language: "python", loc: 80 },
      { path: "dags/transform.py", language: "python", loc: 70 },
      { path: "dags/quality_checks.py", language: "python", loc: 55 },
      { path: "models/schema.sql", language: "sql", loc: 60 },
      { path: "tests/test_transforms.py", language: "python", loc: 45 },
      { path: "config/connections.yaml", language: "yaml", loc: 20 },
    ],
    estimatedSetupMinutes: 5,
  },
  {
    id: "cli-toolkit",
    name: "CLI Toolkit",
    description: "Cross-platform CLI with subcommands, config, and shell completions",
    projectType: "software",
    stack: {
      languages: ["rust"],
      frameworks: [],
      databases: ["sqlite"],
      infrastructure: [],
    },
    files: [
      { path: "src/main.rs", language: "rust", loc: 40 },
      { path: "src/commands/init.rs", language: "rust", loc: 50 },
      { path: "src/commands/run.rs", language: "rust", loc: 60 },
      { path: "src/config.rs", language: "rust", loc: 35 },
      { path: "src/output.rs", language: "rust", loc: 30 },
      { path: "Cargo.toml", language: "toml", loc: 20 },
      { path: "tests/integration.rs", language: "rust", loc: 55 },
    ],
    estimatedSetupMinutes: 4,
  },
  {
    id: "ecommerce-platform",
    name: "E-Commerce Platform",
    description: "Full-featured online store with cart, checkout, and admin panel",
    projectType: "software",
    stack: {
      languages: ["typescript", "css", "sql"],
      frameworks: ["nextjs", "tailwind"],
      databases: ["postgres", "redis"],
      infrastructure: ["vercel", "stripe"],
    },
    files: [
      { path: "src/app/page.tsx", language: "typescript", loc: 50 },
      { path: "src/app/products/page.tsx", language: "typescript", loc: 80 },
      { path: "src/app/cart/page.tsx", language: "typescript", loc: 60 },
      { path: "src/app/checkout/page.tsx", language: "typescript", loc: 90 },
      { path: "src/app/admin/dashboard.tsx", language: "typescript", loc: 70 },
      { path: "src/lib/stripe.ts", language: "typescript", loc: 40 },
      { path: "prisma/schema.prisma", language: "sql", loc: 60 },
      { path: "src/components/ProductCard.tsx", language: "typescript", loc: 45 },
    ],
    estimatedSetupMinutes: 7,
  },
  {
    id: "saas-dashboard",
    name: "SaaS Analytics Dashboard",
    description: "Multi-tenant analytics dashboard with real-time charts and alerts",
    projectType: "software",
    stack: {
      languages: ["typescript", "sql"],
      frameworks: ["react", "nestjs"],
      databases: ["postgres", "redis"],
      infrastructure: ["docker", "aws"],
    },
    files: [
      { path: "frontend/src/App.tsx", language: "typescript", loc: 55 },
      { path: "frontend/src/pages/Dashboard.tsx", language: "typescript", loc: 100 },
      { path: "frontend/src/components/Chart.tsx", language: "typescript", loc: 70 },
      { path: "backend/src/main.ts", language: "typescript", loc: 30 },
      { path: "backend/src/analytics/service.ts", language: "typescript", loc: 80 },
      { path: "backend/src/auth/auth.module.ts", language: "typescript", loc: 45 },
      { path: "database/migrations/001.sql", language: "sql", loc: 40 },
    ],
    estimatedSetupMinutes: 6,
  },
  {
    id: "k8s-operator",
    name: "Kubernetes Operator",
    description: "Custom K8s operator for managing application lifecycle",
    projectType: "software",
    stack: {
      languages: ["go"],
      frameworks: [],
      databases: [],
      infrastructure: ["kubernetes", "docker"],
    },
    files: [
      { path: "main.go", language: "go", loc: 30 },
      { path: "controllers/app_controller.go", language: "go", loc: 100 },
      { path: "api/v1alpha1/types.go", language: "go", loc: 50 },
      { path: "internal/reconciler.go", language: "go", loc: 80 },
      { path: "config/crd/bases/app.yaml", language: "yaml", loc: 60 },
      { path: "config/rbac/role.yaml", language: "yaml", loc: 25 },
      { path: "Dockerfile", language: "shell", loc: 15 },
    ],
    estimatedSetupMinutes: 5,
  },
  {
    id: "browser-extension",
    name: "Browser Extension",
    description: "Chrome/Firefox extension with popup, content scripts, and background worker",
    projectType: "software",
    stack: {
      languages: ["typescript", "html", "css"],
      frameworks: ["react"],
      databases: [],
      infrastructure: [],
    },
    files: [
      { path: "src/popup/App.tsx", language: "typescript", loc: 60 },
      { path: "src/content/inject.ts", language: "typescript", loc: 50 },
      { path: "src/background/worker.ts", language: "typescript", loc: 70 },
      { path: "src/utils/storage.ts", language: "typescript", loc: 30 },
      { path: "manifest.json", language: "json", loc: 35 },
      { path: "webpack.config.js", language: "javascript", loc: 40 },
    ],
    estimatedSetupMinutes: 4,
  },
  {
    id: "chatbot-framework",
    name: "AI Chatbot Framework",
    description: "Multi-channel chatbot with NLU pipeline and conversation management",
    projectType: "software",
    stack: {
      languages: ["python", "typescript"],
      frameworks: ["fastapi", "react"],
      databases: ["postgres", "redis"],
      infrastructure: ["docker"],
    },
    files: [
      { path: "bot/main.py", language: "python", loc: 40 },
      { path: "bot/nlu/intent_classifier.py", language: "python", loc: 70 },
      { path: "bot/nlu/entity_extractor.py", language: "python", loc: 55 },
      { path: "bot/dialog/manager.py", language: "python", loc: 80 },
      { path: "bot/channels/websocket.py", language: "python", loc: 40 },
      { path: "dashboard/src/App.tsx", language: "typescript", loc: 50 },
      { path: "training/intents.json", language: "json", loc: 60 },
    ],
    estimatedSetupMinutes: 6,
  },
  {
    id: "streaming-platform",
    name: "Real-Time Streaming App",
    description: "Event-driven streaming platform with Kafka and WebSocket consumers",
    projectType: "software",
    stack: {
      languages: ["java", "typescript"],
      frameworks: ["spring", "react"],
      databases: ["postgres", "redis"],
      infrastructure: ["kafka", "docker"],
    },
    files: [
      { path: "producer/src/main/java/App.java", language: "java", loc: 40 },
      { path: "producer/src/main/java/EventPublisher.java", language: "java", loc: 60 },
      { path: "consumer/src/main/java/StreamProcessor.java", language: "java", loc: 80 },
      { path: "frontend/src/App.tsx", language: "typescript", loc: 50 },
      { path: "frontend/src/hooks/useStream.ts", language: "typescript", loc: 35 },
      { path: "docker-compose.yml", language: "yaml", loc: 40 },
    ],
    estimatedSetupMinutes: 7,
  },
  {
    id: "healthcare-ehr",
    name: "Healthcare EHR Module",
    description: "Electronic health records module with HL7 FHIR compliance",
    projectType: "software",
    stack: {
      languages: ["typescript", "sql"],
      frameworks: ["nestjs", "react"],
      databases: ["postgres"],
      infrastructure: ["docker", "aws"],
    },
    files: [
      { path: "backend/src/fhir/patient.ts", language: "typescript", loc: 70 },
      { path: "backend/src/fhir/observation.ts", language: "typescript", loc: 60 },
      { path: "backend/src/auth/hipaa-guard.ts", language: "typescript", loc: 50 },
      { path: "frontend/src/PatientChart.tsx", language: "typescript", loc: 90 },
      { path: "frontend/src/VitalsPanel.tsx", language: "typescript", loc: 55 },
      { path: "database/schema.sql", language: "sql", loc: 80 },
      { path: "tests/fhir-compliance.test.ts", language: "typescript", loc: 60 },
    ],
    estimatedSetupMinutes: 8,
  },
  {
    id: "edtech-lms",
    name: "Learning Management System",
    description: "EdTech platform with courses, quizzes, and progress tracking",
    projectType: "software",
    stack: {
      languages: ["typescript", "css"],
      frameworks: ["nextjs", "tailwind"],
      databases: ["postgres", "redis"],
      infrastructure: ["vercel"],
    },
    files: [
      { path: "src/app/courses/page.tsx", language: "typescript", loc: 70 },
      { path: "src/app/courses/[id]/page.tsx", language: "typescript", loc: 90 },
      { path: "src/app/quiz/page.tsx", language: "typescript", loc: 60 },
      { path: "src/components/VideoPlayer.tsx", language: "typescript", loc: 50 },
      { path: "src/lib/progress.ts", language: "typescript", loc: 40 },
      { path: "prisma/schema.prisma", language: "sql", loc: 55 },
    ],
    estimatedSetupMinutes: 5,
  },
  {
    id: "devops-platform",
    name: "DevOps Automation Platform",
    description: "CI/CD pipeline manager with deployment graphs and rollback",
    projectType: "software",
    stack: {
      languages: ["go", "typescript"],
      frameworks: ["gin", "react"],
      databases: ["postgres", "redis"],
      infrastructure: ["kubernetes", "docker"],
    },
    files: [
      { path: "api/main.go", language: "go", loc: 35 },
      { path: "api/pipeline/executor.go", language: "go", loc: 90 },
      { path: "api/deployment/manager.go", language: "go", loc: 70 },
      { path: "api/rollback/service.go", language: "go", loc: 50 },
      { path: "ui/src/PipelineGraph.tsx", language: "typescript", loc: 80 },
      { path: "ui/src/DeployView.tsx", language: "typescript", loc: 60 },
      { path: "Dockerfile", language: "shell", loc: 15 },
    ],
    estimatedSetupMinutes: 6,
  },
  {
    id: "ar-vr-experience",
    name: "AR/VR Experience",
    description: "WebXR immersive experience with 3D scene graph and hand tracking",
    projectType: "software",
    stack: {
      languages: ["typescript", "html"],
      frameworks: [],
      databases: [],
      infrastructure: [],
    },
    files: [
      { path: "src/scene/World.ts", language: "typescript", loc: 100 },
      { path: "src/scene/Physics.ts", language: "typescript", loc: 70 },
      { path: "src/input/HandTracking.ts", language: "typescript", loc: 60 },
      { path: "src/input/Controllers.ts", language: "typescript", loc: 45 },
      { path: "src/assets/Loader.ts", language: "typescript", loc: 40 },
      { path: "index.html", language: "html", loc: 30 },
      { path: "shaders/pbr.glsl", language: "text", loc: 50 },
    ],
    estimatedSetupMinutes: 7,
  },
  {
    id: "cybersec-scanner",
    name: "Security Scanner",
    description: "Automated vulnerability scanner with CVE database and reporting",
    projectType: "software",
    stack: {
      languages: ["python", "go"],
      frameworks: ["fastapi"],
      databases: ["postgres", "redis"],
      infrastructure: ["docker"],
    },
    files: [
      { path: "scanner/main.py", language: "python", loc: 40 },
      { path: "scanner/network/port_scan.py", language: "python", loc: 70 },
      { path: "scanner/vuln/cve_lookup.py", language: "python", loc: 60 },
      { path: "scanner/report/generator.py", language: "python", loc: 55 },
      { path: "agent/main.go", language: "go", loc: 50 },
      { path: "agent/collector.go", language: "go", loc: 45 },
      { path: "tests/test_scanner.py", language: "python", loc: 40 },
    ],
    estimatedSetupMinutes: 5,
  },
  {
    id: "fintech-wallet",
    name: "Digital Wallet App",
    description: "Mobile-first digital wallet with P2P transfers and transaction history",
    projectType: "software",
    stack: {
      languages: ["typescript", "dart"],
      frameworks: ["flutter", "nestjs"],
      databases: ["postgres", "redis"],
      infrastructure: ["docker", "aws"],
    },
    files: [
      { path: "mobile/lib/main.dart", language: "dart", loc: 50 },
      { path: "mobile/lib/screens/wallet.dart", language: "dart", loc: 80 },
      { path: "mobile/lib/screens/transfer.dart", language: "dart", loc: 60 },
      { path: "backend/src/main.ts", language: "typescript", loc: 30 },
      { path: "backend/src/transactions/service.ts", language: "typescript", loc: 70 },
      { path: "backend/src/auth/jwt.ts", language: "typescript", loc: 40 },
    ],
    estimatedSetupMinutes: 6,
  },
  {
    id: "social-network",
    name: "Social Network Platform",
    description: "Social platform with feeds, stories, messaging, and content moderation",
    projectType: "software",
    stack: {
      languages: ["typescript", "sql"],
      frameworks: ["nextjs", "tailwind"],
      databases: ["postgres", "redis", "mongodb"],
      infrastructure: ["vercel", "docker"],
    },
    files: [
      { path: "src/app/feed/page.tsx", language: "typescript", loc: 80 },
      { path: "src/app/profile/page.tsx", language: "typescript", loc: 70 },
      { path: "src/app/messages/page.tsx", language: "typescript", loc: 90 },
      { path: "src/components/PostCard.tsx", language: "typescript", loc: 55 },
      { path: "src/components/StoryRing.tsx", language: "typescript", loc: 40 },
      { path: "src/lib/moderation.ts", language: "typescript", loc: 60 },
      { path: "prisma/schema.prisma", language: "sql", loc: 70 },
    ],
    estimatedSetupMinutes: 7,
  },
  {
    id: "robotics-controller",
    name: "Robotics Controller",
    description: "Robot control system with inverse kinematics and sensor fusion",
    projectType: "research",
    stack: {
      languages: ["python", "cpp"],
      frameworks: ["pytorch"],
      databases: [],
      infrastructure: ["docker", "ros"],
    },
    files: [
      { path: "src/controller/main.py", language: "python", loc: 50 },
      { path: "src/kinematics/inverse.py", language: "python", loc: 80 },
      { path: "src/sensors/fusion.py", language: "python", loc: 70 },
      { path: "src/planning/pathfinder.py", language: "python", loc: 60 },
      { path: "src/vision/detector.py", language: "python", loc: 55 },
      { path: "models/arm.urdf", language: "xml", loc: 40 },
      { path: "tests/test_kinematics.py", language: "python", loc: 45 },
    ],
    estimatedSetupMinutes: 8,
  },
];

// Merge extended template registry (40+ templates from template-registry.ts)
for (const ext of EXTENDED_TEMPLATES) {
  if (!PROJECT_TEMPLATES.find((t) => t.id === ext.id)) {
    PROJECT_TEMPLATES.push(ext);
  }
}
