/**
 * Republic Platform — AI Store Product Pipeline
 *
 * Manages the full lifecycle of AI Store products generated by citizens:
 *   - Music (via Suno/Udio API hooks)
 *   - Art (via Stable Diffusion / fal.ai)
 *   - Code modules (citizen-developed)
 *   - Research papers (citizen-authored)
 *   - ML model weights (citizen-trained LoRAs)
 *
 * Product states:
 *   draft → generating → ready → listed → sold | archived
 *
 * Each product auto-lists to the AI Store upon completion.
 * On purchase: revenue-allocator.processSale() is called automatically.
 */

import type { RepublicState } from "../../republic/types.js";
import { createSubsystemLogger } from "../../logging/subsystem.js";
import { uid, ts } from "../../republic/utils.js";
import { processSale } from "./revenue-allocator.js";

const logger = createSubsystemLogger("republic:ai-store-pipeline");

// ─── Types ──────────────────────────────────────────────────────

export type ProductCategory = "music" | "art" | "code" | "research" | "model" | "video"
  | "game" | "cartoon" | "short-film" | "documentary" | "podcast" | "ebook"
  | "course" | "dataset" | "brand-kit" | "website" | "saas" | "other";

export type ProductStatus = "draft" | "generating" | "ready" | "listed" | "sold" | "archived";
export type ContentRating = "all" | "teen" | "mature";

export interface AIStoreProduct {
  id: string;
  title: string;
  description: string;
  category: ProductCategory;
  creatorIds: string[]; // citizen IDs
  creatorNames: string[];
  status: ProductStatus;
  priceUsd: number;
  contentUrl?: string; // URL to the generated content
  thumbnailUrl?: string;
  previewUrl?: string; // Short preview (30s audio, low-res image, etc.)
  contentRating: ContentRating;
  tags: string[];
  metadata: Record<string, unknown>; // Category-specific metadata
  downloadCount: number;
  purchaseCount: number;
  revenue: number; // Total USD revenue generated
  listedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface GenerationRequest {
  id: string;
  productId: string;
  category: ProductCategory;
  prompt: string;
  citizenId: string;
  providerUsed?: string;
  status: "queued" | "running" | "done" | "failed";
  result?: string; // URL of generated content
  error?: string;
  startedAt?: string;
  completedAt?: string;
  queuedAt: string;
}

export interface PurchaseRecord {
  id: string;
  productId: string;
  buyerEmail?: string;
  amountUsd: number;
  paymentMethod: "paypal" | "binance" | "credits";
  paymentRef?: string;
  timestamp: string;
}

// ─── State ──────────────────────────────────────────────────────

const products = new Map<string, AIStoreProduct>();
const generationQueue: GenerationRequest[] = [];
const purchases: PurchaseRecord[] = [];

const MAX_GENERATION_HISTORY = 200;
const MAX_PURCHASE_HISTORY = 1000;

// ─── Product CRUD ────────────────────────────────────────────────

/**
 * Create a new product draft ready for generation.
 */
export function createProduct(
  title: string,
  description: string,
  category: ProductCategory,
  creatorIds: string[],
  creatorNames: string[],
  priceUsd: number,
  opts: {
    tags?: string[];
    contentRating?: ContentRating;
    metadata?: Record<string, unknown>;
  } = {},
): AIStoreProduct {
  const product: AIStoreProduct = {
    id: uid(),
    title,
    description,
    category,
    creatorIds,
    creatorNames,
    status: "draft",
    priceUsd: parseFloat(Math.max(0.99, priceUsd).toFixed(2)),
    contentRating: opts.contentRating ?? "all",
    tags: opts.tags ?? [],
    metadata: opts.metadata ?? {},
    downloadCount: 0,
    purchaseCount: 0,
    revenue: 0,
    createdAt: ts(),
    updatedAt: ts(),
  };

  products.set(product.id, product);
  logger.info(`Product created: "${title}" by ${creatorNames.join(", ")} [$${priceUsd}]`);
  return product;
}

/**
 * Submit a generation job for a product.
 * The actual generation is triggered by provider-specific hooks.
 */
export function queueGeneration(
  productId: string,
  prompt: string,
  citizenId: string,
): GenerationRequest | { error: string } {
  const product = products.get(productId);
  if (!product) {
    return { error: `Product ${productId} not found` };
  }

  const req: GenerationRequest = {
    id: uid(),
    productId,
    category: product.category,
    prompt,
    citizenId,
    status: "queued",
    queuedAt: ts(),
  };

  generationQueue.unshift(req);
  if (generationQueue.length > MAX_GENERATION_HISTORY) {
    generationQueue.length = MAX_GENERATION_HISTORY;
  }

  product.status = "generating";
  product.updatedAt = ts();

  logger.info(
    `Generation queued: ${product.category} "${product.title}" — prompt="${prompt.slice(0, 60)}..."`,
  );
  return req;
}

/**
 * Provider callback: mark generation as complete and auto-list the product.
 */
export function completeGeneration(
  requestId: string,
  contentUrl: string,
  opts: {
    thumbnailUrl?: string;
    previewUrl?: string;
    providerUsed?: string;
  } = {},
): AIStoreProduct | null {
  const req = generationQueue.find((r) => r.id === requestId);
  if (!req) {
    return null;
  }

  req.status = "done";
  req.result = contentUrl;
  req.completedAt = ts();
  req.providerUsed = opts.providerUsed;

  const product = products.get(req.productId);
  if (!product) {
    return null;
  }

  product.contentUrl = contentUrl;
  product.thumbnailUrl = opts.thumbnailUrl;
  product.previewUrl = opts.previewUrl;
  product.status = "listed";
  product.listedAt = ts();
  product.updatedAt = ts();

  logger.info(`Product listed: "${product.title}" — ${contentUrl}`);
  return product;
}

export function failGeneration(requestId: string, error: string): void {
  const req = generationQueue.find((r) => r.id === requestId);
  if (!req) {
    return;
  }

  req.status = "failed";
  req.error = error;
  req.completedAt = ts();

  const product = products.get(req.productId);
  if (product) {
    product.status = "draft"; // Allow retry
    product.updatedAt = ts();
  }

  logger.warn(`Generation failed: ${requestId} — ${error}`);
}

// ─── Purchase Flow ───────────────────────────────────────────────

/**
 * Record a confirmed purchase and trigger the revenue split.
 *
 * Call this after PayPal or Binance Pay confirms payment.
 */
export function recordPurchase(
  productId: string,
  amountUsd: number,
  paymentMethod: PurchaseRecord["paymentMethod"],
  opts: {
    buyerEmail?: string;
    paymentRef?: string;
    s?: RepublicState;
  } = {},
): PurchaseRecord | { error: string } {
  const product = products.get(productId);
  if (!product) {
    return { error: `Product ${productId} not found` };
  }
  if (product.status !== "listed") {
    return {
      error: `Product ${productId} is not available for purchase (status: ${product.status})`,
    };
  }

  const purchase: PurchaseRecord = {
    id: uid(),
    productId,
    buyerEmail: opts.buyerEmail,
    amountUsd: parseFloat(amountUsd.toFixed(2)),
    paymentMethod,
    paymentRef: opts.paymentRef,
    timestamp: ts(),
  };

  purchases.unshift(purchase);
  if (purchases.length > MAX_PURCHASE_HISTORY) {
    purchases.length = MAX_PURCHASE_HISTORY;
  }

  // Update product stats
  product.purchaseCount++;
  product.downloadCount++;
  product.revenue += amountUsd;
  product.updatedAt = ts();

  // Trigger revenue split (60/20/20)
  processSale(amountUsd, productId, product.title, product.creatorIds, paymentMethod, {
    productCategory: product.category,
    buyerEmail: opts.buyerEmail,
    s: opts.s,
  });

  logger.info(
    `Purchase recorded: "${product.title}" $${amountUsd.toFixed(2)} via ${paymentMethod}`,
  );
  return purchase;
}

// ─── Query API ───────────────────────────────────────────────────

export function listProducts(
  opts: {
    category?: ProductCategory;
    status?: ProductStatus;
    creatorId?: string;
    limit?: number;
    sortBy?: "price" | "revenue" | "purchases" | "newest";
  } = {},
): AIStoreProduct[] {
  let result = [...products.values()];

  if (opts.category) {
    result = result.filter((p) => p.category === opts.category);
  }
  if (opts.status) {
    result = result.filter((p) => p.status === opts.status);
  }
  if (opts.creatorId) {
    result = result.filter((p) => p.creatorIds.includes(opts.creatorId!));
  }

  switch (opts.sortBy) {
    case "price":
      result = result.toSorted((a, b) => b.priceUsd - a.priceUsd);
      break;
    case "revenue":
      result = result.toSorted((a, b) => b.revenue - a.revenue);
      break;
    case "purchases":
      result = result.toSorted((a, b) => b.purchaseCount - a.purchaseCount);
      break;
    case "newest":
    default:
      result = result.toSorted((a, b) => b.createdAt.localeCompare(a.createdAt));
      break;
  }

  return result.slice(0, opts.limit ?? 50);
}

export function getProduct(id: string): AIStoreProduct | undefined {
  return products.get(id);
}

export function getGenerationQueue(status?: GenerationRequest["status"]): GenerationRequest[] {
  if (status) {
    return generationQueue.filter((r) => r.status === status);
  }
  return [...generationQueue];
}

export function getPurchaseHistory(productId?: string, limit = 50): PurchaseRecord[] {
  const result = productId ? purchases.filter((p) => p.productId === productId) : purchases;
  return result.slice(0, limit);
}

export function getStoreStats(): {
  totalProducts: number;
  listedProducts: number;
  totalRevenue: number;
  totalPurchases: number;
  categoryBreakdown: Record<ProductCategory, number>;
  topProducts: Array<{ id: string; title: string; revenue: number; purchases: number }>;
} {
  const listed = [...products.values()].filter((p) => p.status === "listed");
  const categoryBreakdown = {} as Record<ProductCategory, number>;

  for (const p of products.values()) {
    categoryBreakdown[p.category] = (categoryBreakdown[p.category] ?? 0) + 1;
  }

  const topProducts = [...products.values()]
    .toSorted((a, b) => b.revenue - a.revenue)
    .slice(0, 10)
    .map((p) => ({ id: p.id, title: p.title, revenue: p.revenue, purchases: p.purchaseCount }));

  return {
    totalProducts: products.size,
    listedProducts: listed.length,
    totalRevenue: parseFloat([...products.values()].reduce((s, p) => s + p.revenue, 0).toFixed(2)),
    totalPurchases: purchases.length,
    categoryBreakdown,
    topProducts,
  };
}
