/**
 * Backoffice Automation Engine
 *
 * Handles automated product maintenance:
 *   - Version bumping when product is regenerated
 *   - Changelog writing
 *   - Platform sync (push updated content to publications)
 *   - Revenue analytics reporting
 *   - Refund processing management
 */

import { createSubsystemLogger } from "../../logging/subsystem.js";
import { uid, ts } from "../utils.js";

const logger = createSubsystemLogger("republic:backoffice");

export interface ChangelogEntry {
  id: string;
  productId: string;
  version: string;
  changes: string[];
  releasedAt: string;
}

export interface BackofficeEvent {
  id: string;
  type: "version-bump" | "sync" | "refund" | "review-response" | "analytics";
  productId?: string;
  detail: string;
  status: "ok" | "failed";
  createdAt: string;
}

const changelogs = new Map<string, ChangelogEntry[]>(); // productId → entries
const events: BackofficeEvent[] = [];
const versionCounters = new Map<string, number>(); // productId → version number
const MAX_EVENTS = 500;

function nextVersion(productId: string): string {
  const n = (versionCounters.get(productId) ?? 0) + 1;
  versionCounters.set(productId, n);
  return `1.${n}.0`;
}

function logEvent(type: BackofficeEvent["type"], productId: string | undefined, detail: string, status: "ok" | "failed" = "ok"): void {
  events.unshift({ id: uid(), type, productId, detail, status, createdAt: ts() });
  if (events.length > MAX_EVENTS) { events.length = MAX_EVENTS; }
}

/**
 * Record a version bump and write a changelog entry.
 * Call when product content is regenerated.
 */
export function bumpVersion(productId: string, productTitle: string, changes: string[]): ChangelogEntry {
  const version = nextVersion(productId);
  const entry: ChangelogEntry = { id: uid(), productId, version, changes, releasedAt: ts() };
  const existing = changelogs.get(productId) ?? [];
  changelogs.set(productId, [entry, ...existing]);
  logEvent("version-bump", productId, `${productTitle} → v${version}: ${changes.length} changes`);
  logger.info(`[Backoffice] v${version} for "${productTitle}"`);
  return entry;
}

/**
 * Generate a weekly revenue analytics report string.
 */
export function generateAnalyticsReport(products: Array<{ id: string; title: string; revenue: number; purchaseCount: number; category: string }>): string {
  const total = products.reduce((s, p) => s + p.revenue, 0);
  const topProducts = [...products].toSorted((a, b) => b.revenue - a.revenue).slice(0, 5);
  const byCat: Record<string, number> = {};
  for (const p of products) { byCat[p.category] = (byCat[p.category] ?? 0) + p.revenue; }
  const topCat = Object.entries(byCat).toSorted((a, b) => b[1] - a[1])[0];

  const report = `=== HoC Republic Weekly Revenue Report ===
Date: ${new Date().toISOString().split("T")[0]}

TOTAL REVENUE: $${total.toFixed(2)}
PRODUCTS SOLD: ${products.filter(p => p.purchaseCount > 0).length} / ${products.length}
TOP CATEGORY: ${topCat?.[0] ?? "N/A"} ($${(topCat?.[1] ?? 0).toFixed(2)})

TOP 5 PRODUCTS:
${topProducts.map((p, i) => `  ${i + 1}. ${p.title} — $${p.revenue.toFixed(2)} (${p.purchaseCount} sales)`).join("\n")}

Generated by HoC Backoffice Engine`;

  logEvent("analytics", undefined, `Report generated: $${total.toFixed(2)} total revenue`);
  return report;
}

/**
 * Record a refund event.
 */
export function recordRefundIssued(productId: string, productTitle: string, amountUsd: number, reason: string): void {
  logEvent("refund", productId, `$${amountUsd.toFixed(2)} refund for "${productTitle}": ${reason}`);
  logger.info(`[Backoffice] Refund issued for "${productTitle}": $${amountUsd}`);
}

/**
 * Generate an automated review response.
 */
export function generateReviewResponse(productId: string, productTitle: string, reviewText: string, rating: number): string {
  const isPositive = rating >= 4;
  const response = isPositive
    ? `Thank you so much for your kind review of "${productTitle}"! We're thrilled you enjoyed it. Our AI citizens worked hard to bring you this experience and your feedback motivates us to keep creating. 🚀`
    : `We appreciate your honest feedback on "${productTitle}". Our support team has noted your concerns and our QA citizens are investigating improvements. Please reach out if you need direct assistance — we're committed to making this right! 🙏`;
  logEvent("review-response", productId, `Review response generated for "${productTitle}" (${rating}★)`);
  return response;
}

export function getChangelog(productId: string): ChangelogEntry[] { return changelogs.get(productId) ?? []; }
export function getAllChangelogs(limit = 50): Array<ChangelogEntry & { _productId: string }> {
  const all: Array<ChangelogEntry & { _productId: string }> = [];
  for (const [pid, entries] of changelogs.entries()) {
    for (const e of entries) { all.push({ ...e, _productId: pid }); }
  }
  return all.toSorted((a, b) => b.releasedAt.localeCompare(a.releasedAt)).slice(0, limit);
}
export function getEvents(limit = 100): BackofficeEvent[] { return events.slice(0, limit); }
export function getBackofficeStats(): { totalEvents: number; refunds: number; versionBumps: number; reports: number } {
  return { totalEvents: events.length, refunds: events.filter(e => e.type === "refund").length, versionBumps: events.filter(e => e.type === "version-bump").length, reports: events.filter(e => e.type === "analytics").length };
}
