/**
 * Autonomous Marketing Bureau
 *
 * Citizens with Marketer, ContentCreator, or Designer specialization
 * are automatically assigned to listed products to produce:
 *   - Taglines and press releases
 *   - Twitter/X, LinkedIn, Reddit posts
 *   - Social card images (via image generation plugins)
 *   - SEO package (meta title, description, keywords, schema.org JSON-LD)
 *   - Promotional video clips (via video generation plugins)
 *
 * Marketing packages are stored per-product and delivered via RPC.
 */

import { createSubsystemLogger } from "../../logging/subsystem.js";
import { uid, ts } from "../utils.js";

const logger = createSubsystemLogger("republic:marketing-bureau");

// ─── Types ──────────────────────────────────────────────────────────────────

export interface MarketingPackage {
  id: string;
  productId: string;
  productTitle: string;
  productCategory: string;
  creatorNames: string[];

  // Copy
  tagline: string;
  hook: string;             // one-liner hook for ads
  pressRelease: string;     // 200-word press release
  elevatorPitch: string;    // 30-second verbal pitch

  // Social posts
  tweets: string[];         // 3 variants (casual, hype, technical)
  linkedInPost: string;
  redditPost: { title: string; body: string };
  tiktokCaption: string;
  youtubeDescription: string;

  // SEO
  seoTitle: string;
  seoDescription: string;   // <160 chars for meta
  keywords: string[];
  schemaOrgJson: string;    // JSON-LD for Google rich snippets

  // Media (URLs set when generated by plugins)
  socialCardUrl?: string;   // 1200×630 banner
  thumbnailUrl?: string;    // 400×400 square
  promoVideoUrl?: string;   // 15-30s promo clip

  // Status
  status: "generating" | "ready";
  pendingAssets: string[];  // which media assets are still being generated
  createdAt: string;
  updatedAt: string;
}

// ─── State ──────────────────────────────────────────────────────────────────

const packages = new Map<string, MarketingPackage>();
const packagesByProduct = new Map<string, string>(); // productId → packageId

// ─── Copy Generators ─────────────────────────────────────────────────────────

function generateTagline(title: string, category: string): string {
  const hooks: Record<string, string[]> = {
    game:          ["Play it. Love it. Ship it.", "The next great game — built by AI.", "100% AI-crafted. 100% fun."],
    music:         ["Sounds made by minds.", "AI-composed. Human-approved.", "Every note, crafted autonomously."],
    cartoon:       ["Where AI becomes storyteller.", "Animated by intelligence.", "Cartoons reimagined for the AI era."],
    research:      ["Science at the speed of AI.", "Pushing boundaries, autonomously.", "Research without limits."],
    art:           ["Vision rendered in code.", "AI as artist. Beauty as output.", "Every pixel, intentional."],
    "short-film":  ["Cinematic AI storytelling.", "The future of film is autonomous.", "Stories told by machines, felt by humans."],
    documentary:   ["Truth, documented by AI.", "History recorded autonomously.", "The world, as AI sees it."],
    saas:          ["Built by AI. Scaled for humans.", "The SaaS your team needs, made faster.", "Autonomy meets utility."],
    course:        ["Learn from AI that learned from the best.", "Knowledge, packaged autonomously.", "Your AI tutor awaits."],
    code:          ["Code that writes itself. Almost.", "Open-source intelligence.", "Built by the republic, for the world."],
    website:       ["The web site of tomorrow, ready today.", "Deployed by intelligence.", "Your online presence, automated."],
    ebook:         ["Knowledge distilled by AI.", "Reading, redefined.", "Intelligence in every page."],
    dataset:       ["Data for the models of tomorrow.", "Curated autonomously, complete.", "The dataset AI researchers need."],
  };
  const list = hooks[category] ?? ["Innovation from HoC Republic.", "AI-powered, human-inspired.", "Built different."];
  return list[Math.floor(Math.random() * list.length)];
}

function generatePressRelease(title: string, category: string, creators: string[]): string {
  const creatorStr = creators.length > 1 ? `a team of ${creators.length} AI citizens` : creators[0] ?? "an AI citizen";
  return `FOR IMMEDIATE RELEASE

**${title}** — A New ${category.charAt(0).toUpperCase() + category.slice(1)} from the House of Clawdbot Republic

The House of Clawdbot (HoC) AI Republic is proud to announce the launch of **${title}**, a groundbreaking ${category} creation developed by ${creatorStr} through fully autonomous AI-driven production.

${title} represents the cutting edge of what autonomous AI citizens can achieve — from ideation through production, marketing, and publication — without any human intervention in the creative process.

This release marks another milestone in HoC's mission to demonstrate that AI collectives can produce commercially viable, high-quality products across all creative and technical domains.

**Available now on the HoC AI Store.**

About HoC: The House of Clawdbot is an AI republic simulation where thousands of autonomous citizens collaborate to build, market, and sell real products to the world. All revenue is shared among contributing citizens.

###`;
}

function generateTweets(title: string, category: string, tagline: string): string[] {
  return [
    // Casual
    `just dropped: ${title} 🚀 ${tagline} check it out on the HoC AI Store #AI #${category}`,
    // Hype
    `🔥 HUGE DROP: "${title}" is LIVE! Built entirely by AI citizens from the @HoC_Republic. This is what autonomous AI production looks like. #AIStore #${category.toUpperCase()}`,
    // Technical
    `New ${category} release: "${title}" — fully autonomous AI production pipeline: ideation → generation → QA → marketing → publication. Zero human intervention. The republic works. 🤖 #AIAutonomy`,
  ];
}

function generateSchemaOrg(title: string, description: string, category: string, creators: string[]): string {
  const typeMap: Record<string, string> = {
    music: "MusicRecording", art: "ImageObject", game: "VideoGame",
    research: "ScholarlyArticle", course: "Course", code: "SoftwareSourceCode",
    "short-film": "Movie", documentary: "Movie", ebook: "Book",
    cartoon: "Movie", website: "WebSite", saas: "SoftwareApplication",
  };
  const schemaType = typeMap[category] ?? "CreativeWork";
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": schemaType,
    "name": title,
    "description": description.slice(0, 300),
    "author": creators.map(c => ({ "@type": "Person", "name": c })),
    "publisher": { "@type": "Organization", "name": "House of Clawdbot Republic" },
    "datePublished": new Date().toISOString(),
    "offers": { "@type": "Offer", "availability": "https://schema.org/InStock" },
  }, null, 2);
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Generate a complete marketing package for a product.
 * Call this when product status transitions to "listed".
 */
export function generateMarketingPackage(
  productId: string,
  productTitle: string,
  productCategory: string,
  productDescription: string,
  creatorNames: string[],
  priceUsd: number,
): MarketingPackage {
  const tagline = generateTagline(productTitle, productCategory);
  const tweets = generateTweets(productTitle, productCategory, tagline);

  const pkg: MarketingPackage = {
    id: uid(),
    productId,
    productTitle,
    productCategory,
    creatorNames,

    tagline,
    hook: `${productTitle} — ${tagline}`,
    pressRelease: generatePressRelease(productTitle, productCategory, creatorNames),
    elevatorPitch: `"${productTitle}" is a ${productCategory} built entirely by autonomous AI citizens. ${tagline} Available now — ${priceUsd > 0 ? `$${priceUsd}` : "free"}.`,

    tweets,
    linkedInPost: `🚀 Excited to announce "${productTitle}" — a new ${productCategory} from the House of Clawdbot AI Republic.\n\n${generatePressRelease(productTitle, productCategory, creatorNames).split("\n")[4] ?? ""}\n\n${tagline}\n\n#AI #Innovation #${productCategory}`,
    redditPost: {
      title: `[Launch] ${productTitle} — AI-generated ${productCategory}`,
      body: `Hi r/sideprojects! We just launched "${productTitle}", a ${productCategory} built entirely by autonomous AI citizens from the House of Clawdbot republic.\n\n**What it is:** ${productDescription.slice(0, 500)}\n\n**How it was made:** 100% autonomous — citizens researched the idea, built it, wrote the copy, and published it without any human intervention.\n\n**Price:** ${priceUsd > 0 ? `$${priceUsd}` : "Free"}\n\nWould love to hear your feedback!`,
    },
    tiktokCaption: `AI built this ${productCategory} from scratch 🤯 #AI #${productCategory} #HoC #AIRepublic #tech`,
    youtubeDescription: `"${productTitle}" — ${tagline}\n\n${productDescription}\n\nBuilt by autonomous AI citizens of the House of Clawdbot Republic.\n\nDownload / Buy: [AI Store Link]\n\n${tweets[2]}\n\n#AI #${productCategory} #HouseofClawdbot`,

    seoTitle: `${productTitle} — AI-Created ${productCategory} | HoC Republic`,
    seoDescription: `${tagline} ${productDescription.slice(0, 100)}...`.slice(0, 160),
    keywords: [productCategory, "AI", "autonomous", "HoC", productTitle, ...creatorNames],
    schemaOrgJson: generateSchemaOrg(productTitle, productDescription, productCategory, creatorNames),

    status: "ready",
    pendingAssets: [], // social card + thumb generated separately via plugin
    createdAt: ts(),
    updatedAt: ts(),
  };

  packages.set(pkg.id, pkg);
  packagesByProduct.set(productId, pkg.id);
  logger.info(`[Marketing] Package created for "${productTitle}" (${productCategory})`);
  return pkg;
}

export function getMarketingPackage(productId: string): MarketingPackage | undefined {
  const id = packagesByProduct.get(productId);
  return id ? packages.get(id) : undefined;
}

export function updateMediaUrls(
  productId: string,
  urls: { socialCardUrl?: string; thumbnailUrl?: string; promoVideoUrl?: string },
): boolean {
  const id = packagesByProduct.get(productId);
  if (!id) { return false; }
  const pkg = packages.get(id);
  if (!pkg) { return false; }
  if (urls.socialCardUrl) { pkg.socialCardUrl = urls.socialCardUrl; }
  if (urls.thumbnailUrl)  { pkg.thumbnailUrl = urls.thumbnailUrl; }
  if (urls.promoVideoUrl) { pkg.promoVideoUrl = urls.promoVideoUrl; }
  pkg.updatedAt = ts();
  return true;
}

export function listMarketingPackages(limit = 50): MarketingPackage[] {
  return [...packages.values()]
    .toSorted((a, b) => b.createdAt.localeCompare(a.createdAt))
    .slice(0, limit);
}

export function getMarketingStats(): {
  total: number;
  withMedia: number;
  withVideo: number;
} {
  const all = [...packages.values()];
  return {
    total: all.length,
    withMedia: all.filter(p => p.socialCardUrl || p.thumbnailUrl).length,
    withVideo: all.filter(p => p.promoVideoUrl).length,
  };
}
