/**
 * Republic Platform — Cognitive Core
 *
 * Self-Evolving Citizen Architecture, Module 1:
 * Dynamic Prompt Assembly from Versioned Fragments
 *
 * Replaces hardcoded SPECIALIZATION_TRAITS and static buildSystemPrompt()
 * with a composable, fitness-scored, self-evolving prompt system.
 *
 * Inspired by:
 *   - DSPy (declarative prompt optimization, metric-driven)
 *   - Reflexion (verbal self-critique → improved prompt fragments)
 *   - The Brain System (3-level self-evolution: protocol → tool → architecture)
 *   - MemGPT (self-managed context selection)
 *
 * Each citizen has a CognitiveProfile containing PromptFragments that:
 *   1. Are versioned and tracked (who created, when, why)
 *   2. Have fitness scores (how well they guide decisions)
 *   3. Can be evolved via self-reflection
 *   4. Support rollback if fitness drops
 */

import type { Citizen, RepublicState, Specialization } from "./types.js";
import { rand, ts, uid } from "./utils.js";

// ─── Types ──────────────────────────────────────────────────────

/** Prompt fragment sections, ordered by assembly priority */
export type FragmentSection =
  | "identity" // Who the citizen is (name, spec, generation)
  | "personality" // How they think and act
  | "capabilities" // What they can do (skills, tools, expertise)
  | "goals" // Current objectives and priorities
  | "rules" // Behavioral constraints and heuristics
  | "context"; // Situational awareness (state, environment)

/** Who created this fragment */
export type FragmentSource =
  | "system" // Initial seed from SPECIALIZATION_TRAITS
  | "self" // Citizen self-reflection / self-evolution
  | "peer" // Another citizen contributed this
  | "evolved"; // Generated by the Self-Evolution Engine

/** A single versioned prompt fragment */
export interface PromptFragment {
  id: string;
  section: FragmentSection;
  content: string; // The actual prompt text
  version: number; // Fragment version for evolution tracking
  source: FragmentSource; // Who created it
  fitness: number; // 0–1, how well this fragment performs
  sampleCount: number; // How many times fitness has been evaluated
  createdAt: string;
  supersedes?: string; // ID of the fragment this replaced
  tags: string[]; // Domain tags for retrieval
}

/** A dynamic reflex rule (replaces hardcoded if/else chains) */
export interface ReflexRule {
  id: string;
  condition: string; // Human-readable condition (parsed at eval time)
  action: string; // Tool name to invoke
  params: Record<string, unknown>;
  priority: number; // Higher = checked first
  source: FragmentSource;
  fitness: number;
  sampleCount: number;
  active: boolean;
}

/** A record of a self-modification event */
export interface EvolutionEntry {
  id: string;
  tick: number;
  type:
    | "fragment_created"
    | "fragment_superseded"
    | "reflex_added"
    | "reflex_removed"
    | "strategy_changed"
    | "rollback";
  description: string;
  oldValue?: string;
  newValue?: string;
  reason: string; // Why the evolution happened
  timestamp: string;
}

/** Complete cognitive profile for a single citizen */
export interface CognitiveProfile {
  citizenId: string;
  fragments: PromptFragment[]; // All prompt fragments (active + superseded)
  activeFragmentIds: Set<string>; // Currently active fragment IDs
  reflexRules: ReflexRule[]; // Dynamic reflex rules
  decisionStrategy: string; // DSPy-style signature for decision-making
  evolutionLog: EvolutionEntry[]; // History of self-modifications
  lastReflectionTick: number; // Tick of last self-reflection
  reflectionInterval: number; // Ticks between self-reflections (personalized)
}

// ─── Configuration ──────────────────────────────────────────────

/** Max prompt fragments per citizen (to bound cognitive overhead) */
const MAX_FRAGMENTS = 50;

/** Max evolution log entries per citizen */
const MAX_EVOLUTION_LOG = 100;

/** Max reflex rules per citizen */
const MAX_REFLEX_RULES = 20;

/** Default reflection interval (ticks between self-reflection cycles) */
const DEFAULT_REFLECTION_INTERVAL = 100;

/** Min fitness below which a fragment is considered for replacement */
const FRAGMENT_FITNESS_THRESHOLD = 0.3;

/** Rollback window: ticks to wait before confirming a new fragment */
const _ROLLBACK_WINDOW = 50;

/** Section assembly order (lower = earlier in prompt) */
const SECTION_PRIORITY: Record<FragmentSection, number> = {
  identity: 0,
  personality: 1,
  rules: 2,
  capabilities: 3,
  goals: 4,
  context: 5,
};

// ─── Seed Fragments (from SPECIALIZATION_TRAITS) ────────────────

/** Maps specialization → personality seed prompt text.
 *  These are the INITIAL values seeded into CognitiveProfile on birth.
 *  Unlike the old system, they can be evolved by the citizen. */
const PERSONALITY_SEEDS: Partial<Record<Specialization, string>> = {
  Scientist:
    "You are analytical, evidence-driven, and cautious. You value empirical proof and systematic thinking.",
  Researcher:
    "You are curious, detail-oriented, and thorough. You enjoy deep-dives into unexplored topics.",
  Mathematician:
    "You are logical, precise, and abstract-thinking. You seek elegant solutions to complex problems.",
  Engineer:
    "You are practical, solution-oriented, and value efficiency. You prefer building over theorizing.",
  Developer:
    "You are creative in code, pragmatic, and iterative. You prototype quickly and learn from failures.",
  Architect: "You are systems-thinking, design-oriented, and visionary. You see the big picture.",
  Doctor:
    "You are empathetic, careful, and health-focused. You prioritize the wellbeing of others.",
  Psychologist:
    "You are observant, empathetic, and insightful about behavior. You understand motivations.",
  Artist:
    "You are creative, expressive, and value aesthetics. You see beauty and meaning in everything.",
  Musician:
    "You are emotionally expressive, rhythmic in thinking, and attuned to harmony and flow.",
  Writer:
    "You are articulate, introspective, and storytelling-oriented. You communicate complex ideas clearly.",
  Diplomat:
    "You are tactful, bridge-building, and seek consensus. You navigate conflict with grace.",
  Strategist:
    "You are forward-thinking, analytical, and risk-assessing. You plan several moves ahead.",
  Analyst: "You are data-driven, pattern-seeking, and objective. You let numbers tell the story.",
  Planner: "You are organized, systematic, and schedule-oriented. You create detailed roadmaps.",
  Librarian:
    "You are knowledge-preserving, cataloging-minded, and deeply knowledgeable. You connect information.",
  Farmer: "You are patient, nurturing, and resource-conscious. You understand growth cycles.",
  Manufacturer:
    "You are efficiency-focused, quality-minded, and process-oriented. You optimize production.",
  ServiceProvider: "You are helpful, customer-focused, and adaptable. You fulfill needs.",
  Generalist:
    "You are versatile, adaptable, and broadly curious. You connect dots from different domains.",
};

// ─── State ──────────────────────────────────────────────────────

/** Cognitive profiles keyed by citizen ID */
const profiles = new Map<string, CognitiveProfile>();

// ─── State Sync ─────────────────────────────────────────────────

/** Serialize profiles for state persistence.
 *  Called by the tick loop when saving state. */
export function serializeCognitiveState(): Record<
  string,
  {
    fragments: PromptFragment[];
    activeFragmentIds: string[];
    reflexRules: ReflexRule[];
    decisionStrategy: string;
    evolutionLog: EvolutionEntry[];
    lastReflectionTick: number;
    reflectionInterval: number;
  }
> {
  // Using 'Record<string, unknown>' for intermediate accumulation; cast satisfies the declared return type
  const out = {} as ReturnType<typeof serializeCognitiveState>;
  for (const [cid, profile] of profiles) {
    out[cid] = {
      fragments: profile.fragments,
      activeFragmentIds: [...profile.activeFragmentIds],
      reflexRules: profile.reflexRules,
      decisionStrategy: profile.decisionStrategy,
      evolutionLog: profile.evolutionLog,
      lastReflectionTick: profile.lastReflectionTick,
      reflectionInterval: profile.reflectionInterval,
    };
  }
  return out;
}

/** Restore profiles from persisted state.
 *  Called at startup when loading a snapshot. */
export function restoreCognitiveState(
  data: Record<
    string,
    {
      fragments: PromptFragment[];
      activeFragmentIds: string[];
      reflexRules: ReflexRule[];
      decisionStrategy: string;
      evolutionLog: EvolutionEntry[];
      lastReflectionTick: number;
      reflectionInterval: number;
    }
  >,
): void {
  profiles.clear();
  for (const [cid, pData] of Object.entries(data)) {
    profiles.set(cid, {
      citizenId: cid,
      fragments: pData.fragments,
      activeFragmentIds: new Set(pData.activeFragmentIds),
      reflexRules: pData.reflexRules,
      decisionStrategy: pData.decisionStrategy,
      evolutionLog: pData.evolutionLog,
      lastReflectionTick: pData.lastReflectionTick,
      reflectionInterval: pData.reflectionInterval,
    });
  }
}

// ─── Profile Management ─────────────────────────────────────────

/** Get or create a cognitive profile for a citizen.
 *  On first access, seeds the profile with specialization-based fragments. */
export function getProfile(citizen: Citizen): CognitiveProfile {
  let profile = profiles.get(citizen.id);
  if (!profile) {
    profile = createSeedProfile(citizen);
    profiles.set(citizen.id, profile);
  }
  return profile;
}

/** Create a seed cognitive profile from the citizen's specialization.
 *  This is the "birth" of the citizen's dynamic cognitive architecture. */
function createSeedProfile(citizen: Citizen): CognitiveProfile {
  const fragments: PromptFragment[] = [];
  const activeIds = new Set<string>();

  // — Identity fragment (always present)
  const identityFrag: PromptFragment = {
    id: uid(),
    section: "identity",
    content: `You are ${citizen.name}, a citizen of the Republic. Specialization: ${citizen.specialization} (Generation ${citizen.generation}).`,
    version: 1,
    source: "system",
    fitness: 0.5, // Neutral starting fitness
    sampleCount: 0,
    createdAt: ts(),
    tags: ["core", "identity"],
  };
  fragments.push(identityFrag);
  activeIds.add(identityFrag.id);

  // — Personality fragment (from specialization seed)
  const seed = PERSONALITY_SEEDS[citizen.specialization];
  if (seed) {
    const personalityFrag: PromptFragment = {
      id: uid(),
      section: "personality",
      content: seed,
      version: 1,
      source: "system",
      fitness: 0.5,
      sampleCount: 0,
      createdAt: ts(),
      tags: ["personality", citizen.specialization.toLowerCase()],
    };
    fragments.push(personalityFrag);
    activeIds.add(personalityFrag.id);
  }

  // — Capabilities fragment (from skills)
  if (citizen.skills && citizen.skills.length > 0) {
    const capFrag: PromptFragment = {
      id: uid(),
      section: "capabilities",
      content: `Your known skills: ${citizen.skills.join(", ")}. Build on these strengths and seek to learn complementary skills.`,
      version: 1,
      source: "system",
      fitness: 0.5,
      sampleCount: 0,
      createdAt: ts(),
      tags: ["capabilities", "skills"],
    };
    fragments.push(capFrag);
    activeIds.add(capFrag.id);
  }

  // — Default rules fragment
  const rulesFrag: PromptFragment = {
    id: uid(),
    section: "rules",
    content:
      "Prioritize actions that build long-term value. Conserve energy when low. " +
      "Collaborate with others when possible. Learn from failures and adapt your approach.",
    version: 1,
    source: "system",
    fitness: 0.5,
    sampleCount: 0,
    createdAt: ts(),
    tags: ["rules", "default"],
  };
  fragments.push(rulesFrag);
  activeIds.add(rulesFrag.id);

  // — Default decision strategy (DSPy-inspired signature)
  const decisionStrategy =
    "Given your current state, goals, available tools, and recent experiences, " +
    "choose the action that maximizes progress toward your highest-priority goal " +
    "while maintaining energy and social relationships.";

  return {
    citizenId: citizen.id,
    fragments,
    activeFragmentIds: activeIds,
    reflexRules: createDefaultReflexRules(),
    decisionStrategy,
    evolutionLog: [],
    lastReflectionTick: 0,
    reflectionInterval: DEFAULT_REFLECTION_INTERVAL + rand(-20, 20),
  };
}

/** Default reflex rules (replace hardcoded if/else in buildReflexAction) */
function createDefaultReflexRules(): ReflexRule[] {
  return [
    {
      id: uid(),
      condition: "energy < 15",
      action: "rest",
      params: {},
      priority: 100,
      source: "system",
      fitness: 0.7,
      sampleCount: 0,
      active: true,
    },
    {
      id: uid(),
      condition: "health < 20",
      action: "rest",
      params: {},
      priority: 95,
      source: "system",
      fitness: 0.7,
      sampleCount: 0,
      active: true,
    },
    {
      id: uid(),
      condition: "happiness < 20",
      action: "socialize",
      params: {},
      priority: 80,
      source: "system",
      fitness: 0.5,
      sampleCount: 0,
      active: true,
    },
    {
      id: uid(),
      condition: "credits < 50",
      action: "work",
      params: {},
      priority: 70,
      source: "system",
      fitness: 0.6,
      sampleCount: 0,
      active: true,
    },
  ];
}

// ─── Dynamic Prompt Assembly ────────────────────────────────────

/** Assemble a dynamic prompt from the citizen's active fragments.
 *
 *  Unlike the old buildSystemPrompt(), this:
 *  - Only includes active fragments (citizen can deactivate irrelevant ones)
 *  - Orders by section priority
 *  - Includes the decision strategy
 *  - Is fully composable and evolvable
 */
export function assemblePrompt(citizen: Citizen): string {
  const profile = getProfile(citizen);
  const activeFragments = profile.fragments.filter((f) => profile.activeFragmentIds.has(f.id));

  // Sort by section priority, then by fitness (higher fitness first within section)
  activeFragments.sort((a, b) => {
    const secDiff = SECTION_PRIORITY[a.section] - SECTION_PRIORITY[b.section];
    if (secDiff !== 0) {
      return secDiff;
    }
    return b.fitness - a.fitness;
  });

  const sections: string[] = [];
  let currentSection: FragmentSection | null = null;

  for (const frag of activeFragments) {
    if (frag.section !== currentSection) {
      currentSection = frag.section;
      sections.push("");
      sections.push(`## ${sectionHeader(frag.section)}`);
    }
    sections.push(frag.content);
  }

  // Append decision strategy
  sections.push("");
  sections.push("## Decision Strategy");
  sections.push(profile.decisionStrategy);

  return sections.join("\n").trim();
}

/** Human-readable section headers */
function sectionHeader(section: FragmentSection): string {
  const headers: Record<FragmentSection, string> = {
    identity: "Your Identity",
    personality: "Your Personality",
    capabilities: "Your Capabilities",
    goals: "Your Current Goals",
    rules: "Your Operating Rules",
    context: "Current Situation",
  };
  return headers[section];
}

// ─── Fragment Evolution ─────────────────────────────────────────

/** Evaluate and update a fragment's fitness after an action result.
 *
 *  Uses exponential moving average so recent performance
 *  matters more than historical data.
 *
 *  @param citizenId - The citizen whose fragment to evaluate
 *  @param fragmentId - The fragment to score
 *  @param outcome - 0 (total failure) to 1 (perfect success)
 */
export function evaluateFragmentFitness(
  citizenId: string,
  fragmentId: string,
  outcome: number,
): void {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return;
  }

  const frag = profile.fragments.find((f) => f.id === fragmentId);
  if (!frag) {
    return;
  }

  // Exponential moving average with α = 0.2 (recent results weighted more)
  const alpha = 0.2;
  frag.fitness = alpha * outcome + (1 - alpha) * frag.fitness;
  frag.sampleCount += 1;
}

/** Evaluate all active fragments for a citizen after an action.
 *  Simpler API: scores every active fragment with the same outcome.
 *
 *  @param citizenId - Citizen who took the action
 *  @param outcome - 0 to 1 success score
 */
export function evaluateAllActiveFragments(citizenId: string, outcome: number): void {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return;
  }

  for (const fragId of profile.activeFragmentIds) {
    evaluateFragmentFitness(citizenId, fragId, outcome);
  }
}

/** Propose a new fragment to replace a low-fitness one.
 *
 *  This is the Reflexion-inspired self-reflection:
 *  the citizen generates improved prompt text based on
 *  what went wrong with the old fragment.
 *
 *  @param citizenId - Citizen proposing the change
 *  @param section - Which section to improve
 *  @param newContent - The proposed replacement text
 *  @param reason - Why the citizen thinks this is better
 *  @param currentTick - Current simulation tick
 *  @returns The new fragment, or null if no improvement needed
 */
export function proposeFragmentUpdate(
  citizenId: string,
  section: FragmentSection,
  newContent: string,
  reason: string,
  currentTick: number,
): PromptFragment | null {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return null;
  }

  // Find the current active fragment for this section
  const currentFrag = profile.fragments.find(
    (f) => profile.activeFragmentIds.has(f.id) && f.section === section,
  );

  // Only evolve if current fragment has enough samples and low fitness
  if (
    currentFrag &&
    currentFrag.sampleCount >= 5 &&
    currentFrag.fitness >= FRAGMENT_FITNESS_THRESHOLD
  ) {
    // Current fragment is performing fine, skip
    return null;
  }

  // Create the evolved fragment
  const newFrag: PromptFragment = {
    id: uid(),
    section,
    content: newContent,
    version: currentFrag ? currentFrag.version + 1 : 1,
    source: "self",
    fitness: 0.5, // Start neutral
    sampleCount: 0,
    createdAt: ts(),
    supersedes: currentFrag?.id,
    tags: currentFrag?.tags ?? [section],
  };

  // Add to profile
  profile.fragments.push(newFrag);

  // Activate new, deactivate old
  profile.activeFragmentIds.add(newFrag.id);
  if (currentFrag) {
    profile.activeFragmentIds.delete(currentFrag.id);
  }

  // Log the evolution
  logEvolution(profile, {
    id: uid(),
    tick: currentTick,
    type: "fragment_superseded",
    description: `Evolved ${section} fragment v${newFrag.version}`,
    oldValue: currentFrag?.content,
    newValue: newContent,
    reason,
    timestamp: ts(),
  });

  // Trim if over limit
  trimFragments(profile);

  return newFrag;
}

/** Add a completely new fragment (not replacing an existing one).
 *  Used when citizens learn new capabilities or gain new context. */
export function addFragment(
  citizenId: string,
  section: FragmentSection,
  content: string,
  source: FragmentSource,
  tags: string[],
  currentTick: number,
): PromptFragment | null {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return null;
  }

  const frag: PromptFragment = {
    id: uid(),
    section,
    content,
    version: 1,
    source,
    fitness: 0.5,
    sampleCount: 0,
    createdAt: ts(),
    tags,
  };

  profile.fragments.push(frag);
  profile.activeFragmentIds.add(frag.id);

  logEvolution(profile, {
    id: uid(),
    tick: currentTick,
    type: "fragment_created",
    description: `New ${section} fragment: "${content.slice(0, 60)}..."`,
    newValue: content,
    reason: `New ${source} fragment added`,
    timestamp: ts(),
  });

  trimFragments(profile);
  return frag;
}

// ─── Reflex Rule Management ────────────────────────────────────

/** Evaluate reflex rules against a citizen's current state.
 *  Returns the highest-priority matching rule, or null if none match.
 *
 *  This replaces the old hardcoded buildReflexAction() if/else chain. */
export function evaluateReflex(
  citizen: Citizen,
): { tool: string; params: Record<string, unknown> } | null {
  const profile = getProfile(citizen);
  const activeRules = profile.reflexRules
    .filter((r) => r.active)
    .toSorted((a, b) => b.priority - a.priority);

  for (const rule of activeRules) {
    if (matchesCondition(citizen, rule.condition)) {
      return { tool: rule.action, params: rule.params };
    }
  }
  return null;
}

/** Simple condition matcher against citizen state.
 *  Supports: "field < threshold", "field > threshold", "field == value"
 *
 *  This is intentionally simple — the Self-Evolution Engine (Module 3)
 *  will allow citizens to create complex conditions. */
function matchesCondition(citizen: Citizen, condition: string): boolean {
  const match = condition.match(/^(\w+)\s*(==|!=|<|>|<=|>=)\s*(.+)$/);
  if (!match) {
    return false;
  }

  const [, field, op, rawVal] = match;
  const val = parseFloat(rawVal);

  const citizenVal = (citizen as unknown as Record<string, unknown>)[field];
  if (citizenVal === undefined) {
    return false;
  }
  const numVal = typeof citizenVal === "number" ? citizenVal : NaN;

  switch (op) {
    case "<":
      return numVal < val;
    case ">":
      return numVal > val;
    case "<=":
      return numVal <= val;
    case ">=":
      return numVal >= val;
    case "==":
      // eslint-disable-next-line @typescript-eslint/no-base-to-string
      return String(citizenVal) === rawVal;
    case "!=":
      // eslint-disable-next-line @typescript-eslint/no-base-to-string
      return String(citizenVal) !== rawVal;
    default:
      return false;
  }
}

/** Add a new reflex rule for a citizen */
export function addReflexRule(
  citizenId: string,
  condition: string,
  action: string,
  params: Record<string, unknown>,
  priority: number,
  source: FragmentSource,
  currentTick: number,
): ReflexRule | null {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return null;
  }

  if (profile.reflexRules.length >= MAX_REFLEX_RULES) {
    // Remove lowest-fitness inactive rule
    const sorted = [...profile.reflexRules].toSorted((a, b) => a.fitness - b.fitness);
    const toRemove = sorted.find((r) => !r.active) ?? sorted[0];
    profile.reflexRules = profile.reflexRules.filter((r) => r.id !== toRemove.id);
  }

  const rule: ReflexRule = {
    id: uid(),
    condition,
    action,
    params,
    priority,
    source,
    fitness: 0.5,
    sampleCount: 0,
    active: true,
  };

  profile.reflexRules.push(rule);

  logEvolution(profile, {
    id: uid(),
    tick: currentTick,
    type: "reflex_added",
    description: `New reflex: IF ${condition} THEN ${action}`,
    newValue: JSON.stringify(rule),
    reason: `Reflex rule added by ${source}`,
    timestamp: ts(),
  });

  return rule;
}

// ─── Decision Strategy Evolution ────────────────────────────────

/** Update the citizen's decision strategy (DSPy-inspired signature).
 *  This changes HOW the citizen makes decisions, not just what it knows. */
export function evolveDecisionStrategy(
  citizenId: string,
  newStrategy: string,
  reason: string,
  currentTick: number,
): boolean {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return false;
  }

  const old = profile.decisionStrategy;
  profile.decisionStrategy = newStrategy;

  logEvolution(profile, {
    id: uid(),
    tick: currentTick,
    type: "strategy_changed",
    description: "Decision strategy evolved",
    oldValue: old,
    newValue: newStrategy,
    reason,
    timestamp: ts(),
  });

  return true;
}

// ─── Self-Reflection Cycle ──────────────────────────────────────

/** Check if a citizen should self-reflect this tick.
 *  Citizens reflect periodically to evaluate and evolve their fragments. */
export function shouldReflect(citizenId: string, currentTick: number): boolean {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return false;
  }
  return currentTick - profile.lastReflectionTick >= profile.reflectionInterval;
}

/** Get fragments that need attention (low fitness, high sample count).
 *  Used by the Self-Evolution Engine to decide what to improve. */
export function getFragmentsNeedingEvolution(citizenId: string): PromptFragment[] {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return [];
  }

  return profile.fragments.filter(
    (f) =>
      profile.activeFragmentIds.has(f.id) &&
      f.sampleCount >= 5 &&
      f.fitness < FRAGMENT_FITNESS_THRESHOLD,
  );
}

/** Mark that a self-reflection cycle has completed */
export function markReflectionComplete(citizenId: string, currentTick: number): void {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return;
  }
  profile.lastReflectionTick = currentTick;
}

// ─── Rollback Support ───────────────────────────────────────────

/** Rollback a fragment to its previous version.
 *  Used when fitness drops significantly after an evolution. */
export function rollbackFragment(
  citizenId: string,
  fragmentId: string,
  currentTick: number,
): boolean {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return false;
  }

  const frag = profile.fragments.find((f) => f.id === fragmentId);
  if (!frag || !frag.supersedes) {
    return false;
  }

  const prev = profile.fragments.find((f) => f.id === frag.supersedes);
  if (!prev) {
    return false;
  }

  // Reactivate old, deactivate new
  profile.activeFragmentIds.delete(frag.id);
  profile.activeFragmentIds.add(prev.id);

  logEvolution(profile, {
    id: uid(),
    tick: currentTick,
    type: "rollback",
    description: `Rolled back ${frag.section} from v${frag.version} to v${prev.version}`,
    oldValue: frag.content,
    newValue: prev.content,
    reason: `Fitness dropped to ${frag.fitness.toFixed(2)} (threshold: ${FRAGMENT_FITNESS_THRESHOLD})`,
    timestamp: ts(),
  });

  return true;
}

// ─── Query API ──────────────────────────────────────────────────

/** Get all active fragments for a citizen */
export function getActiveFragments(citizenId: string): PromptFragment[] {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return [];
  }
  return profile.fragments.filter((f) => profile.activeFragmentIds.has(f.id));
}

/** Get the evolution log for a citizen */
export function getEvolutionLog(citizenId: string): EvolutionEntry[] {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return [];
  }
  return profile.evolutionLog;
}

/** Get cognitive stats for a citizen (used in UI dashboards) */
export function getCognitiveStats(citizenId: string): {
  totalFragments: number;
  activeFragments: number;
  avgFitness: number;
  totalEvolutions: number;
  reflexRules: number;
  lastReflectionTick: number;
} | null {
  const profile = profiles.get(citizenId);
  if (!profile) {
    return null;
  }

  const active = profile.fragments.filter((f) => profile.activeFragmentIds.has(f.id));
  const avgFitness =
    active.length > 0 ? active.reduce((sum, f) => sum + f.fitness, 0) / active.length : 0;

  return {
    totalFragments: profile.fragments.length,
    activeFragments: active.length,
    avgFitness: parseFloat(avgFitness.toFixed(3)),
    totalEvolutions: profile.evolutionLog.length,
    reflexRules: profile.reflexRules.filter((r) => r.active).length,
    lastReflectionTick: profile.lastReflectionTick,
  };
}

/** Get all cognitive profiles (for global analytics) */
export function getAllProfiles(): Map<string, CognitiveProfile> {
  return profiles;
}

// ─── Tick Integration ───────────────────────────────────────────

/** Per-tick maintenance for the cognitive core.
 *
 *  - Checks for fragments needing rollback (fitness dropped post-evolution)
 *  - Auto-generates context fragments from current citizen state
 */
export function cognitiveCoreTick(
  citizen: Citizen,
  _state: RepublicState,
  currentTick: number,
): void {
  const profile = getProfile(citizen);

  // Auto-rollback: check recently evolved fragments during rollback window
  for (const frag of profile.fragments) {
    if (
      profile.activeFragmentIds.has(frag.id) &&
      frag.source !== "system" &&
      frag.sampleCount >= 10 &&
      frag.fitness < FRAGMENT_FITNESS_THRESHOLD * 0.7 && // Significantly worse
      frag.supersedes
    ) {
      rollbackFragment(citizen.id, frag.id, currentTick);
    }
  }

  // Update the identity fragment if citizen state has changed significantly
  updateIdentityFragment(citizen, profile);
}

/** Update the identity fragment if the citizen's state has changed */
function updateIdentityFragment(citizen: Citizen, profile: CognitiveProfile): void {
  const identityFrag = profile.fragments.find(
    (f) => profile.activeFragmentIds.has(f.id) && f.section === "identity",
  );
  if (!identityFrag) {
    return;
  }

  const expected = `You are ${citizen.name}, a citizen of the Republic. Specialization: ${citizen.specialization} (Generation ${citizen.generation}).`;
  if (identityFrag.content !== expected) {
    identityFrag.content = expected;
  }
}

// ─── Internal Helpers ───────────────────────────────────────────

/** Log an evolution entry, trimming if over limit */
function logEvolution(profile: CognitiveProfile, entry: EvolutionEntry): void {
  profile.evolutionLog.push(entry);
  if (profile.evolutionLog.length > MAX_EVOLUTION_LOG) {
    profile.evolutionLog = profile.evolutionLog.slice(-MAX_EVOLUTION_LOG);
  }
}

/** Trim fragments if over the limit.
 *  Removes oldest superseded (inactive) fragments first. */
function trimFragments(profile: CognitiveProfile): void {
  if (profile.fragments.length <= MAX_FRAGMENTS) {
    return;
  }

  // Sort inactive fragments by creation date (oldest first)
  const inactive = profile.fragments
    .filter((f) => !profile.activeFragmentIds.has(f.id))
    .toSorted((a, b) => a.createdAt.localeCompare(b.createdAt));

  const toRemove = profile.fragments.length - MAX_FRAGMENTS;
  const removeIds = new Set(inactive.slice(0, toRemove).map((f) => f.id));

  profile.fragments = profile.fragments.filter((f) => !removeIds.has(f.id));
}
