/**
 * Republic Platform — Document Generator
 *
 * Citizens can produce professional documents in multiple formats:
 * - PDF  — reports, invoices, contracts, documentation
 * - PPTX — slide decks, presentations, pitch decks
 * - XLSX — spreadsheets, data exports, financial models
 * - MD   — Markdown documentation, README files
 *
 * Uses JSON-based document specifications that can be generated by
 * LLMs. Actual rendering uses optional dependencies (pdfkit, officegen)
 * with graceful text-only fallback when not installed.
 */

import { ts, uid } from "./utils.js";

// ─── Types ──────────────────────────────────────────────────────

export type DocumentFormat = "pdf" | "pptx" | "xlsx" | "md" | "html" | "csv";

export interface DocumentSpec {
  title: string;
  format: DocumentFormat;
  author?: string;
  sections: DocumentSection[];
  metadata?: Record<string, string>;
  styling?: DocumentStyling;
}

export interface DocumentSection {
  heading?: string;
  content: string;
  type: "text" | "table" | "chart" | "image" | "code" | "list";
  data?: unknown;
}

export interface DocumentStyling {
  font?: string;
  fontSize?: number;
  primaryColor?: string;
  accentColor?: string;
  headerStyle?: "minimal" | "corporate" | "creative";
  margins?: { top: number; right: number; bottom: number; left: number };
}

export interface GeneratedDocument {
  id: string;
  title: string;
  format: DocumentFormat;
  author: string;
  sizeBytes: number;
  pageCount: number;
  filePath: string;
  content: string;
  createdAt: string;
  citizenId: string;
}

export interface SlideSpec {
  title: string;
  bullets: string[];
  notes?: string;
  layout: "title" | "content" | "two-column" | "image" | "blank";
  imageBase64?: string;
}

export interface PresentationSpec {
  title: string;
  subtitle?: string;
  author?: string;
  theme: "dark" | "light" | "corporate" | "creative";
  slides: SlideSpec[];
}

export interface SpreadsheetSpec {
  title: string;
  sheets: SheetSpec[];
}

export interface SheetSpec {
  name: string;
  headers: string[];
  rows: (string | number | boolean)[][];
  columnWidths?: number[];
  formulas?: { cell: string; formula: string }[];
}

export interface InvoiceSpec {
  invoiceNumber: string;
  from: { name: string; address: string; email: string };
  to: { name: string; address: string; email: string };
  items: { description: string; quantity: number; unitPrice: number }[];
  currency: string;
  tax?: number;
  notes?: string;
  dueDate?: string;
}

// ─── State ──────────────────────────────────────────────────────

const generatedDocuments: GeneratedDocument[] = [];
const MAX_DOC_HISTORY = 100;

// ─── PDF Generation ─────────────────────────────────────────────

/**
 * Generate a PDF document from a specification.
 */
export async function generatePDF(
  spec: DocumentSpec,
  savePath: string,
  citizenId = "system",
): Promise<GeneratedDocument> {
  const { writeFile } = await import("node:fs/promises");

  // Build text-based PDF content (uses pdfkit when available)
  const content = renderDocumentToText(spec);

  // Try to use pdfkit for real PDF output
  try {
    const pdfContent = await renderWithPdfKit(spec);
    await writeFile(savePath, pdfContent);

    const doc = createDocRecord(
      spec.title,
      "pdf",
      spec.author ?? "Republic",
      pdfContent.length,
      spec.sections.length,
      savePath,
      content,
      citizenId,
    );
    archiveDoc(doc);
    return doc;
  } catch {
    // Fallback: write as plain text with .pdf extension
    const textBuffer = Buffer.from(content, "utf-8");
    await writeFile(savePath, textBuffer);

    const doc = createDocRecord(
      spec.title,
      "pdf",
      spec.author ?? "Republic",
      textBuffer.length,
      spec.sections.length,
      savePath,
      content,
      citizenId,
    );
    archiveDoc(doc);
    return doc;
  }
}

/**
 * Generate a professional invoice as PDF.
 */
export async function generateInvoice(
  invoice: InvoiceSpec,
  savePath: string,
  citizenId = "system",
): Promise<GeneratedDocument> {
  const subtotal = invoice.items.reduce((s, i) => s + i.quantity * i.unitPrice, 0);
  const tax = invoice.tax ? subtotal * invoice.tax : 0;
  const total = subtotal + tax;

  const sections: DocumentSection[] = [
    {
      heading: `Invoice #${invoice.invoiceNumber}`,
      content: `From: ${invoice.from.name}\n${invoice.from.address}\n${invoice.from.email}`,
      type: "text",
    },
    {
      heading: "Bill To",
      content: `${invoice.to.name}\n${invoice.to.address}\n${invoice.to.email}`,
      type: "text",
    },
    {
      heading: "Items",
      content: invoice.items
        .map(
          (i) => `${i.description}: ${i.quantity} × ${invoice.currency}${i.unitPrice.toFixed(2)}`,
        )
        .join("\n"),
      type: "table",
      data: invoice.items,
    },
    {
      heading: "Total",
      content: [
        `Subtotal: ${invoice.currency}${subtotal.toFixed(2)}`,
        invoice.tax
          ? `Tax (${(invoice.tax * 100).toFixed(0)}%): ${invoice.currency}${tax.toFixed(2)}`
          : null,
        `Total: ${invoice.currency}${total.toFixed(2)}`,
        invoice.dueDate ? `Due: ${invoice.dueDate}` : null,
      ]
        .filter(Boolean)
        .join("\n"),
      type: "text",
    },
  ];

  if (invoice.notes) {
    sections.push({ heading: "Notes", content: invoice.notes, type: "text" });
  }

  const spec: DocumentSpec = {
    title: `Invoice ${invoice.invoiceNumber}`,
    format: "pdf",
    author: invoice.from.name,
    sections,
  };

  return generatePDF(spec, savePath, citizenId);
}

// ─── Presentation Generation ────────────────────────────────────

/**
 * Generate a PPTX presentation.
 */
export async function generatePresentation(
  spec: PresentationSpec,
  savePath: string,
  citizenId = "system",
): Promise<GeneratedDocument> {
  const { writeFile } = await import("node:fs/promises");

  // Build markdown-like text representation
  const content = renderPresentationToText(spec);

  // Try officegen for real PPTX
  try {
    const pptxBuffer = await renderWithOfficegen("pptx", spec);
    await writeFile(savePath, pptxBuffer);

    const doc = createDocRecord(
      spec.title,
      "pptx",
      spec.author ?? "Republic",
      pptxBuffer.length,
      spec.slides.length,
      savePath,
      content,
      citizenId,
    );
    archiveDoc(doc);
    return doc;
  } catch {
    // Fallback: write as markdown
    const textBuffer = Buffer.from(content, "utf-8");
    await writeFile(savePath, textBuffer);

    const doc = createDocRecord(
      spec.title,
      "pptx",
      spec.author ?? "Republic",
      textBuffer.length,
      spec.slides.length,
      savePath,
      content,
      citizenId,
    );
    archiveDoc(doc);
    return doc;
  }
}

// ─── Spreadsheet Generation ─────────────────────────────────────

/**
 * Generate an XLSX spreadsheet.
 */
export async function generateSpreadsheet(
  spec: SpreadsheetSpec,
  savePath: string,
  citizenId = "system",
): Promise<GeneratedDocument> {
  const { writeFile } = await import("node:fs/promises");

  const content = renderSpreadsheetToText(spec);

  // Try officegen for real XLSX
  try {
    const xlsxBuffer = await renderWithOfficegen("xlsx", spec);
    await writeFile(savePath, xlsxBuffer);

    const doc = createDocRecord(
      spec.title,
      "xlsx",
      "",
      xlsxBuffer.length,
      spec.sheets.length,
      savePath,
      content,
      citizenId,
    );
    archiveDoc(doc);
    return doc;
  } catch {
    // Fallback: write as CSV
    const csvContent = renderSpreadsheetToCSV(spec);
    const csvBuffer = Buffer.from(csvContent, "utf-8");
    await writeFile(savePath.replace(/\.xlsx$/, ".csv"), csvBuffer);

    const doc = createDocRecord(
      spec.title,
      "csv",
      "",
      csvBuffer.length,
      spec.sheets.length,
      savePath,
      csvContent,
      citizenId,
    );
    archiveDoc(doc);
    return doc;
  }
}

// ─── Markdown & HTML Generation ─────────────────────────────────

/**
 * Generate a Markdown document.
 */
export async function generateMarkdown(
  spec: DocumentSpec,
  savePath: string,
  citizenId = "system",
): Promise<GeneratedDocument> {
  const { writeFile } = await import("node:fs/promises");

  const content = renderDocumentToMarkdown(spec);
  const buffer = Buffer.from(content, "utf-8");
  await writeFile(savePath, buffer);

  const doc = createDocRecord(
    spec.title,
    "md",
    spec.author ?? "Republic",
    buffer.length,
    spec.sections.length,
    savePath,
    content,
    citizenId,
  );
  archiveDoc(doc);
  return doc;
}

/**
 * Generate an HTML document with embedded styles.
 */
export async function generateHTML(
  spec: DocumentSpec,
  savePath: string,
  citizenId = "system",
): Promise<GeneratedDocument> {
  const { writeFile } = await import("node:fs/promises");

  const content = renderDocumentToHTML(spec);
  const buffer = Buffer.from(content, "utf-8");
  await writeFile(savePath, buffer);

  const doc = createDocRecord(
    spec.title,
    "html",
    spec.author ?? "Republic",
    buffer.length,
    spec.sections.length,
    savePath,
    content,
    citizenId,
  );
  archiveDoc(doc);
  return doc;
}

// ─── Renderers ──────────────────────────────────────────────────

function renderDocumentToText(spec: DocumentSpec): string {
  const lines: string[] = [];
  lines.push("=".repeat(60));
  lines.push(`  ${spec.title}`);
  if (spec.author) {
    lines.push(`  By ${spec.author}`);
  }
  lines.push("=".repeat(60));
  lines.push("");

  for (const section of spec.sections) {
    if (section.heading) {
      lines.push(`--- ${section.heading} ---`);
    }
    lines.push(section.content);
    lines.push("");
  }

  return lines.join("\n");
}

function renderDocumentToMarkdown(spec: DocumentSpec): string {
  const lines: string[] = [];
  lines.push(`# ${spec.title}`);
  if (spec.author) {
    lines.push(`*By ${spec.author}*`);
  }
  lines.push("");

  for (const section of spec.sections) {
    if (section.heading) {
      lines.push(`## ${section.heading}`);
      lines.push("");
    }

    if (section.type === "code") {
      lines.push("```");
      lines.push(section.content);
      lines.push("```");
    } else if (section.type === "list") {
      for (const item of section.content.split("\n")) {
        lines.push(`- ${item}`);
      }
    } else {
      lines.push(section.content);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function renderDocumentToHTML(spec: DocumentSpec): string {
  const primaryColor = spec.styling?.primaryColor ?? "#1a1a2e";
  const accentColor = spec.styling?.accentColor ?? "#e94560";
  const font = spec.styling?.font ?? "Inter, sans-serif";

  const sectionsHtml = spec.sections
    .map((s) => {
      const heading = s.heading
        ? `<h2 style="color:${accentColor}">${escapeHtml(s.heading)}</h2>`
        : "";
      const content =
        s.type === "code"
          ? `<pre><code>${escapeHtml(s.content)}</code></pre>`
          : `<p>${escapeHtml(s.content).replace(/\n/g, "<br>")}</p>`;
      return `${heading}\n${content}`;
    })
    .join("\n<hr>\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(spec.title)}</title>
  <style>
    body { font-family: ${font}; color: ${primaryColor}; max-width: 800px; margin: 2rem auto; padding: 0 1rem; line-height: 1.6; }
    h1 { border-bottom: 3px solid ${accentColor}; padding-bottom: 0.5rem; }
    h2 { color: ${accentColor}; }
    pre { background: #f4f4f4; padding: 1rem; border-radius: 4px; overflow-x: auto; }
    hr { border: none; border-top: 1px solid #ddd; margin: 2rem 0; }
  </style>
</head>
<body>
  <h1>${escapeHtml(spec.title)}</h1>
  ${spec.author ? `<p><em>By ${escapeHtml(spec.author)}</em></p>` : ""}
  ${sectionsHtml}
</body>
</html>`;
}

function renderPresentationToText(spec: PresentationSpec): string {
  const lines: string[] = [];
  lines.push(`# ${spec.title}`);
  if (spec.subtitle) {
    lines.push(`## ${spec.subtitle}`);
  }
  if (spec.author) {
    lines.push(`*${spec.author}*`);
  }
  lines.push("");

  for (let i = 0; i < spec.slides.length; i++) {
    const slide = spec.slides[i];
    lines.push(`--- Slide ${i + 1}: ${slide.title} ---`);
    for (const bullet of slide.bullets) {
      lines.push(`  • ${bullet}`);
    }
    if (slide.notes) {
      lines.push(`  [Notes: ${slide.notes}]`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function renderSpreadsheetToText(spec: SpreadsheetSpec): string {
  const lines: string[] = [];
  lines.push(`Workbook: ${spec.title}`);
  lines.push("");

  for (const sheet of spec.sheets) {
    lines.push(`Sheet: ${sheet.name}`);
    lines.push(sheet.headers.join("\t"));
    lines.push("-".repeat(60));
    for (const row of sheet.rows) {
      lines.push(row.map(String).join("\t"));
    }
    lines.push("");
  }

  return lines.join("\n");
}

function renderSpreadsheetToCSV(spec: SpreadsheetSpec): string {
  const lines: string[] = [];

  for (const sheet of spec.sheets) {
    lines.push(`# ${sheet.name}`);
    lines.push(sheet.headers.map(csvEscape).join(","));
    for (const row of sheet.rows) {
      lines.push(row.map((v) => csvEscape(String(v))).join(","));
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Optional Dependency Renderers ──────────────────────────────

async function renderWithPdfKit(spec: DocumentSpec): Promise<Buffer> {
  // Dynamic import to avoid hard dependency
  const moduleName = "pdfkit";
  const PDFDocument = ((await import(moduleName)) as { default: new () => PdfDocLike }).default;

  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument();

    doc.on("data", (...args: unknown[]) => {
      chunks.push(args[0] as Buffer);
    });
    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });
    doc.on("error", (...args: unknown[]) => {
      reject(args[0]);
    });

    // Title
    doc.fontSize(24).text(spec.title, { align: "center" });
    if (spec.author) {
      doc.fontSize(12).text(`By ${spec.author}`, { align: "center" });
    }
    doc.moveDown(2);

    // Sections
    for (const section of spec.sections) {
      if (section.heading) {
        doc.fontSize(16).text(section.heading);
        doc.moveDown(0.5);
      }
      doc.fontSize(11).text(section.content);
      doc.moveDown(1);
    }

    doc.end();
  });
}

async function renderWithOfficegen(
  type: "pptx" | "xlsx",
  spec: PresentationSpec | SpreadsheetSpec,
): Promise<Buffer> {
  if (type === "pptx") {
    // Try officegen for real PPTX
    const moduleName = "officegen";
    const officegen = ((await import(moduleName)) as { default: (t: string) => OfficeGenLike }).default;
    const pptx = officegen("pptx");

    const deckSpec = spec as PresentationSpec;

    // Build slides
    for (const slide of deckSpec.slides) {
      const s = pptx.makeTitleSlide(slide.title, slide.bullets.join("\n"));
      void s; // slide object returned for chaining
    }

    // Generate to buffer
    return new Promise<Buffer>((resolve, reject) => {
      const chunks: Buffer[] = [];
      const stream = pptx.generate({
        type: "nodebuffer",
        onend: (_written: unknown) => {
          void _written;
        },
      });
      if (stream && typeof stream.on === "function") {
        stream.on("data", (...args: unknown[]) => chunks.push(args[0] as Buffer));
        stream.on("end", () => resolve(Buffer.concat(chunks)));
        stream.on("error", reject);
      } else {
        reject(new Error("officegen did not return a stream"));
      }
    });
  }

  // XLSX fallback: render as CSV buffer (most tools can import CSV)
  if (type === "xlsx") {
    const sheetSpec = spec as SpreadsheetSpec;
    const csv = renderSpreadsheetToCSV(sheetSpec);
    return Buffer.from(csv, "utf-8");
  }

  throw new Error(`Unsupported officegen type: ${type}`);
}

/** Minimal officegen interface for type safety */
interface OfficeGenLike {
  makeTitleSlide(title: string, subtitle: string): unknown;
  generate(opts: Record<string, unknown>): { on(e: string, fn: (...args: unknown[]) => void): void } | null;
}

// ─── Helpers ────────────────────────────────────────────────────

interface PdfDocLike {
  on(event: string, fn: (...args: unknown[]) => void): void;
  fontSize(n: number): PdfDocLike;
  text(t: string, opts?: Record<string, unknown>): PdfDocLike;
  moveDown(n?: number): PdfDocLike;
  end(): void;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function csvEscape(val: string): string {
  if (val.includes(",") || val.includes('"') || val.includes("\n")) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}

function createDocRecord(
  title: string,
  format: DocumentFormat,
  author: string,
  sizeBytes: number,
  pageCount: number,
  filePath: string,
  content: string,
  citizenId: string,
): GeneratedDocument {
  return {
    id: uid(),
    title,
    format,
    author,
    sizeBytes,
    pageCount,
    filePath,
    content: content.slice(0, 5_000),
    createdAt: ts(),
    citizenId,
  };
}

function archiveDoc(doc: GeneratedDocument): void {
  generatedDocuments.push(doc);
  if (generatedDocuments.length > MAX_DOC_HISTORY) {
    generatedDocuments.splice(0, generatedDocuments.length - MAX_DOC_HISTORY);
  }
}

// ─── Queries ────────────────────────────────────────────────────

export function getDocumentHistory(limit = 50): GeneratedDocument[] {
  return generatedDocuments.slice(-limit);
}

export function getCitizenDocuments(citizenId: string, limit = 20): GeneratedDocument[] {
  return generatedDocuments.filter((d) => d.citizenId === citizenId).slice(-limit);
}

export function getDocumentById(docId: string): GeneratedDocument | undefined {
  return generatedDocuments.find((d) => d.id === docId);
}

// ─── Diagnostics ────────────────────────────────────────────────

export interface DocumentGeneratorDiagnostics {
  totalGenerated: number;
  formatBreakdown: Record<string, number>;
  totalSizeBytes: number;
}

export function getDocumentGeneratorDiagnostics(): DocumentGeneratorDiagnostics {
  const formatBreakdown: Record<string, number> = {};
  let totalSize = 0;

  for (const doc of generatedDocuments) {
    formatBreakdown[doc.format] = (formatBreakdown[doc.format] ?? 0) + 1;
    totalSize += doc.sizeBytes;
  }

  return {
    totalGenerated: generatedDocuments.length,
    formatBreakdown,
    totalSizeBytes: totalSize,
  };
}
