/**
 * Kali Report Generation
 *
 * Generates structured Markdown penetration test reports from scan results.
 */

import type { KaliScanResult, Finding } from "./kali-types.js";

export function generateReport(scan: KaliScanResult): string {
  const now = new Date().toISOString();
  const severity = (f: Finding[]) => ({
    critical: f.filter((x) => x.severity === "critical").length,
    high: f.filter((x) => x.severity === "high").length,
    medium: f.filter((x) => x.severity === "medium").length,
    low: f.filter((x) => x.severity === "low").length,
    info: f.filter((x) => x.severity === "info").length,
  });
  const stats = severity(scan.findings);
  const riskLevel =
    stats.critical > 0 ? "CRITICAL" : stats.high > 0 ? "HIGH" : stats.medium > 0 ? "MEDIUM" : "LOW";

  scan.summary = {
    targetInfo: scan.target,
    riskLevel,
    totalFindings: scan.findings.length,
    ...stats,
    topRisks: scan.findings
      .filter((f) => f.severity === "critical" || f.severity === "high")
      .map((f) => f.title)
      .slice(0, 5),
    recommendations: [
      ...scan.findings
        .filter((f) => f.severity === "critical")
        .map((f) => `[CRITICAL] ${f.remediation}`),
      ...scan.findings.filter((f) => f.severity === "high").map((f) => `[HIGH] ${f.remediation}`),
    ].slice(0, 10),
  };

  const sections = [
    `# Penetration Test Report`,
    ``,
    `**Target**: ${scan.target}`,
    `**Scan Type**: ${scan.scanType}`,
    `**Date**: ${now}`,
    `**Risk Level**: ${riskLevel}`,
    ``,
    `## Executive Summary`,
    ``,
    `| Severity | Count |`,
    `|----------|-------|`,
    `| Critical | ${stats.critical} |`,
    `| High     | ${stats.high} |`,
    `| Medium   | ${stats.medium} |`,
    `| Low      | ${stats.low} |`,
    `| Info     | ${stats.info} |`,
    `| **Total**| **${scan.findings.length}** |`,
    ``,
  ];

  if (scan.summary.topRisks.length > 0) {
    sections.push(`## Top Risks`, ``);
    scan.summary.topRisks.forEach((r, i) => sections.push(`${i + 1}. ${r}`));
    sections.push(``);
  }

  // Group findings by phase
  const phases = new Map<string, Finding[]>();
  for (const f of scan.findings) {
    if (!phases.has(f.phase)) {
      phases.set(f.phase, []);
    }
    phases.get(f.phase)!.push(f);
  }

  for (const [phase, findings] of phases) {
    sections.push(`## Phase: ${phase}`, ``);
    for (const f of findings) {
      const icon =
        f.severity === "critical"
          ? "🔴"
          : f.severity === "high"
            ? "🟠"
            : f.severity === "medium"
              ? "🟡"
              : f.severity === "low"
                ? "🟢"
                : "🔵";
      sections.push(
        `### ${icon} ${f.title}`,
        ``,
        `- **Severity**: ${f.severity.toUpperCase()}${f.cvss ? ` (CVSS ${f.cvss})` : ""}${f.cve ? ` — ${f.cve}` : ""}`,
        `- **Tool**: ${f.tool}`,
        `- **Description**: ${f.description}`,
        `- **Evidence**: \`${f.evidence.slice(0, 200)}\``,
        `- **Remediation**: ${f.remediation}`,
        ``,
      );
    }
  }

  if (scan.summary.recommendations.length > 0) {
    sections.push(`## Remediation Plan`, ``);
    scan.summary.recommendations.forEach((r, i) => sections.push(`${i + 1}. ${r}`));
    sections.push(``);
  }

  sections.push(`---`, `*Generated by HoC Kali Cybersecurity Sandbox*`);
  return sections.join("\n");
}
