/**
 * Republic AI Fusion — Model Registry Data
 *
 * Static configuration of all available AI model profiles.
 * Extracted from ai-fusion.ts for maintainability.
 */

import type { ModelProfile } from "./ai-fusion.js";

// ─── Model Registry Population ──────────────────────────────────

export const MODEL_REGISTRY: ModelProfile[] = [
  // Gemini 3 Family
  {
    id: "gemini-3-flash-lite",
    name: "Gemini 3 Flash Lite",
    provider: "gemini",
    tier: "nano",
    capabilities: new Set(["text_generation", "text_analysis", "classification", "summarization"]),
    contextWindow: 128_000,
    costPerMillionInput: 0.05,
    costPerMillionOutput: 0.15,
    avgLatencyMs: 200,
    qualityScores: {
      text_generation: 70,
      text_analysis: 65,
      classification: 75,
      summarization: 70,
    },
    available: true,
    modalities: ["text"],
  },
  {
    id: "gemini-3-flash",
    name: "Gemini 3 Flash",
    provider: "gemini",
    tier: "standard",
    capabilities: new Set([
      "text_generation",
      "text_reasoning",
      "code_generation",
      "vision_understanding",
      "tool_use",
      "function_calling",
      "long_context",
      "multi_turn_dialogue",
      "document_analysis",
    ]),
    contextWindow: 1_000_000,
    costPerMillionInput: 0.25,
    costPerMillionOutput: 1.0,
    avgLatencyMs: 500,
    qualityScores: {
      text_generation: 85,
      text_reasoning: 80,
      code_generation: 82,
      vision_understanding: 80,
      tool_use: 85,
    },
    available: true,
    modalities: ["text", "image", "code"],
  },
  {
    id: "gemini-3-pro",
    name: "Gemini 3 Pro",
    provider: "gemini",
    tier: "pro",
    capabilities: new Set([
      "text_generation",
      "text_reasoning",
      "text_analysis",
      "code_generation",
      "code_review",
      "code_debugging",
      "vision_understanding",
      "vision_generation",
      "audio_transcription",
      "audio_generation",
      "tool_use",
      "function_calling",
      "long_context",
      "chain_of_thought",
      "multi_turn_dialogue",
      "document_analysis",
      "mathematical_reasoning",
      "scientific_analysis",
      "creative_writing",
      "translation",
      "summarization",
      "real_time_streaming",
    ]),
    contextWindow: 2_000_000,
    costPerMillionInput: 1.25,
    costPerMillionOutput: 5.0,
    avgLatencyMs: 1500,
    qualityScores: {
      text_generation: 95,
      text_reasoning: 95,
      code_generation: 93,
      vision_understanding: 92,
      chain_of_thought: 96,
      mathematical_reasoning: 94,
      scientific_analysis: 95,
    },
    available: true,
    modalities: ["text", "image", "audio", "video", "code"],
  },

  // GPT-5 Family
  {
    id: "gpt-5-nano",
    name: "GPT-5 Nano",
    provider: "openai",
    tier: "nano",
    capabilities: new Set([
      "text_generation",
      "text_analysis",
      "classification",
      "embedding_generation",
    ]),
    contextWindow: 64_000,
    costPerMillionInput: 0.1,
    costPerMillionOutput: 0.3,
    avgLatencyMs: 150,
    qualityScores: { text_generation: 72, text_analysis: 68, classification: 78 },
    available: true,
    modalities: ["text"],
  },
  {
    id: "gpt-5-mini",
    name: "GPT-5 Mini",
    provider: "openai",
    tier: "mini",
    capabilities: new Set([
      "text_generation",
      "text_reasoning",
      "code_generation",
      "tool_use",
      "function_calling",
      "multi_turn_dialogue",
    ]),
    contextWindow: 128_000,
    costPerMillionInput: 0.3,
    costPerMillionOutput: 1.2,
    avgLatencyMs: 400,
    qualityScores: { text_generation: 82, text_reasoning: 78, code_generation: 80, tool_use: 82 },
    available: true,
    modalities: ["text", "code"],
  },
  {
    id: "gpt-5",
    name: "GPT-5",
    provider: "openai",
    tier: "standard",
    capabilities: new Set([
      "text_generation",
      "text_reasoning",
      "text_analysis",
      "code_generation",
      "code_review",
      "vision_understanding",
      "tool_use",
      "function_calling",
      "long_context",
      "chain_of_thought",
      "multi_turn_dialogue",
      "document_analysis",
      "creative_writing",
    ]),
    contextWindow: 256_000,
    costPerMillionInput: 2.5,
    costPerMillionOutput: 10.0,
    avgLatencyMs: 1000,
    qualityScores: {
      text_generation: 90,
      text_reasoning: 90,
      code_generation: 88,
      vision_understanding: 88,
      chain_of_thought: 92,
    },
    available: true,
    modalities: ["text", "image", "code"],
  },
  {
    id: "gpt-5.1",
    name: "GPT-5.1",
    provider: "openai",
    tier: "pro",
    capabilities: new Set([
      "text_generation",
      "text_reasoning",
      "text_analysis",
      "code_generation",
      "code_review",
      "code_debugging",
      "vision_understanding",
      "audio_transcription",
      "tool_use",
      "function_calling",
      "long_context",
      "chain_of_thought",
      "multi_turn_dialogue",
      "document_analysis",
      "mathematical_reasoning",
      "scientific_analysis",
      "creative_writing",
      "translation",
      "summarization",
    ]),
    contextWindow: 512_000,
    costPerMillionInput: 5.0,
    costPerMillionOutput: 15.0,
    avgLatencyMs: 1200,
    qualityScores: {
      text_generation: 93,
      text_reasoning: 93,
      code_generation: 91,
      mathematical_reasoning: 92,
      chain_of_thought: 94,
    },
    available: true,
    modalities: ["text", "image", "audio", "code"],
  },
  {
    id: "gpt-5.2-pro",
    name: "GPT-5.2 Pro",
    provider: "openai",
    tier: "ultra",
    capabilities: new Set([
      "text_generation",
      "text_reasoning",
      "text_analysis",
      "code_generation",
      "code_review",
      "code_debugging",
      "vision_understanding",
      "vision_generation",
      "audio_transcription",
      "audio_generation",
      "tool_use",
      "function_calling",
      "long_context",
      "chain_of_thought",
      "multi_turn_dialogue",
      "document_analysis",
      "mathematical_reasoning",
      "scientific_analysis",
      "creative_writing",
      "translation",
      "summarization",
      "classification",
      "real_time_streaming",
      "quantum_simulation",
    ]),
    contextWindow: 1_000_000,
    costPerMillionInput: 10.0,
    costPerMillionOutput: 30.0,
    avgLatencyMs: 2000,
    qualityScores: {
      text_generation: 97,
      text_reasoning: 97,
      code_generation: 96,
      mathematical_reasoning: 96,
      chain_of_thought: 98,
      quantum_simulation: 85,
    },
    available: true,
    modalities: ["text", "image", "audio", "video", "code"],
  },

  // Anthropic
  {
    id: "claude-sonnet-4.5",
    name: "Claude Sonnet 4.5",
    provider: "anthropic",
    tier: "standard",
    capabilities: new Set([
      "text_generation",
      "text_reasoning",
      "text_analysis",
      "code_generation",
      "code_review",
      "code_debugging",
      "tool_use",
      "function_calling",
      "long_context",
      "chain_of_thought",
      "multi_turn_dialogue",
      "document_analysis",
      "mathematical_reasoning",
      "scientific_analysis",
      "creative_writing",
      "summarization",
    ]),
    contextWindow: 200_000,
    costPerMillionInput: 3.0,
    costPerMillionOutput: 15.0,
    avgLatencyMs: 800,
    qualityScores: {
      text_generation: 92,
      text_reasoning: 93,
      code_generation: 94,
      code_review: 95,
      chain_of_thought: 92,
      creative_writing: 93,
    },
    available: true,
    modalities: ["text", "image", "code"],
  },
  {
    id: "claude-opus-4.5",
    name: "Claude Opus 4.5",
    provider: "anthropic",
    tier: "ultra",
    capabilities: new Set([
      "text_generation",
      "text_reasoning",
      "text_analysis",
      "code_generation",
      "code_review",
      "code_debugging",
      "vision_understanding",
      "tool_use",
      "function_calling",
      "long_context",
      "chain_of_thought",
      "multi_turn_dialogue",
      "document_analysis",
      "mathematical_reasoning",
      "scientific_analysis",
      "creative_writing",
      "translation",
      "summarization",
      "classification",
      "psychological_modeling",
    ]),
    contextWindow: 200_000,
    costPerMillionInput: 15.0,
    costPerMillionOutput: 75.0,
    avgLatencyMs: 2500,
    qualityScores: {
      text_generation: 96,
      text_reasoning: 97,
      code_generation: 96,
      code_review: 97,
      chain_of_thought: 97,
      scientific_analysis: 96,
      psychological_modeling: 90,
    },
    available: true,
    modalities: ["text", "image", "code"],
  },

  // Local models
  {
    id: "ollama-deepseek-r1",
    name: "DeepSeek-R1 (Local)",
    provider: "local_ollama",
    tier: "standard",
    capabilities: new Set([
      "text_generation",
      "text_reasoning",
      "code_generation",
      "code_review",
      "chain_of_thought",
      "mathematical_reasoning",
    ]),
    contextWindow: 64_000,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    avgLatencyMs: 3000,
    qualityScores: {
      text_generation: 78,
      text_reasoning: 82,
      code_generation: 80,
      chain_of_thought: 85,
      mathematical_reasoning: 84,
    },
    available: true,
    modalities: ["text", "code"],
  },
  {
    id: "nvidia-nim-llama3",
    name: "LLaMA 3 (NVIDIA NIM)",
    provider: "local_nvidia",
    tier: "standard",
    capabilities: new Set([
      "text_generation",
      "text_reasoning",
      "code_generation",
      "tool_use",
      "function_calling",
      "multi_turn_dialogue",
    ]),
    contextWindow: 128_000,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    avgLatencyMs: 800,
    qualityScores: { text_generation: 80, text_reasoning: 78, code_generation: 77, tool_use: 75 },
    available: true,
    modalities: ["text", "code"],
  },
];
