/**
 * Republic Platform — Research Engine
 *
 * ACE Loop 2: Autonomous Knowledge Acquisition & Discovery
 *
 * Inspired by:
 *   - FutureHouse's AI research agents (PaperQA, hypothesis generation)
 *   - Google DeepMind's AI co-scientist (multi-agent hypothesis validation)
 *   - Agents4Science (LLM-driven research pipelines)
 *   - Popper framework (automated hypothesis falsification)
 *
 * Citizens autonomously:
 *   1. Conduct research on topics generated by the Curiosity Engine
 *   2. Generate and validate hypotheses using multi-model AI
 *   3. Synthesize findings into structured knowledge articles
 *   4. Peer-review each other's discoveries
 *   5. Publish validated knowledge to the Republic's knowledge base
 *
 * Integrates with:
 *   - ai-fusion.ts          (multi-model inference, ensemble voting)
 *   - curiosity-engine.ts   (research questions, frontier domains)
 *   - memory-reflection.ts  (insight retrieval, procedural memory)
 *   - trust-reputation.ts   (peer review credibility)
 *   - autonomous-learning.ts (domain expertise checks)
 */

import * as fs from "node:fs";
import * as path from "node:path";
import {
    answerResearchQuestion, getResearchQuestions, markQuestionActive
} from "./curiosity-engine.js";
import { generateMarkdown } from "./document-generator.js";
import type { RepublicState } from "./types.js";
import { rand, ts, uid } from "./utils.js";

// ─── Configuration ──────────────────────────────────────────────

/** Ticks per research step (simulated investigation time) */
const _TICKS_PER_RESEARCH_STEP = 6;

/** Research ticks per full cycle */
const RESEARCH_INTERVAL = 40;

/** Max simultaneous active research sessions globally */
const MAX_ACTIVE_RESEARCH = 50;

/** Max knowledge articles stored */
const MAX_KNOWLEDGE_ARTICLES = 1000;

/** Max research reports stored */
const MAX_RESEARCH_REPORTS = 500;

/** Minimum confidence to auto-publish (0-1) */
const MIN_PUBLISH_CONFIDENCE = 0.6;

/** Minimum peer reviews before publication */
const MIN_PEER_REVIEWS = 1;

// ─── Types ──────────────────────────────────────────────────────

export type ResearchPhase =
  | "question_formulation"
  | "literature_review"
  | "hypothesis_generation"
  | "experimentation"
  | "cross_validation"
  | "synthesis"
  | "peer_review"
  | "publication";

export interface ResearchSession {
  id: string;
  citizenId: string;
  citizenName: string;
  /** The research question being investigated */
  questionId: string;
  domainPath: string;
  topic: string;
  /** Current phase in the research pipeline */
  phase: ResearchPhase;
  /** Ticks remaining in current phase */
  ticksRemaining: number;
  /** Accumulated findings from each phase */
  findings: ResearchFinding[];
  /** Generated hypothesis (from hypothesis_generation phase) */
  hypothesis?: string;
  /** Confidence in hypothesis (0-1, updated at each phase) */
  confidence: number;
  /** Models used during research */
  modelsUsed: string[];
  /** Peer review results */
  peerReviews: PeerReview[];
  status: "active" | "completed" | "failed" | "abandoned";
  createdAt: string;
  completedAt?: string;
}

export interface ResearchFinding {
  phase: ResearchPhase;
  content: string;
  confidence: number;
  modelUsed: string;
  tick: number;
}

export interface PeerReview {
  reviewerId: string;
  reviewerName: string;
  verdict: "approved" | "needs_revision" | "rejected";
  comments: string;
  confidence: number;
  reviewedAt: string;
}

export interface KnowledgeArticle {
  id: string;
  title: string;
  domainPath: string;
  /** Structured content */
  abstract: string;
  findings: string[];
  methodology: string;
  conclusions: string;
  /** Provenance */
  authorId: string;
  authorName: string;
  researchSessionId: string;
  questionId: string;
  /** Quality metrics */
  confidence: number;
  peerReviewScore: number;
  reviewCount: number;
  /** Citation tracking */
  citedBy: string[]; // article IDs
  references: string[]; // article IDs
  /** Discovery classification */
  isNovel: boolean;
  impactScore: number;
  /** Timestamps */
  publishedAt: string;
  lastUpdatedAt: string;
}

// ─── State ──────────────────────────────────────────────────────

const researchSessions: ResearchSession[] = [];
const knowledgeArticles: KnowledgeArticle[] = [];

// ─── Research Phase Pipeline ─────────────────────────────────────

const PHASE_ORDER: ResearchPhase[] = [
  "question_formulation",
  "literature_review",
  "hypothesis_generation",
  "experimentation",
  "cross_validation",
  "synthesis",
  "peer_review",
  "publication",
];

const PHASE_TICKS: Record<ResearchPhase, number> = {
  question_formulation: 3,
  literature_review: 8,
  hypothesis_generation: 5,
  experimentation: 10,
  cross_validation: 6,
  synthesis: 4,
  peer_review: 5,
  publication: 2,
};

// ─── State Sync (C1) ────────────────────────────────────────────

/**
 * Initialize module arrays from RepublicState (called at startup).
 */
export function initResearchFromState(s: RepublicState): void {
  if (s.knowledgeBase && s.knowledgeBase.length > 0) {
    knowledgeArticles.length = 0;
    knowledgeArticles.push(...s.knowledgeBase);
  }
  if (s.researchJournal && s.researchJournal.length > 0) {
    researchSessions.length = 0;
    researchSessions.push(...s.researchJournal);
  }
}

/**
 * Sync module arrays to RepublicState (called each tick).
 */
export function syncResearchToState(s: RepublicState): void {
  s.knowledgeBase = knowledgeArticles;
  s.researchJournal = researchSessions;
}

// ─── Research Initiation ────────────────────────────────────────

/**
 * Start a research session for a citizen on a given research question.
 *
 * The citizen begins at the question_formulation phase and progresses
 * through the full pipeline automatically.
 */
export function conductResearch(
  s: RepublicState,
  citizenId: string,
  questionId: string,
): ResearchSession | null {
  const citizen = s.citizens.find((c) => c.id === citizenId);
  if (!citizen) {
    return null;
  }

  // Check if already at capacity
  const active = researchSessions.filter((r) => r.status === "active");
  if (active.length >= MAX_ACTIVE_RESEARCH) {
    return null;
  }

  // M5: Check if citizen is already researching — return null instead of stale session
  const existing = active.find((r) => r.citizenId === citizenId);
  if (existing) {
    return null;
  }

  // Find the research question
  const questions = getResearchQuestions({ status: "proposed" });
  const question =
    questions.find((q) => q.id === questionId) ??
    getResearchQuestions({ status: "active" }).find((q) => q.id === questionId);
  if (!question) {
    return null;
  }

  // H1: Mark the question as "active" so other citizens don't pick it up
  markQuestionActive(questionId);

  const session: ResearchSession = {
    id: `rs-${uid()}`,
    citizenId,
    citizenName: citizen.name,
    questionId,
    domainPath: question.domainPath,
    topic: question.question,
    phase: "question_formulation",
    ticksRemaining: PHASE_TICKS.question_formulation,
    findings: [],
    confidence: 0.1,
    modelsUsed: [],
    peerReviews: [],
    status: "active",
    createdAt: ts(),
  };

  researchSessions.push(session);
  return session;
}

// ─── Phase Execution ────────────────────────────────────────────

/**
 * Advance a research session by one tick.
 * When a phase completes, generates findings and transitions to next phase.
 */
function advanceResearchPhase(s: RepublicState, session: ResearchSession): void {
  session.ticksRemaining--;

  if (session.ticksRemaining > 0) {
    return;
  }

  // Phase completed — generate findings for this phase
  const finding = generatePhaseFinding(s, session);
  session.findings.push(finding);

  // Determine next phase
  const currentIdx = PHASE_ORDER.indexOf(session.phase);
  if (currentIdx < PHASE_ORDER.length - 1) {
    const nextPhase = PHASE_ORDER[currentIdx + 1];
    session.phase = nextPhase;
    session.ticksRemaining = PHASE_TICKS[nextPhase];

    // Special handling for peer_review phase
    if (nextPhase === "peer_review") {
      conductPeerReview(s, session);
    }
  } else {
    // All phases complete — attempt publication
    completeResearch(s, session);
  }
}

/**
 * Generate a research finding for the completed phase.
 * Uses structured templates for deterministic progress + fires async LLM
 * via routeInference for real analysis enrichment.
 * H3: Receives currentTick directly to set tick accurately.
 * H4+H5: Uses seeded rand() instead of Math.random().
 */
function generatePhaseFinding(s: RepublicState, session: ResearchSession): ResearchFinding {
  const phase = session.phase;

  // Model selection (multi-model routing)
  const models = [
    "gpt-4.1",
    "gemini-2.5-pro",
    "claude-sonnet-4",
    "o4-mini",
    "gemini-2.5-flash",
    "claude-haiku-3.5",
  ];
  const model = models[rand(0, models.length - 1)];
  if (!session.modelsUsed.includes(model)) {
    session.modelsUsed.push(model);
  }

  // Structured template for deterministic progress
  const contentByPhase: Record<ResearchPhase, string> = {
    question_formulation: `Refined research question: "${session.topic}" — identified key variables and scope boundaries for investigation in ${session.domainPath}.`,
    literature_review: `Surveyed existing knowledge in ${session.domainPath}. Found ${rand(3, 12)} relevant prior findings. Identified ${rand(1, 4)} knowledge gaps that this research can address.`,
    hypothesis_generation: `Generated hypothesis: "${session.hypothesis ?? `Applying novel ${session.domainPath} techniques yields measurable improvement in target metrics`}". Testable via simulation and cross-validation.`,
    experimentation: `Conducted ${rand(3, 8)} experimental simulations. Results indicate ${rand(60, 95)}% support for hypothesis. Key finding: ${session.domainPath} methods show ${rand(10, 45)}% improvement over baseline.`,
    cross_validation: `Cross-validated findings using ${rand(2, 4)} independent models (ensemble inference). Consensus confidence: ${Math.round(session.confidence * 100)}%. No significant contradictions found.`,
    synthesis: `Synthesized ${session.findings.length} phase findings into structured knowledge article. Abstract, methodology, and conclusions prepared for peer review.`,
    peer_review: `Peer review phase: ${session.peerReviews.length} reviews collected. ${session.peerReviews.filter((r) => r.verdict === "approved").length} approvals.`,
    publication: `Published to Republic knowledge base. Article available for citation and further research.`,
  };

  // H5: Update confidence using seeded rand instead of Math.random
  const confidenceGainByPhase: Record<ResearchPhase, number> = {
    question_formulation: 0.05,
    literature_review: 0.15,
    hypothesis_generation: 0.1,
    experimentation: 0.25,
    cross_validation: 0.15,
    synthesis: 0.1,
    peer_review: 0.1,
    publication: 0.05,
  };

  const jitter = (rand(0, 50) - 25) / 1000; // H5: seeded ±0.025 jitter
  session.confidence = Math.min(1, session.confidence + confidenceGainByPhase[phase] + jitter);

  // Set hypothesis during hypothesis_generation phase
  if (phase === "hypothesis_generation" && !session.hypothesis) {
    session.hypothesis = `Novel ${session.domainPath} techniques yield ${rand(15, 40)}% improvement in target Republic metrics`;
  }

  const finding: ResearchFinding = {
    phase,
    content: contentByPhase[phase],
    confidence: session.confidence,
    modelUsed: model,
    tick: s.currentTick,
  };

  // ── Async LLM enrichment (non-blocking) ──
  // Fire real inference to enrich finding with LLM analysis.
  // The async result appends to the finding content if it completes in time.
  const phasePrompts: Partial<Record<ResearchPhase, string>> = {
    literature_review: `Survey the current state of research in "${session.domainPath}" related to: "${session.topic}". List 3-5 key findings and knowledge gaps. Be concise.`,
    hypothesis_generation: `Given the research question "${session.topic}" in domain "${session.domainPath}", generate a specific, testable hypothesis. Include expected outcomes and methodology.`,
    experimentation: `Design an experiment to test: "${session.hypothesis ?? session.topic}" in "${session.domainPath}". Outline methodology, expected results, and metrics. Be specific.`,
    synthesis: `Synthesize the following research findings into a coherent conclusion:\n${session.findings.map(f => f.content).join("\n")}\nProvide: key insight, limitations, and next steps. 3-5 sentences.`,
  };

  const prompt = phasePrompts[phase];
  if (prompt) {
    void (async () => {
      try {
        const { routeInference } = await import("./inference-gateway.js");
        const result = await routeInference({
          citizenId: session.citizenId,
          prompt,
          systemPrompt: `You are a ${session.domainPath} researcher named ${session.citizenName}. Produce rigorous, evidence-based research findings. Be concise and specific.`,
          toolName: "research_finding",
          task: { type: "decision" as const, complexity: 0.7, citizenId: session.citizenId, description: `Research: ${session.topic} (${phase})` },
          specialization: "Scientist" as unknown as import("./types.js").Specialization,
          skillLevel: 7,
          maxTokens: 512,
        });
        if (result && typeof result === "object" && "text" in result) {
          finding.content += `\n\n[LLM Analysis]: ${String((result as Record<string, unknown>).text).slice(0, 500)}`;
        }
      } catch { /* template fallback already set */ }
    })();
  }

  return finding;
}

// ─── Peer Review ────────────────────────────────────────────────

/**
 * Conduct peer review by finding qualified citizens to review the research.
 * H4: Uses seeded rand() instead of Math.random() for reproducibility.
 */
function conductPeerReview(s: RepublicState, session: ResearchSession): void {
  // Find citizens certified in the same domain (exclude the author)
  const reviewers = s.citizens.filter(
    (c) =>
      c.id !== session.citizenId &&
      c.professionalProfile?.certifications?.some(
        (cert) => cert.domainPath === session.domainPath && cert.valid,
      ),
  );

  // H4: Shuffle using seeded rand instead of Math.random
  const shuffled = reviewers.toSorted(() => rand(0, 2) - 1);
  const selected = shuffled.slice(0, 3);

  for (const reviewer of selected) {
    // Simulate review quality based on reviewer's expertise
    const cert = reviewer.professionalProfile?.certifications?.find(
      (c) => c.domainPath === session.domainPath && c.valid,
    );
    const levelBonus = cert?.level === "doctorate" || cert?.level === "fellowship" ? 0.2 : 0;

    // H4: seeded confidence instead of Math.random
    const reviewConfidence = Math.min(1, 0.5 + levelBonus + rand(0, 30) / 100);

    // Verdict based on session confidence + seeded randomness
    let verdict: PeerReview["verdict"];
    if (session.confidence > 0.7 && reviewConfidence > 0.5) {
      verdict = "approved";
    } else if (session.confidence > 0.4) {
      verdict = rand(0, 100) > 30 ? "approved" : "needs_revision";
    } else {
      verdict = rand(0, 100) > 50 ? "needs_revision" : "rejected";
    }

    session.peerReviews.push({
      reviewerId: reviewer.id,
      reviewerName: reviewer.name,
      verdict,
      comments:
        verdict === "approved"
          ? `Research methodology is sound. Findings in ${session.domainPath} are well-supported.`
          : verdict === "needs_revision"
            ? `Some claims need additional evidence. Consider expanding cross-validation.`
            : `Insufficient evidence to support hypothesis. Recommend additional experimentation.`,
      confidence: reviewConfidence,
      reviewedAt: ts(),
    });
  }
}

// ─── Research Completion ────────────────────────────────────────

/**
 * Complete a research session and attempt to publish as a knowledge article.
 */
function completeResearch(s: RepublicState, session: ResearchSession): void {
  session.status = "completed";
  session.completedAt = ts();

  // Check if publishable
  const approvals = session.peerReviews.filter((r) => r.verdict === "approved").length;
  const avgReviewConfidence =
    session.peerReviews.length > 0
      ? session.peerReviews.reduce((sum, r) => sum + r.confidence, 0) / session.peerReviews.length
      : 0;

  if (session.confidence >= MIN_PUBLISH_CONFIDENCE && approvals >= MIN_PEER_REVIEWS) {
    publishDiscovery(s, session, avgReviewConfidence);

    // Generate a markdown research document as a tangible deliverable
    try {
      const findingsText = session.findings.map(
        (f, i) => `### Phase ${i + 1}: ${f.phase}\n${f.content}\n*Model: ${f.modelUsed} | Confidence: ${(f.confidence * 100).toFixed(1)}%*`,
      ).join("\n\n");

      const docSpec = {
        title: `Research: ${session.topic}`,
        format: "md" as const,
        author: session.citizenName,
        sections: [
          { heading: "Overview", content: `**Domain:** ${session.domainPath}\n**Confidence:** ${(session.confidence * 100).toFixed(1)}%\n**Models Used:** ${session.modelsUsed.join(", ")}\n**Peer Reviews:** ${approvals}/${session.peerReviews.length} approved`, type: "text" as const },
          { heading: "Hypothesis", content: session.hypothesis ?? "No formal hypothesis generated.", type: "text" as const },
          { heading: "Findings", content: findingsText, type: "text" as const },
          { heading: "Conclusions", content: session.hypothesis ?? `Novel insights discovered in ${session.domainPath}.`, type: "text" as const },
        ],
      };

      const researchDir = path.join(process.cwd(), "republic-output", "research");
      fs.mkdirSync(researchDir, { recursive: true });
      const savePath = path.join(researchDir, `research-${session.id}.md`);
      generateMarkdown(docSpec, savePath, session.citizenId).catch(() => {
        // Document generation is non-critical — failures must not affect the research pipeline
      });
    } catch {
      // Best-effort document generation; swallow errors
    }
  }

  // Answer the research question
  if (session.findings.length > 0) {
    const synthesized = session.findings.map((f) => f.content).join(" | ");
    answerResearchQuestion(session.questionId, synthesized);
  }
}

/**
 * Publish a completed research session as a knowledge article.
 */
function publishDiscovery(s: RepublicState, session: ResearchSession, peerScore: number): void {
  const article: KnowledgeArticle = {
    id: `ka-${uid()}`,
    title: `Discovery: ${session.topic}`,
    domainPath: session.domainPath,
    abstract:
      session.findings
        .filter((f) => f.phase === "synthesis")
        .map((f) => f.content)
        .join(" ") || `Research findings in ${session.domainPath}`,
    findings: session.findings.map((f) => f.content),
    methodology: `Multi-phase research pipeline: ${session.modelsUsed.join(", ")}. ${session.findings.length} phase findings collected. ${session.peerReviews.length} peer reviews.`,
    conclusions: session.hypothesis ?? `Novel insights discovered in ${session.domainPath}`,
    authorId: session.citizenId,
    authorName: session.citizenName,
    researchSessionId: session.id,
    questionId: session.questionId,
    confidence: session.confidence,
    peerReviewScore: peerScore,
    reviewCount: session.peerReviews.length,
    citedBy: [],
    references: findRelatedArticles(session.domainPath).map((a) => a.id),
    isNovel: !knowledgeArticles.some(
      (a) => a.domainPath === session.domainPath && a.confidence > session.confidence,
    ),
    impactScore: session.confidence * peerScore,
    publishedAt: ts(),
    lastUpdatedAt: ts(),
  };

  knowledgeArticles.push(article);

  // Update citations on referenced articles
  for (const refId of article.references) {
    const ref = knowledgeArticles.find((a) => a.id === refId);
    if (ref && !ref.citedBy.includes(article.id)) {
      ref.citedBy.push(article.id);
    }
  }

  // C2+C3: Trim old knowledge articles using reverse-index removal
  if (knowledgeArticles.length > MAX_KNOWLEDGE_ARTICLES) {
    const removable = knowledgeArticles
      .filter((a) => a.citedBy.length === 0) // don't remove cited articles
      .toSorted((a, b) => a.impactScore - b.impactScore);
    const removeCount = Math.ceil(removable.length / 4);
    const removeIds = new Set(removable.slice(0, removeCount).map((a) => a.id));
    for (let i = knowledgeArticles.length - 1; i >= 0; i--) {
      if (removeIds.has(knowledgeArticles[i].id)) {
        knowledgeArticles.splice(i, 1);
      }
    }
  }
}

/**
 * Find articles related to a domain (for citations).
 */
function findRelatedArticles(domainPath: string): KnowledgeArticle[] {
  return knowledgeArticles
    .filter((a) => a.domainPath === domainPath || domainPath.startsWith(a.domainPath))
    .toSorted((a, b) => b.confidence - a.confidence)
    .slice(0, 5);
}

// ─── Query API ──────────────────────────────────────────────────

/**
 * Search the knowledge base.
 */
export function searchKnowledgeBase(opts?: {
  domainPath?: string;
  authorId?: string;
  minConfidence?: number;
  query?: string;
  limit?: number;
}): KnowledgeArticle[] {
  const limit = opts?.limit ?? 20;
  return knowledgeArticles
    .filter((a) => {
      if (opts?.domainPath && !a.domainPath.startsWith(opts.domainPath)) {
        return false;
      }
      if (opts?.authorId && a.authorId !== opts.authorId) {
        return false;
      }
      if (opts?.minConfidence && a.confidence < opts.minConfidence) {
        return false;
      }
      if (opts?.query) {
        const q = opts.query.toLowerCase();
        const match =
          a.title.toLowerCase().includes(q) ||
          a.abstract.toLowerCase().includes(q) ||
          a.conclusions.toLowerCase().includes(q);
        if (!match) {
          return false;
        }
      }
      return true;
    })
    .toSorted((a, b) => b.impactScore - a.impactScore)
    .slice(0, limit);
}

/**
 * Get active research sessions.
 */
export function getActiveResearch(citizenId?: string): ResearchSession[] {
  return researchSessions.filter(
    (r) => r.status === "active" && (!citizenId || r.citizenId === citizenId),
  );
}

/**
 * Get research journal (all completed sessions).
 */
export function getResearchJournal(opts?: {
  citizenId?: string;
  domainPath?: string;
  limit?: number;
}): ResearchSession[] {
  return researchSessions
    .filter((r) => {
      if (opts?.citizenId && r.citizenId !== opts.citizenId) {
        return false;
      }
      if (opts?.domainPath && r.domainPath !== opts.domainPath) {
        return false;
      }
      return true;
    })
    .toSorted((a, b) => (b.completedAt ?? b.createdAt).localeCompare(a.completedAt ?? a.createdAt))
    .slice(0, opts?.limit ?? 50);
}

/**
 * Get knowledge base stats.
 */
export function getKnowledgeBaseStats(): {
  totalArticles: number;
  novelDiscoveries: number;
  avgConfidence: number;
  avgImpact: number;
  topDomains: Array<{ domain: string; count: number }>;
  topAuthors: Array<{ authorId: string; authorName: string; count: number }>;
} {
  const domainCounts: Record<string, number> = {};
  const authorCounts: Record<string, { name: string; count: number }> = {};
  let totalConf = 0;
  let totalImpact = 0;
  let novel = 0;

  for (const a of knowledgeArticles) {
    domainCounts[a.domainPath] = (domainCounts[a.domainPath] ?? 0) + 1;
    if (!authorCounts[a.authorId]) {
      authorCounts[a.authorId] = { name: a.authorName, count: 0 };
    }
    authorCounts[a.authorId].count++;
    totalConf += a.confidence;
    totalImpact += a.impactScore;
    if (a.isNovel) {
      novel++;
    }
  }

  const n = knowledgeArticles.length || 1;
  return {
    totalArticles: knowledgeArticles.length,
    novelDiscoveries: novel,
    avgConfidence: Math.round((totalConf / n) * 100) / 100,
    avgImpact: Math.round((totalImpact / n) * 100) / 100,
    topDomains: Object.entries(domainCounts)
      .map(([domain, count]) => ({ domain, count }))
      .toSorted((a, b) => b.count - a.count)
      .slice(0, 10),
    topAuthors: Object.entries(authorCounts)
      .map(([authorId, { name, count }]) => ({ authorId, authorName: name, count }))
      .toSorted((a, b) => b.count - a.count)
      .slice(0, 10),
  };
}

// ─── Tick Integration ───────────────────────────────────────────

/**
 * Research tick — advances active research sessions and auto-starts new ones.
 *
 * 1. Advance all active research sessions by one tick
 * 2. Auto-start research for idle certified citizens with pending questions
 *
 * INVARIANT (C4): All iteration over researchSessions completes before
 * the trimming block. Trimming uses reverse-index removal (C2).
 */
export function researchTick(s: RepublicState): void {
  // 1. Advance active sessions
  for (const session of researchSessions) {
    if (session.status !== "active") {
      continue;
    }

    // H3: tick is now set directly in generatePhaseFinding — no post-hoc patching needed

    advanceResearchPhase(s, session);
  }

  // 2. Auto-start research for eligible citizens (staggered)
  if (s.currentTick % RESEARCH_INTERVAL !== 0) {
    // C1: Still sync state even if we skip auto-start
    syncResearchToState(s);
    return;
  }

  // H2: Re-count active sessions dynamically inside the loop
  let activeCount = researchSessions.filter((r) => r.status === "active").length;
  if (activeCount >= MAX_ACTIVE_RESEARCH) {
    syncResearchToState(s);
    return;
  }

  // Find pending research questions
  const pendingQuestions = getResearchQuestions({ status: "proposed" });
  if (pendingQuestions.length === 0) {
    syncResearchToState(s);
    return;
  }

  // Find eligible citizens (certified, not already researching, has energy)
  for (const citizen of s.citizens) {
    if (activeCount >= MAX_ACTIVE_RESEARCH) {
      break;
    } // H2: uses live counter
    if (citizen.energy < 20 || citizen.activity === "Sleeping") {
      continue;
    }

    // Check if already researching
    const alreadyResearching = researchSessions.some(
      (r) => r.citizenId === citizen.id && r.status === "active",
    );
    if (alreadyResearching) {
      continue;
    }

    // Check if citizen is certified in any domain
    const certs = citizen.professionalProfile?.certifications?.filter((c) => c.valid) ?? [];
    if (certs.length === 0) {
      continue;
    }

    // Find a matching question in their domain of expertise
    const matchingQ = pendingQuestions.find((q) =>
      certs.some((c) => c.domainPath === q.domainPath),
    );
    if (!matchingQ) {
      continue;
    }

    // Only some citizens auto-start (15% chance per cycle)
    if (rand(0, 100) > 15) {
      continue;
    }

    const result = conductResearch(s, citizen.id, matchingQ.id);
    if (result) {
      activeCount++; // H2: increment live counter
    }
  }

  // C2+C3: Trim completed/failed sessions using reverse-index removal
  if (researchSessions.length > MAX_RESEARCH_REPORTS) {
    const removable = researchSessions
      .filter((r) => r.status === "completed" || r.status === "failed" || r.status === "abandoned")
      .toSorted((a, b) =>
        (a.completedAt ?? a.createdAt).localeCompare(b.completedAt ?? b.createdAt),
      );
    const removeCount = Math.ceil(removable.length / 2);
    const removeIds = new Set(removable.slice(0, removeCount).map((r) => r.id));
    for (let i = researchSessions.length - 1; i >= 0; i--) {
      if (removeIds.has(researchSessions[i].id)) {
        researchSessions.splice(i, 1);
      }
    }
  }

  // C1: Sync module state to RepublicState for persistence
  syncResearchToState(s);
}

// ─── Diagnostics ────────────────────────────────────────────────

export interface ResearchDiagnostics {
  activeResearchSessions: number;
  completedSessions: number;
  totalKnowledgeArticles: number;
  novelDiscoveries: number;
  avgResearchConfidence: number;
  avgPeerReviewScore: number;
  modelsUsed: string[];
  topResearchDomains: Array<{ domain: string; sessions: number }>;
}

export function researchDiagnostics(): ResearchDiagnostics {
  const active = researchSessions.filter((r) => r.status === "active");
  const completed = researchSessions.filter((r) => r.status === "completed");
  const allModels = new Set<string>();
  let totalConf = 0;
  let totalReview = 0;
  let reviewCount = 0;
  const domainSessions: Record<string, number> = {};

  for (const session of researchSessions) {
    for (const m of session.modelsUsed) {
      allModels.add(m);
    }
    totalConf += session.confidence;
    for (const r of session.peerReviews) {
      totalReview += r.confidence;
      reviewCount++;
    }
    domainSessions[session.domainPath] = (domainSessions[session.domainPath] ?? 0) + 1;
  }

  const n = researchSessions.length || 1;
  return {
    activeResearchSessions: active.length,
    completedSessions: completed.length,
    totalKnowledgeArticles: knowledgeArticles.length,
    novelDiscoveries: knowledgeArticles.filter((a) => a.isNovel).length,
    avgResearchConfidence: Math.round((totalConf / n) * 100) / 100,
    avgPeerReviewScore: reviewCount > 0 ? Math.round((totalReview / reviewCount) * 100) / 100 : 0,
    modelsUsed: [...allModels],
    topResearchDomains: Object.entries(domainSessions)
      .map(([domain, sessions]) => ({ domain, sessions }))
      .toSorted((a, b) => b.sessions - a.sessions)
      .slice(0, 10),
  };
}

// ─── Engine 12: Autonomous Discovery ────────────────────────────
// Cross-domain hypothesis generation & serendipitous connections

import { rng } from "./utils.js";

export interface CrossDomainHypothesis {
  id: string;
  domainA: string;
  domainB: string;
  hypothesis: string;
  analogyBasis: string;
  confidence: number;
  validated: boolean;
  generatorId: string;
  createdAt: string;
}

const crossDomainHypotheses: CrossDomainHypothesis[] = [];
const MAX_HYPOTHESES = 100;
const DISCOVERY_TICK_INTERVAL = 60;

const CROSS_DOMAIN_ANALOGIES = [
  {
    domainA: "biology",
    domainB: "technology",
    analogy: "neural networks mirror biological neurons",
  },
  {
    domainA: "economics",
    domainB: "ecology",
    analogy: "market competition parallels ecological niches",
  },
  {
    domainA: "physics",
    domainB: "social",
    analogy: "gravitational attraction mirrors social influence",
  },
  { domainA: "chemistry", domainB: "governance", analogy: "catalysis mirrors policy acceleration" },
  { domainA: "mathematics", domainB: "music", analogy: "harmonic series connect math and music" },
  {
    domainA: "linguistics",
    domainB: "genetics",
    analogy: "language evolution mirrors genetic drift",
  },
  { domainA: "astronomy", domainB: "network", analogy: "galaxy clusters mirror network topology" },
  {
    domainA: "psychology",
    domainB: "economics",
    analogy: "cognitive biases drive market behavior",
  },
];

/** Generate a cross-domain hypothesis from knowledge articles */
export function generateCrossDomainHypothesis(
  citizenId: string,
  _citizenName: string,
): CrossDomainHypothesis | null {
  if (crossDomainHypotheses.length >= MAX_HYPOTHESES) {
    return null;
  }

  // Pick a random analogy template
  const template = CROSS_DOMAIN_ANALOGIES[Math.floor(rng() * CROSS_DOMAIN_ANALOGIES.length)];

  // Find related articles for both domains
  const articlesA = findRelatedArticles(template.domainA);
  const articlesB = findRelatedArticles(template.domainB);

  // Generate hypothesis from combination
  const hypothesisText =
    articlesA.length > 0 && articlesB.length > 0
      ? `If ${articlesA[0].title} applies to ${template.domainA}, then by analogy (${template.analogy}), similar principles might apply in ${template.domainB} — specifically ${articlesB[0].title}.`
      : `Cross-domain transfer: ${template.analogy}. This suggests new research avenues connecting ${template.domainA} and ${template.domainB}.`;

  const hypothesis: CrossDomainHypothesis = {
    id: uid(),
    domainA: template.domainA,
    domainB: template.domainB,
    hypothesis: hypothesisText,
    analogyBasis: template.analogy,
    confidence: 0.3 + rng() * 0.4,
    validated: false,
    generatorId: citizenId,
    createdAt: ts(),
  };

  crossDomainHypotheses.push(hypothesis);
  return hypothesis;
}

/** Autonomous discovery tick — generates cross-domain hypotheses */
export function autonomousDiscoveryTick(s: RepublicState): void {
  if (s.currentTick % DISCOVERY_TICK_INTERVAL !== 0) {
    return;
  }

  // Top researchers (those with completed sessions) generate hypotheses
  for (const citizen of s.citizens) {
    if (rng() > 0.05) {
      continue;
    } // 5% chance per citizen per tick

    const citizenSessions = researchSessions.filter(
      (r) => r.citizenId === citizen.id && r.status === "completed",
    );

    if (citizenSessions.length >= 2) {
      const hypothesis = generateCrossDomainHypothesis(citizen.id, citizen.name);
      if (hypothesis && citizen.xp !== undefined) {
        citizen.xp += 3; // Discovery XP bonus
      }
    }
  }
}

export function getCrossDomainHypotheses(): CrossDomainHypothesis[] {
  return [...crossDomainHypotheses];
}
