/**
 * Fine-Tune Pipeline — Core Orchestrator
 *
 * Manages the full fine-tuning lifecycle:
 * 1. Dataset preparation (chat logs → ShareGPT/Alpaca format)
 * 2. Training via LlamaFactory (LoRA/QLoRA)
 * 3. Evaluation against held-out validation set
 * 4. LoRA merge into base model
 * 5. Deploy to LM Studio / Ollama for immediate use
 */

import type {
  TrainingJob,
  TrainingStatus,
  TrainingMethod,
  DatasetConfig,
  LoRAConfig,
  HyperParams,
  TrainingMetrics,
  FineTuneDiagnostics,
} from "./types.js";

// ─── State ───────────────────────────────────────────────────────

const jobs = new Map<string, TrainingJob>();
let idCounter = 0;

function genId(): string {
  return `ft-${Date.now().toString(36)}-${(++idCounter).toString(36)}`;
}

function now(): string {
  return new Date().toISOString();
}

// ─── Default Configs ─────────────────────────────────────────────

const DEFAULT_LORA: LoRAConfig = {
  rank: 16,
  alpha: 32,
  dropout: 0.05,
  targetModules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
};

const DEFAULT_HYPERPARAMS: HyperParams = {
  learningRate: 2e-4,
  epochs: 3,
  batchSize: 4,
  gradAccumSteps: 4,
  warmupRatio: 0.1,
  maxSeqLen: 2048,
  weightDecay: 0.01,
};

const DEFAULT_METRICS: TrainingMetrics = {
  loss: 0,
  epoch: 0,
  step: 0,
  totalSteps: 0,
  tokensPerSec: 0,
  etaSeconds: 0,
  lossHistory: [],
};

// ─── Job Management ──────────────────────────────────────────────

/** Create a new fine-tuning job */
export function createTrainingJob(
  name: string,
  baseModel: string,
  dataset: DatasetConfig,
  opts?: {
    method?: TrainingMethod;
    lora?: Partial<LoRAConfig>;
    hyperparams?: Partial<HyperParams>;
  },
): TrainingJob {
  const job: TrainingJob = {
    id: genId(),
    name,
    baseModel,
    method: opts?.method ?? "qlora",
    dataset,
    loraConfig: { ...DEFAULT_LORA, ...opts?.lora },
    hyperparams: { ...DEFAULT_HYPERPARAMS, ...opts?.hyperparams },
    status: "pending",
    progress: 0,
    metrics: { ...DEFAULT_METRICS },
    createdAt: now(),
  };

  jobs.set(job.id, job);
  return job;
}

/** Get a training job by ID */
export function getTrainingJob(id: string): TrainingJob | null {
  return jobs.get(id) ?? null;
}

/** List all training jobs */
export function listTrainingJobs(status?: TrainingStatus): TrainingJob[] {
  let all = [...jobs.values()];
  if (status) {
    all = all.filter((j) => j.status === status);
  }
  return all.toSorted((a, b) => b.createdAt.localeCompare(a.createdAt));
}

/** Update job status and progress */
export function updateJobProgress(
  id: string,
  status: TrainingStatus,
  progress: number,
  metrics?: Partial<TrainingMetrics>,
): boolean {
  const job = jobs.get(id);
  if (!job) {
    return false;
  }

  job.status = status;
  job.progress = Math.max(0, Math.min(100, progress));

  if (metrics) {
    Object.assign(job.metrics, metrics);
    if (metrics.loss !== undefined) {
      job.metrics.lossHistory.push({ step: job.metrics.step, loss: metrics.loss });
      // Keep last 500 points
      if (job.metrics.lossHistory.length > 500) {
        job.metrics.lossHistory = job.metrics.lossHistory.slice(-500);
      }
    }
  }

  if (status === "training" && !job.startedAt) {
    job.startedAt = now();
  }
  if (status === "complete" || status === "failed") {
    job.completedAt = now();
  }

  return true;
}

/** Cancel a training job */
export function cancelTrainingJob(id: string): boolean {
  const job = jobs.get(id);
  if (!job || job.status === "complete" || job.status === "failed") {
    return false;
  }
  job.status = "failed";
  job.error = "Cancelled by user";
  job.completedAt = now();
  return true;
}

/** Delete a training job */
export function deleteTrainingJob(id: string): boolean {
  return jobs.delete(id);
}

// ─── LlamaFactory Config Generator ──────────────────────────────

/** Generate a LlamaFactory YAML config for a training job */
export function generateLlamaFactoryConfig(job: TrainingJob): string {
  const lines: string[] = [
    `### LlamaFactory Training Config`,
    `### Generated by HoC Fine-Tune Pipeline`,
    `### Job: ${job.name} (${job.id})`,
    ``,
    `### Model`,
    `model_name_or_path: ${job.baseModel}`,
    ``,
    `### Method`,
    `stage: sft`,
    `do_train: true`,
    `finetuning_type: ${job.method === "full" ? "full" : "lora"}`,
  ];

  if (job.method === "qlora") {
    lines.push(`quantization_bit: ${job.loraConfig.quantBits ?? 4}`);
  }

  lines.push(
    ``,
    `### Dataset`,
    `dataset: ${job.dataset.trainPath}`,
    `template: default`,
    `cutoff_len: ${job.hyperparams.maxSeqLen}`,
    ``,
    `### LoRA`,
    `lora_rank: ${job.loraConfig.rank}`,
    `lora_alpha: ${job.loraConfig.alpha}`,
    `lora_dropout: ${job.loraConfig.dropout}`,
    `lora_target: ${job.loraConfig.targetModules.join(",")}`,
    ``,
    `### Training`,
    `learning_rate: ${job.hyperparams.learningRate}`,
    `num_train_epochs: ${job.hyperparams.epochs}`,
    `per_device_train_batch_size: ${job.hyperparams.batchSize}`,
    `gradient_accumulation_steps: ${job.hyperparams.gradAccumSteps}`,
    `warmup_ratio: ${job.hyperparams.warmupRatio}`,
    `weight_decay: ${job.hyperparams.weightDecay}`,
    ``,
    `### Output`,
    `output_dir: /workspace/finetune/${job.id}`,
    `logging_steps: 10`,
    `save_steps: 100`,
    `save_total_limit: 3`,
    `fp16: true`,
  );

  return lines.join("\n");
}

// ─── Diagnostics ─────────────────────────────────────────────────

export function getFineTuneDiagnostics(): FineTuneDiagnostics {
  const all = [...jobs.values()];
  const completed = all.filter((j) => j.status === "complete");
  const totalTime = completed.reduce((s, j) => {
    if (j.startedAt && j.completedAt) {
      return s + (new Date(j.completedAt).getTime() - new Date(j.startedAt).getTime());
    }
    return s;
  }, 0);

  return {
    totalJobs: all.length,
    activeJobs: all.filter((j) =>
      ["preparing", "training", "evaluating", "merging"].includes(j.status),
    ).length,
    completedJobs: completed.length,
    failedJobs: all.filter((j) => j.status === "failed").length,
    avgTrainingTimeMinutes:
      completed.length > 0 ? Math.round(totalTime / completed.length / 60_000) : 0,
    modelsProduced: completed.filter((j) => j.outputPath).length,
  };
}

/** Reset (testing) */
export function resetFineTunePipeline(): void {
  jobs.clear();
  idCounter = 0;
}
