import type { SeedDomain } from "./seed-data.js";

export const medicineDomains: SeedDomain[] = [
  {
    path: "Medicine",
    name: "Medicine",
    description: "The science and practice of diagnosing, treating, and preventing disease",
    coreSkills: [
      "clinical-assessment",
      "patient-communication",
      "medical-ethics",
      "evidence-based-medicine",
    ],
    minPracticeLevel: "bachelor",
  },
  {
    path: "Medicine.GeneralPractice",
    name: "General Practice",
    description:
      "Primary healthcare covering common conditions, preventive care, and patient triage",
    coreSkills: [
      "physical-examination",
      "history-taking",
      "differential-diagnosis",
      "preventive-care",
      "referral-management",
    ],
    minPracticeLevel: "bachelor",
  },
  // ─── RADIOLOGY ────────────────────────────────────────────────────────────────
  {
    path: "Medicine.Radiology",
    name: "Radiology",
    description:
      "Medical imaging interpretation — MRI, CT, X-ray, ultrasound analysis and diagnosis",
    coreSkills: [
      "mri-interpretation",
      "ct-scan-analysis",
      "x-ray-reading",
      "ultrasound-analysis",
      "radiological-reporting",
      "tumor-identification",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Radiology.Neuroradiology",
    name: "Neuroradiology",
    description: "Subspecialty focused on brain and nervous system imaging",
    coreSkills: [
      "brain-mri",
      "spinal-imaging",
      "neuroanatomy",
      "stroke-detection",
      "tumor-grading",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Radiology.InterventionalRadiology",
    name: "Interventional Radiology",
    description: "Minimally invasive image-guided procedures for diagnosis and treatment",
    coreSkills: [
      "angiography",
      "catheter-placement",
      "embolization",
      "biopsy-guidance",
      "drainage-procedures",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Radiology.NuclearMedicine",
    name: "Nuclear Medicine",
    description: "PET and SPECT radiotracer imaging for metabolic disease diagnosis",
    coreSkills: ["pet-scan-analysis", "spect-imaging", "radiopharmaceuticals", "dosimetry"],
    minPracticeLevel: "master",
  },
  // ─── PHARMACOLOGY ─────────────────────────────────────────────────────────────
  {
    path: "Medicine.Pharmacology",
    name: "Pharmacology",
    description:
      "Drug action mechanisms, interactions, dosage optimization, and prescription safety",
    coreSkills: [
      "drug-interaction-analysis",
      "dosage-calculation",
      "pharmacokinetics",
      "adverse-event-detection",
      "prescription-validation",
    ],
    minPracticeLevel: "bachelor",
  },
  {
    path: "Medicine.Pharmacology.ClinicalPharmacy",
    name: "Clinical Pharmacy",
    description: "Patient-centered medication therapy management and pharmaceutical care",
    coreSkills: [
      "medication-review",
      "therapeutic-monitoring",
      "patient-counseling",
      "formulary-management",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Pharmacology.Toxicology",
    name: "Toxicology",
    description: "Study of adverse effects of chemical substances on living organisms",
    coreSkills: [
      "poison-identification",
      "antidote-management",
      "toxicology-screening",
      "occupational-exposure",
      "forensic-toxicology",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Pharmacology.Pharmacogenomics",
    name: "Pharmacogenomics",
    description: "Genetic factors influencing individual drug response for personalized medicine",
    coreSkills: [
      "genetic-profiling",
      "drug-genome-interaction",
      "personalized-dosing",
      "biomarker-analysis",
    ],
    minPracticeLevel: "doctorate",
  },
  // ─── PSYCHIATRY ───────────────────────────────────────────────────────────────
  {
    path: "Medicine.Psychiatry",
    name: "Psychiatry",
    description: "Mental health diagnosis, treatment planning, and therapeutic intervention",
    coreSkills: [
      "psychiatric-assessment",
      "diagnosis-dsm",
      "treatment-planning",
      "psychopharmacology",
      "crisis-intervention",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Psychiatry.ChildPsychiatry",
    name: "Child Psychiatry",
    description: "Pediatric mental health specializing in developmental and behavioral disorders",
    coreSkills: [
      "developmental-assessment",
      "adhd-evaluation",
      "autism-screening",
      "behavioral-intervention",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Psychiatry.Neuropsychiatry",
    name: "Neuropsychiatry",
    description: "Interface of neurology and psychiatry for brain-behavior disorders",
    coreSkills: [
      "cognitive-assessment",
      "brain-behavior-analysis",
      "neuropsychological-testing",
      "tbi-management",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Psychiatry.AddictionMedicine",
    name: "Addiction Medicine",
    description: "Prevention, evaluation, and treatment of substance use disorders",
    coreSkills: [
      "substance-assessment",
      "withdrawal-management",
      "motivational-interviewing",
      "relapse-prevention",
    ],
    minPracticeLevel: "master",
  },
  // ─── ENDOCRINOLOGY ────────────────────────────────────────────────────────────
  {
    path: "Medicine.Endocrinology",
    name: "Endocrinology",
    description: "Hormone disorders, diabetes, thyroid conditions, and metabolic diseases",
    coreSkills: [
      "hormone-analysis",
      "diabetes-management",
      "thyroid-evaluation",
      "metabolic-assessment",
      "insulin-optimization",
    ],
    minPracticeLevel: "master",
  },
  // ─── SURGERY ──────────────────────────────────────────────────────────────────
  {
    path: "Medicine.Surgery",
    name: "Surgery",
    description: "Surgical procedure planning, techniques, and post-operative care",
    coreSkills: [
      "surgical-planning",
      "anatomy-knowledge",
      "procedure-documentation",
      "post-op-management",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Surgery.Neurosurgery",
    name: "Neurosurgery",
    description: "Surgical treatment of brain, spinal cord, and peripheral nerve disorders",
    coreSkills: [
      "brain-surgery",
      "spinal-surgery",
      "tumor-resection",
      "aneurysm-clipping",
      "deep-brain-stimulation",
      "intraoperative-monitoring",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Surgery.CardiothoracicSurgery",
    name: "Cardiothoracic Surgery",
    description: "Surgical treatment of heart, lungs, and chest diseases",
    coreSkills: [
      "cardiac-bypass",
      "valve-repair",
      "lung-resection",
      "thoracoscopy",
      "aortic-surgery",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Surgery.OrthopedicSurgery",
    name: "Orthopedic Surgery",
    description: "Surgical correction of musculoskeletal conditions, fractures, and joint diseases",
    coreSkills: [
      "fracture-fixation",
      "joint-replacement",
      "arthroscopy",
      "spine-surgery",
      "sports-injury-repair",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Surgery.PlasticSurgery",
    name: "Plastic Surgery",
    description: "Reconstructive and aesthetic surgical procedures",
    coreSkills: [
      "reconstructive-surgery",
      "wound-closure",
      "flap-techniques",
      "burn-management",
      "microsurgery",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Surgery.VascularSurgery",
    name: "Vascular Surgery",
    description: "Surgical treatment of arteries and veins excluding heart and brain",
    coreSkills: [
      "aneurysm-repair",
      "bypass-grafting",
      "endovascular-intervention",
      "venous-surgery",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Surgery.ColorectalSurgery",
    name: "Colorectal Surgery",
    description: "Surgical treatment of colon, rectum, and anus conditions",
    coreSkills: [
      "colectomy",
      "proctology",
      "laparoscopic-bowel-surgery",
      "stoma-management",
      "oncological-rectal-surgery",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Surgery.TransplantSurgery",
    name: "Transplant Surgery",
    description: "Organ transplantation including kidney, liver, heart, and lung",
    coreSkills: [
      "organ-procurement",
      "immunosuppression",
      "rejection-management",
      "transplant-selection",
    ],
    minPracticeLevel: "doctorate",
  },
  // ─── CARDIOLOGY ───────────────────────────────────────────────────────────────
  {
    path: "Medicine.Cardiology",
    name: "Cardiology",
    description: "Heart and cardiovascular system diagnosis and treatment",
    coreSkills: [
      "ecg-interpretation",
      "cardiac-imaging",
      "hemodynamic-analysis",
      "arrhythmia-detection",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Cardiology.Electrophysiology",
    name: "Cardiac Electrophysiology",
    description: "Diagnosis and treatment of heart rhythm disorders",
    coreSkills: [
      "ep-study",
      "ablation-therapy",
      "pacemaker-implantation",
      "defibrillator-programming",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Cardiology.InterventionalCardiology",
    name: "Interventional Cardiology",
    description: "Catheter-based procedures for coronary artery disease",
    coreSkills: [
      "coronary-angiography",
      "pci-stenting",
      "valve-intervention",
      "structural-heart-disease",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Cardiology.HeartFailure",
    name: "Heart Failure & Transplant",
    description: "Advanced management of heart failure and cardiac device therapy",
    coreSkills: [
      "ventricular-assist-devices",
      "heart-transplant-workup",
      "hemodynamic-optimization",
      "palliative-cardiology",
    ],
    minPracticeLevel: "doctorate",
  },
  // ─── ONCOLOGY ──────────────────────────────────────────────────────────────────
  {
    path: "Medicine.Oncology",
    name: "Oncology",
    description: "Cancer diagnosis, staging, treatment planning, and management",
    coreSkills: [
      "tumor-staging",
      "chemotherapy-planning",
      "biomarker-analysis",
      "survivorship-care",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Oncology.RadiationOncology",
    name: "Radiation Oncology",
    description: "Use of radiation to treat cancer — planning and delivery",
    coreSkills: ["radiation-planning", "dosimetry", "stereotactic-radiosurgery", "proton-therapy"],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Oncology.HematologicOncology",
    name: "Hematologic Oncology",
    description: "Blood cancers including leukemia, lymphoma, and myeloma",
    coreSkills: ["bone-marrow-analysis", "stem-cell-transplant", "immunotherapy", "car-t-therapy"],
    minPracticeLevel: "doctorate",
  },
  // ─── DERMATOLOGY ──────────────────────────────────────────────────────────────
  {
    path: "Medicine.Dermatology",
    name: "Dermatology",
    description: "Skin conditions diagnosis using visual analysis and dermoscopy",
    coreSkills: [
      "lesion-classification",
      "dermoscopy",
      "skin-biopsy-analysis",
      "treatment-planning",
    ],
    minPracticeLevel: "master",
  },
  // ─── PATHOLOGY ────────────────────────────────────────────────────────────────
  {
    path: "Medicine.Pathology",
    name: "Pathology",
    description: "Disease diagnosis through laboratory analysis of tissues and body fluids",
    coreSkills: ["histopathology", "cytology", "molecular-diagnostics", "autopsy-analysis"],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Pathology.ForensicPathology",
    name: "Forensic Pathology",
    description: "Determination of cause of death for legal and criminal investigations",
    coreSkills: [
      "autopsy-technique",
      "cause-of-death-determination",
      "forensic-evidence",
      "toxicology-screening",
    ],
    minPracticeLevel: "doctorate",
  },
  // ─── NEUROLOGY ────────────────────────────────────────────────────────────────
  {
    path: "Medicine.Neurology",
    name: "Neurology",
    description:
      "Nervous system disorders including stroke, epilepsy, and neurodegenerative diseases",
    coreSkills: [
      "neurological-exam",
      "eeg-interpretation",
      "stroke-management",
      "dementia-assessment",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Neurology.Epileptology",
    name: "Epileptology",
    description: "Specialized management of epilepsy and seizure disorders",
    coreSkills: [
      "eeg-analysis",
      "seizure-classification",
      "antiepileptic-therapy",
      "surgical-candidacy",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Neurology.MovementDisorders",
    name: "Movement Disorders",
    description: "Parkinson's disease, tremors, dystonia, and related conditions",
    coreSkills: ["parkinson-assessment", "dbs-management", "botox-injection", "gait-analysis"],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Neurology.Neuroimmunology",
    name: "Neuroimmunology",
    description: "Autoimmune and inflammatory disorders of the nervous system",
    coreSkills: [
      "ms-management",
      "immunosuppression-neuro",
      "lumbar-puncture",
      "autoantibody-testing",
    ],
    minPracticeLevel: "doctorate",
  },
  // ─── PULMONOLOGY ──────────────────────────────────────────────────────────────
  {
    path: "Medicine.Pulmonology",
    name: "Pulmonology",
    description: "Lung and respiratory system disorders including COPD, asthma, and pneumonia",
    coreSkills: ["spirometry", "bronchoscopy", "ventilator-management", "pleural-procedures"],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Pulmonology.CriticalCare",
    name: "Critical Care Medicine",
    description: "Intensive care management of life-threatening conditions",
    coreSkills: [
      "mechanical-ventilation",
      "sepsis-management",
      "hemodynamic-monitoring",
      "organ-failure-support",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Pulmonology.SleepMedicine",
    name: "Sleep Medicine",
    description: "Diagnosis and treatment of sleep disorders including apnea and insomnia",
    coreSkills: [
      "polysomnography",
      "cpap-titration",
      "sleep-disorder-classification",
      "cbt-insomnia",
    ],
    minPracticeLevel: "master",
  },
  // ─── GASTROENTEROLOGY ─────────────────────────────────────────────────────────
  {
    path: "Medicine.Gastroenterology",
    name: "Gastroenterology",
    description: "Digestive system disorders including IBD, GERD, and liver conditions",
    coreSkills: [
      "endoscopy",
      "colonoscopy",
      "liver-assessment",
      "ibd-management",
      "gi-bleeding-control",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Gastroenterology.Hepatology",
    name: "Hepatology",
    description: "Liver, gallbladder, biliary tract, and pancreas diseases",
    coreSkills: [
      "liver-biopsy",
      "cirrhosis-management",
      "viral-hepatitis",
      "transplant-hepatology",
    ],
    minPracticeLevel: "doctorate",
  },
  // ─── IMMUNOLOGY ───────────────────────────────────────────────────────────────
  {
    path: "Medicine.Immunology",
    name: "Clinical Immunology",
    description: "Immune system disorders including autoimmune diseases and immunodeficiencies",
    coreSkills: [
      "immunological-workup",
      "allergy-testing",
      "immunotherapy-protocols",
      "autoimmune-diagnosis",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Immunology.Vaccinology",
    name: "Vaccinology",
    description: "Vaccine development, immunization science, and preventive immunology",
    coreSkills: [
      "vaccine-design",
      "clinical-trials",
      "immunogenicity-testing",
      "adjuvant-formulation",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Immunology.AllergyMedicine",
    name: "Allergy & Immunology",
    description: "Allergic conditions, anaphylaxis management, and desensitization therapy",
    coreSkills: [
      "allergy-testing",
      "immunotherapy-desensitization",
      "anaphylaxis-management",
      "drug-allergy-evaluation",
    ],
    minPracticeLevel: "master",
  },
  // ─── HEMATOLOGY ───────────────────────────────────────────────────────────────
  {
    path: "Medicine.Hematology",
    name: "Hematology",
    description: "Blood disorders including anemia, clotting diseases, and blood cancers",
    coreSkills: [
      "blood-smear-analysis",
      "bone-marrow-biopsy",
      "coagulation-testing",
      "transfusion-medicine",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Hematology.TransfusionMedicine",
    name: "Transfusion Medicine",
    description: "Blood banking, compatibility testing, and transfusion therapy safety",
    coreSkills: ["blood-typing", "crossmatch", "component-therapy", "transfusion-reactions"],
    minPracticeLevel: "master",
  },
  // ─── INFECTIOUS DISEASE ───────────────────────────────────────────────────────
  {
    path: "Medicine.InfectiousDisease",
    name: "Infectious Disease",
    description: "Diagnosis and treatment of bacterial, viral, fungal, and parasitic infections",
    coreSkills: [
      "infection-diagnosis",
      "antimicrobial-stewardship",
      "outbreak-investigation",
      "hiv-management",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.InfectiousDisease.TropicalMedicine",
    name: "Tropical Medicine",
    description:
      "Diseases endemic to tropical regions including malaria, dengue, and leishmaniasis",
    coreSkills: [
      "malaria-management",
      "tropical-parasitology",
      "travel-medicine",
      "vector-control",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.InfectiousDisease.Virology",
    name: "Clinical Virology",
    description: "Viral pathogenesis, antiviral therapy, and pandemic preparedness",
    coreSkills: ["viral-culture", "pcr-diagnostics", "antiviral-pharmacology", "epidemic-modeling"],
    minPracticeLevel: "doctorate",
  },
  // ─── OPHTHALMOLOGY ────────────────────────────────────────────────────────────
  {
    path: "Medicine.Ophthalmology",
    name: "Ophthalmology",
    description: "Eye diseases, vision disorders, and ocular surgery",
    coreSkills: [
      "slit-lamp-examination",
      "oct-interpretation",
      "refraction",
      "intraocular-surgery",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Ophthalmology.RetinalSurgery",
    name: "Retinal Surgery",
    description:
      "Surgical treatment of retinal detachment, macular degeneration, and diabetic retinopathy",
    coreSkills: [
      "vitreoretinal-surgery",
      "anti-vegf-therapy",
      "laser-photocoagulation",
      "oct-angiography",
    ],
    minPracticeLevel: "doctorate",
  },
  // ─── ENT ──────────────────────────────────────────────────────────────────────
  {
    path: "Medicine.Otolaryngology",
    name: "Otolaryngology (ENT)",
    description: "Ear, nose, and throat disorders including hearing loss and sinus disease",
    coreSkills: ["endoscopic-sinus-surgery", "audiometry", "laryngoscopy", "head-neck-oncology"],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Otolaryngology.Otology",
    name: "Otology & Neurotology",
    description: "Ear diseases, cochlear implants, and skull base surgery",
    coreSkills: [
      "cochlear-implant",
      "tympanoplasty",
      "audiological-evaluation",
      "skull-base-surgery",
    ],
    minPracticeLevel: "doctorate",
  },
  // ─── UROLOGY / NEPHROLOGY ─────────────────────────────────────────────────────
  {
    path: "Medicine.Urology",
    name: "Urology",
    description: "Urinary tract and male reproductive system disorders",
    coreSkills: ["cystoscopy", "prostate-assessment", "stone-management", "urodynamics"],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Nephrology",
    name: "Nephrology",
    description: "Kidney diseases, renal failure management, and dialysis",
    coreSkills: [
      "renal-biopsy",
      "dialysis-management",
      "electrolyte-disorders",
      "glomerulonephritis",
    ],
    minPracticeLevel: "master",
  },
  // ─── OB-GYN ───────────────────────────────────────────────────────────────────
  {
    path: "Medicine.Obstetrics",
    name: "Obstetrics",
    description: "Pregnancy, childbirth, and postpartum care",
    coreSkills: [
      "prenatal-assessment",
      "fetal-monitoring",
      "labor-management",
      "caesarean-section",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Gynecology",
    name: "Gynecology",
    description: "Female reproductive system health and disease",
    coreSkills: [
      "pelvic-examination",
      "laparoscopy",
      "hysteroscopy",
      "colposcopy",
      "menstrual-disorders",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Gynecology.ReproductiveMedicine",
    name: "Reproductive Medicine",
    description: "Infertility evaluation, IVF, and assisted reproductive technologies",
    coreSkills: ["ivf-protocols", "ovarian-stimulation", "embryology", "fertility-preservation"],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Gynecology.MaternalFetal",
    name: "Maternal-Fetal Medicine",
    description: "High-risk pregnancy management and fetal diagnosis",
    coreSkills: [
      "fetal-echocardiography",
      "amniocentesis",
      "preterm-birth-management",
      "fetal-intervention",
    ],
    minPracticeLevel: "doctorate",
  },
  // ─── PEDIATRICS ───────────────────────────────────────────────────────────────
  {
    path: "Medicine.Pediatrics",
    name: "Pediatrics",
    description: "Medical care of infants, children, and adolescents",
    coreSkills: [
      "developmental-assessment",
      "vaccination-schedules",
      "growth-monitoring",
      "pediatric-examination",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Pediatrics.Neonatology",
    name: "Neonatology",
    description: "Medical care of newborns, especially premature and critically ill infants",
    coreSkills: [
      "nicu-management",
      "neonatal-respiratory",
      "neonatal-resuscitation",
      "surfactant-therapy",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Pediatrics.PediatricCardiology",
    name: "Pediatric Cardiology",
    description: "Congenital heart disease and cardiac disorders in children",
    coreSkills: [
      "congenital-heart-diagnosis",
      "echocardiography-pediatric",
      "cardiac-catheterization-ped",
      "fontan-management",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Pediatrics.PediatricOncology",
    name: "Pediatric Oncology",
    description: "Cancer diagnosis and treatment in children and adolescents",
    coreSkills: [
      "leukemia-pediatric",
      "brain-tumor-children",
      "chemotherapy-pediatric",
      "survivorship-pediatric",
    ],
    minPracticeLevel: "doctorate",
  },
  // ─── ANESTHESIOLOGY ───────────────────────────────────────────────────────────
  {
    path: "Medicine.Anesthesiology",
    name: "Anesthesiology",
    description: "Perioperative care, sedation, and pain management",
    coreSkills: ["general-anesthesia", "regional-anesthesia", "airway-management", "pain-acute"],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Anesthesiology.PainManagement",
    name: "Pain Medicine",
    description: "Chronic pain evaluation and multidisciplinary treatment",
    coreSkills: ["interventional-pain", "opioid-management", "nerve-blocks", "neuromodulation"],
    minPracticeLevel: "doctorate",
  },
  // ─── REHABILITATION ───────────────────────────────────────────────────────────
  {
    path: "Medicine.Rehabilitation",
    name: "Physical Medicine & Rehabilitation",
    description: "Restoring function and quality of life after disease or injury",
    coreSkills: [
      "functional-assessment",
      "rehabilitation-planning",
      "prosthetics-orthotics",
      "spasticity-management",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Rehabilitation.SportsMedicine",
    name: "Sports Medicine",
    description: "Athletic injuries, performance optimization, and exercise physiology",
    coreSkills: [
      "musculoskeletal-assessment",
      "return-to-play-protocols",
      "concussion-management",
      "exercise-prescription",
    ],
    minPracticeLevel: "master",
  },
  // ─── EMERGENCY MEDICINE ───────────────────────────────────────────────────────
  {
    path: "Medicine.EmergencyMedicine",
    name: "Emergency Medicine",
    description: "Acute care for undifferentiated medical emergencies in the ED",
    coreSkills: [
      "triage",
      "resuscitation",
      "emergency-procedures",
      "toxicology-emergency",
      "trauma-assessment",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.EmergencyMedicine.DisasterMedicine",
    name: "Disaster Medicine",
    description: "Medical response to mass casualty events and natural disasters",
    coreSkills: ["mass-casualty-triage", "field-medicine", "incident-command", "pandemic-response"],
    minPracticeLevel: "master",
  },
  // ─── GENETICS ─────────────────────────────────────────────────────────────────
  {
    path: "Medicine.Genetics",
    name: "Medical Genetics",
    description: "Hereditary conditions, chromosome abnormalities, and genetic counseling",
    coreSkills: ["genetic-testing", "karyotyping", "genetic-counseling", "pedigree-analysis"],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Genetics.GenomicMedicine",
    name: "Genomic Medicine",
    description: "Application of genomic information for personalized healthcare",
    coreSkills: [
      "whole-genome-sequencing",
      "variant-interpretation",
      "polygenic-risk-scores",
      "pharmacogenomics",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Genetics.CRISPR",
    name: "CRISPR Gene Editing",
    description: "Precision genome editing for therapeutic and research applications",
    coreSkills: [
      "crispr-cas9",
      "guide-rna-design",
      "off-target-analysis",
      "gene-therapy-delivery",
      "prime-editing",
      "base-editing",
    ],
    minPracticeLevel: "doctorate",
  },
  {
    path: "Medicine.Genetics.Epigenetics",
    name: "Epigenetics",
    description: "Heritable gene expression changes without DNA sequence alterations",
    coreSkills: [
      "dna-methylation-analysis",
      "histone-modification",
      "chromatin-remodeling",
      "epigenome-association",
    ],
    minPracticeLevel: "doctorate",
  },
  // ─── GERONTOLOGY ──────────────────────────────────────────────────────────────
  {
    path: "Medicine.Gerontology",
    name: "Gerontology",
    description: "Science of aging — biology, psychology, and social aspects of growing older",
    coreSkills: [
      "aging-biology",
      "longevity-assessment",
      "age-related-disease",
      "frailty-evaluation",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Gerontology.Geriatrics",
    name: "Geriatrics",
    description: "Clinical care of elderly patients with complex multisystem diseases",
    coreSkills: [
      "geriatric-assessment",
      "dementia-management",
      "polypharmacy-review",
      "falls-prevention",
    ],
    minPracticeLevel: "master",
  },
  {
    path: "Medicine.Gerontology.LongevityMedicine",
    name: "Longevity Medicine",
    description: "Evidence-based interventions to extend healthspan and combat aging biology",
    coreSkills: [
      "senolytic-therapy",
      "nad-metabolism",
      "biological-age-testing",
      "longevity-biomarkers",
    ],
    minPracticeLevel: "doctorate",
  },
];
